### ISSUE TITLE
[UI] - Evaluation

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#1]
- [ ] Employee ไม่มีลูกน้อง

![Image](https://user-images.githubusercontent.com/126447414/236756064-1566f14d-12e8-444f-832f-89bdcf1161c3.png)

- [ ] Employee มีลูกน้อง

![Image](https://user-images.githubusercontent.com/126447414/236756161-73c516c3-c7ee-401e-8c4f-7c41202efe59.png)

![Image](https://user-images.githubusercontent.com/126447414/236756201-3b558f8f-fcd1-42cf-b2e8-57d5b84444db.png)

- [ ] level E up

![Image](https://user-images.githubusercontent.com/126447414/236756392-8358b3a1-c4ca-4d29-b35a-4a800c79efb9.png)

> 

- [ ] กด record ที่ Subordinate เปิดเป็นหน้า 👇

![Image](https://user-images.githubusercontent.com/126447414/236756693-88d2d6c8-3f68-4c0a-9326-5d4197469ddd.png)

- [ ]  กด record ที่ 360 Evaluator เปิดเป็นหน้า 👇 แบบประเมินของ Staff นั้น

![Image](https://user-images.githubusercontent.com/126447414/236757483-18d74627-82f4-4e69-ac4b-9c228b2c7efc.png)

- [ ] กดปุ่ม 360 Evaluator 

![Image](https://user-images.githubusercontent.com/126447414/236757707-e3752ddb-77f0-4ef6-b729-a648ceb30897.png)

**Comment by sainamphung** [comment]
เติม weight ใน core value evaluation
