### ISSUE TITLE
[UI] - Goal Setting-KPI

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#10]
- [x] Employee ไม่มีลูกน้อง

![Image](https://user-images.githubusercontent.com/126447414/236798170-55890330-cee3-4355-b750-d42aeea7d0af.png)
 
- [x] Employee ไม่ใช่ E+ , มีลูกน้อง

![Image](https://user-images.githubusercontent.com/126447414/236798403-437d80e9-ba4e-43da-9eb3-ec59d927552d.png)

- [x] Employee E+

![Image](https://user-images.githubusercontent.com/126447414/236798567-823365e2-ebca-46dc-acee-0a76efb821e5.png)

- [x] Only Admin

![Image](https://user-images.githubusercontent.com/126447414/236798732-12defe6e-f6e5-405d-998e-9fb77856d512.png)

**Comment by sainamphung** [comment]
เปลี่ยน design แล้ว
