### ISSUE TITLE
[Function] - Supervisor can see PM Setting, Evaluation, Summary button

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#100]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1429b06e-866d-42ad-8c2d-c9ccb3220255)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0e773459-7b9d-441e-9248-f95564dd94ab)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a90da01a-3585-4c62-80a4-07a00222a4b4)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/92a72b25-f1be-4744-b281-159816048335)
