### ISSUE TITLE
[Function] - Employee with level F,G,H,I which no team can see Evaluation button

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#101]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ac6efe10-ee40-4e48-b74e-c3801941194b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/121ddd29-4a03-4fe3-8f00-1cd29b70d4e4)
