### ISSUE TITLE
[Query] - Add core value score from supervisor

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#113]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9d1ec620-ec56-4fd2-b56b-530fe6f8e99e)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a6b439de-8e27-40c9-8fa9-3a4d2d29eafa)
