### ISSUE TITLE
[Function] - Show each page like employee who admin is selected to act as

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#118]

**Comment by nawapornmanyanon** [comment]
เพิ่มของอีก  2    หน้า

[PMSetting][Overall][Detail] **[DepartmentKPI]**

[PMSetting][Overall][Detail] **[IndividualKPI]**

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c83d1511-1fed-40cb-b791-fabcbb1f83c4)

**Comment by nawapornmanyanon** [comment]
Evaluation

- [ ] KPI evaluation - Department KPI
- [ ] KPI evaluation - Individual KPI
- [ ] Core value evaluation 
- [ ] Engagement survey

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0e0adee7-ab2b-467d-8ee1-662292cbaacc)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a1ab4ddd-c705-47f8-a778-2d909d397f29)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/520203f8-e33f-4506-ac10-c0c3bdf73757)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/69beccc2-2c65-4722-a676-f5f3fbddbc1e)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a1862cf0-687f-48f8-9c7d-b10ce0c39215)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f0ad9e71-1cb8-4a4b-b085-2fc3f607e60d)
