### ISSUE TITLE
[API] - getDivisionProgressStatus

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#119]
**Description**: ดึง progress ของแต่ละ step มาคิดว่า summitted ไปทั้งหมดกี่ % แล้ว โดยแสดงเป็นราย division
- Calculate % from status to show in progress page
- Get progress status all division
- แสดงเฉพาะ department ที่ admin คนนั้นดูแลอยู่

**Table**:
- admins
- admins_to_company
- admins_to_department
- kpi_evaluate
- kpi_evaluate_detail
- core_value
- engagement

**Params**:
- current_employee_id

**Response**:
```
[
 {
  "division_id": "division code",
  "company": "",
  "department": "department_name",
  "division": "division_name",
  "head_name": "head_name",
  "goal_setting_progress": 0, // Submitted percentage จาก Kpi evaluate ของคนทั้งหมดใน division (KPI submitted number / number of team in division) * 100
  "self_evaluation_progress": 0, // Submitted percentage จาก KPI_evaluate, core_value, engagement submitted number / number of team in division)  * 100
"supervisor_evaluation_progress": 0 // Submitted percentage จาก KPI_evaluate, core value = (Submitted kpi_evaluate and core_value / number of team member in division) * 100
 }
]
```

**Comment by sainamphung** [comment]
ต้องแสดงทุก division ที่ admin คนนั้นดูแลอยู่

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/295f46aa-8aeb-45cd-93ba-2199cda2b0cf)

**Comment by nawapornmanyanon** [comment]
[
 {
  "division_id": "division code",
  "company": "",
  "department": "department_name",
  "division": "division_name",
  "head_name": "head_name",
  "goal_setting_progress": 0, // Submitted percentage จาก Kpi evaluate ของคนทั้งหมดใน division (KPI submitted number / number of team in division) * 100
  "self_evaluation_progress": 0, // Submitted percentage จาก KPI_evaluate, core_value, engagement submitted number / number of team in division)  * 100
"supervisor_evaluation_progress": 0 // Submitted percentage จาก KPI_evaluate, core value = (Submitted kpi_evaluate and core_value / number of team member in division) * 100
 }
]

-----------------


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cb291038-6b1f-4b5a-b841-bbb3c6001059)

**Comment by peravat** [comment]
@nawapornmanyanon จากที่ตรวจสอบนะครับ KPI_evaluate, engagement ยังไม่มี submitted สักคนเลยครับ

KPI_evaluate:

![Image](https://github.com/S4-Internal-app/Evaluated/assets/133958310/b628e722-07fe-4468-a710-db4cb0dfc806)



engagement: 
![Image](https://github.com/S4-Internal-app/Evaluated/assets/133958310/cf41627d-12fd-4cd3-9086-821592c6124d)

**Comment by peravat** [comment]
@nawapornmanyanon  แต่ mlab ขึ้นปกตินะครับ


![Image](https://github.com/S4-Internal-app/Evaluated/assets/133958310/2669ffaa-e2e1-45db-9197-cbdb1317bf99)

**Comment by nawapornmanyanon** [comment]
อันนี้ยิง data ที่ test server ใช่ ัั

ใช้มั้ย

venture lab in02000 ป่ะ มามั้ยอ่ะ

**Comment by peravat** [comment]
ใช่ครับ db test ครับ

IN02000 ครับ

**Comment by nawapornmanyanon** [comment]
core value in02000 มี submit มั้ย

แล้วเวลา get มันมามั้ย

เมื่อคืนพี่ ยิงแล้วไม่มาอ่ะ

**Comment by peravat** [comment]
core value มี submitted ครับ get ที่ว่า หมายถึง "self_evaluation_progress" ใช่ไหมครับ
![Image](https://github.com/S4-Internal-app/Evaluated/assets/133958310/e40e0acd-3147-4ee3-b4b5-649d076bf7a4)

**Comment by nawapornmanyanon** [comment]
ใช่  เข้าว่า มันเป็นค่ารวมของ evaluation+corevalue+engagement

**Comment by nawapornmanyanon** [comment]
สรุปว่า ต้องมี Submit ทั้ง 3 ตัว ( KPI + CoreValue + Engagement)  อย่างน้อย 1  คน ระบบถึงจะ คิดเป็น 1 % ใน 100 % ให้

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e2ccd950-4a5e-4be9-9462-2b234caa4329)
