### ISSUE TITLE
[API] - getEmployeeEngagementSurveyStatus

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#123]
**Description**: get engagement result to show in engagement result page

**Table**:
- employee
- office_master
- engagement
- admins
- admins_to_company
- admins_to_department

**Params**:
- current_employee_id

**Response**:
```
[
 {
  "employee_id": "",
  "employee_name": "",
  "employee_email": "",
  "department": "department_name",
  "division": "division_name",
  "employee_level": "",
  "supervisor": "supervisor name",
  "status": ""
 }
]
```

**Comment by sainamphung** [comment]
response key ผิด line 200 employee_level ต้องเป็น supervisor

**Comment by sainamphung** [comment]
ต้องแสดงทุกคนที่อยู่ใน company/department ที่คนนั้นดูแล

**Comment by nawapornmanyanon** [comment]
Pass
