### ISSUE TITLE
[Auth] - Integrate  AD authen api with app

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#130]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a206b577-c83c-49e6-83bf-23e23385253d)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5606c9df-c55a-47d6-8dae-5675a6faf091)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5dc99f91-d58b-4888-acd6-beec751ef5a1)
