### ISSUE TITLE
[Edit_admin_list] - name List ให้ Query เฉพาะคนที่อยู่ใน Division PE01000 กับ PE05000 มาแสดง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#140]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3f9491bf-04c2-48da-9c7f-482746ce4220)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dd759ad7-2aa8-4572-b387-770dc9138be6)

**Comment by sainamphung** [comment]
มีเพิ่มพี่เกดเข้าไปด้วย 1 คนค่ะ

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/aa4df253-329e-47a9-8a8a-da0a5e69e9ea)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2e609072-c913-4f33-a87e-416d4adf681d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a6500186-8012-4ad3-b5d2-c7b48a4fcab3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7f79b212-af2e-41a0-a5ae-1d201338323a)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d8ebbd34-67a1-43ab-8d2c-5d6626a9125e)
