### ISSUE TITLE
[System Setting][Administrator_tab] - กด save Admin แล้ว ให้กลับมา tab ของ Admin และ แสดง Message ว่า Update admin success

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#146]
กด save จากหน้า Update admin 
**Expected result :**
แสดงหน้า System setting - Administrator tab และแสดง Message Update admin success

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9c55992d-e3df-44ed-a583-aeea6b13ea11)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/fb49cd3c-2019-400c-97f9-d04343494086)

**Comment by nawapornmanyanon** [comment]
Cancel 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/09487c0a-f95c-49a7-95d3-ee238da94609)

**Comment by nawapornmanyanon** [comment]
save


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dcb636fc-8432-46ef-b3fa-d2330a078f8d)
