### ISSUE TITLE
[UI] - Update assign department KPI page

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#150]

**Comment by nawapornmanyanon** [comment]
KPIEmployeeAssign


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/135cd486-c0cd-4bab-a45b-09ba5f3c9752)




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9e89f73b-9711-482f-b013-62701f30c1af)
