### ISSUE TITLE
[Function] - Validate % of department KPI and individual KPI

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#153]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/7d72bb28-51bc-4ec7-b3c9-de49b4e1714d)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/463b087b-3a56-4941-b4f4-ab78b17b083a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5c70f5f1-4ec3-4e87-ad60-86d45b3a2bd2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f9cf4037-c217-4fe0-80bc-a7248ccc016b)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7e1022b2-3286-4e1e-b546-783b28737bd2)
