### ISSUE TITLE
[UI] - Add new page for edit % of KPI

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#155]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6dc74c2b-9a30-4ba7-a997-6795e8df8595)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a36e644b-f95f-402c-854e-485a0a42e9a3)
