### ISSUE TITLE
[Function] - Update function support new flow

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#157]
Assign department KPI ให้พนักงานทีละหลายๆคน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f11e4fd4-42a5-4ad1-a1a3-58a4772b0048)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/512dd364-819f-4492-bf27-eae92d977612)

**Comment by nawapornmanyanon** [comment]
Pass
