### ISSUE TITLE
[API] - getTeamMemberForSelectByKPIType

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#158]
**Condition**:
- เชคจาก % ของ department KPI ว่าต้องไม่ใช่ 0
- ไม่ใช่คนที่ถูก assign department KPI ไปแล้ว

**Description**: Get team member for selection

**Table**:
- employee
- kpi_evaluate
- kpi_evaluate_detail

**Params**:
- supervisor_id
- kpi_type

**Response**:
```
[
  {
    "employee_id": "employee_id",
    "employee_name": "employee_name",
    "position": "employee_position"
  }
]
```

**Comment by sainamphung** [comment]
เรียก API นี้แล้วไม่มี data ส่งมาให้

**Comment by nawapornmanyanon** [comment]
Individual

{
  "payload": [
    {
      "division_name": "M-Lab",
      "employee_id": "03087",
      "employee_name": "Phumchanok Sakdakampanart",
      "employee_nickname": "Card",
      "position": "Software Developer"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03093",
      "employee_name": "Chutikarn Puttiwarodom",
      "employee_nickname": "May",
      "position": "Software Developer"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03331",
      "employee_name": "Nakarin Jungate",
      "employee_nickname": "flook",
      "position": "Software Developer"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03357",
      "employee_name": "Sutharat Aumfak",
      "employee_nickname": "Aon",
      "position": "Software Tester"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03549",
      "employee_name": "Peravat Burinkot",
      "employee_nickname": "Jo",
      "position": "Software Developer"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03827",
      "employee_name": "Tanawat Limsakul",
      "employee_nickname": "Earth",
      "position": "Software Developer"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "03832",
      "employee_name": "Prangprai Rattanachetchutha",
      "employee_nickname": "Ploy",
      "position": "Software Tester"
    },
    {
      "division_name": "M-Lab",
      "employee_id": "04578",
      "employee_name": "Puttiphong Boonsiri",
      "employee_nickname": "P",
      "position": "Software Developer"
    }
  ]
}

**Comment by nawapornmanyanon** [comment]
OK. , List คนที่ยังไม่ Assign มาให้
