### ISSUE TITLE
[Function] - Call API getTeamMemberForSelectByKPIType with individual type

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#161]
Condition
- เชคจาก % ของ individual KPI ว่าต้องไม่ใช่ 0
- ไม่ใช่คนที่ถูก assign individual KPI ไปแล้ว

**Comment by nawapornmanyanon** [comment]
API นี้ใช้ได้แระ พี่ Test ข้อมูลมา

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/52977494-e067-49c6-ac32-faf2fb6fa31b)


ยังไม่ได้ถูกเอาไปใช้

**Comment by warakornlj** [comment]
Department KPI


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/4634aade-a1a6-47c8-8955-a79cf71009f1)

**Comment by warakornlj** [comment]
Individual KPI



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/255880e2-7bc6-452d-9aed-5d8e8e09edf3)

**Comment by nawapornmanyanon** [comment]
ได้มาแล้ว
