### ISSUE TITLE
[Function] - Call API updateEmployeeKPIByKPIType

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#163]
Update individual KPI to each employee

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3df6d061-5832-43cf-9a53-0728baf4e923)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/839543d6-65f4-4d65-8ec3-da8dee2d6c54)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/39842d26-008e-4e26-9cdc-2debd7ca5dd0)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/77ca56a3-20ee-44d0-986c-cfcd85723656)
