### ISSUE TITLE
[Bug] - If a user remove or change something in input or select fields and close the modal, once they click the edit button on that row, the data will be showed based on previous action (Add Department, Corporate, Persepective)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#165]

**Comment by nawapornmanyanon** [comment]
App department KPI phase 1 เอา Edit column ออกไปก่อน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a8faec41-36d6-4fb2-ac4c-6170397c6dd1)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f176f7f7-a7af-4d4d-8bd0-8d740b482cce)
