### ISSUE TITLE
[UI] Update Employee ID All page

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#166]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b034921e-7d82-40c4-9cc7-5e1747885255)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/690b6055-a5e0-4776-ad8f-b715d9fe44c6)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e4b387fe-5185-44a8-8a17-2ac8e92260eb)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6d119e23-b0c5-4935-9922-7741ea919367)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/60cb3fb9-f2e1-496f-b32a-778f334ba3d8)
