### ISSUE TITLE
[Auth][Function] Integrate AD to Application

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#177]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/0a9b8a6c-6ce8-44bb-8a45-71a0218c83c6)

**Comment by nawapornmanyanon** [comment]
https://mfeconcloud.sharepoint.com/:o:/s/PMSapp/EriogHjsPJdBuc7N_M48MiABp7mpl4hF-R2MpgVUnVy_9A?e=fvSCHz

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7b8d17c0-16b3-4523-8e69-6f95f9781684)
