### ISSUE TITLE
[Function] Handle function on Assign KPI (Including Validatation)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#186]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/500be7d4-b873-4f29-b349-0c6987f9c47d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8977c4be-0bd6-49a7-b431-710be7d67f50)
