### ISSUE TITLE
[KPI setting][Add perspective] - แก้คำ "Upload department KPI file" เป็น "Upload perspective weight" และ เรียง Column ใหม่

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#188]
แก้คำ "Upload department KPI file" เป็น "Upload perspective weight"

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5d5b651f-32ad-4713-b0b2-1090bd69cd88)
-------
เรียง column ใหม่

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4d96cc7d-3aa5-4813-9cec-4f8e04a54856)

**Comment by nawapornmanyanon** [comment]
@warakornlj  เรียง Column Profit , Resources, Strategic


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f16905cf-8d2f-41cf-b670-1239fe202ea0)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/2e82f60d-2512-4fba-b2ef-8bdf1401a052)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/03940603-ab2f-46e0-bda3-fedc0a1bf1a5)
