### ISSUE TITLE
[PM setting] - เพิ่ม column "position" และแก้ชื่อตาราง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#189]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5b0fd2d8-807f-4295-b894-bbcf5c9abf92)

1. แก้ชื่อ column เป็น Employee ID , Employee name , Position , Goal Setting  ทั้งของ emp_sub และ  emp_class_e_high
2. ปรับพื้นที่ ให้พอดีหน้า

**Comment by warakornlj** [comment]
ตอนนี้ตัว API ได้ Return ค่ามาแค่
EmployeeID, EmployeeName, Department Status, Individual Status ครับ

API ใช้เส้น https://s4-dev-api.mfec.dev/api/v1/pmSetinngs/evaluates/status/supervisors/{{supervisor_id}}

**Comment by nawapornmanyanon** [comment]
OK>


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ef4fb16d-b462-4913-bfd1-f0b2090ba20e)

**Comment by nawapornmanyanon** [comment]
@warakornlj  ใบนี้ถ้าไม่ติดไรแล้ว ย้ายมา Test นะ
