### ISSUE TITLE
[PM setting][no sub] - หน้านี้ไม่มีแล้วเอาออกเลยมั้ย

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#190]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/47ea06ae-fa9f-4a21-8e72-dea124940b7d)

---------

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/56db3e3a-7e31-4c37-a99b-57c4ce768595)

**Comment by sainamphung** [comment]
เอาออกไปเลยก็ได้ค่ะ phase หน้า design ใหม่ ทำใหม่ ไปเลย
