### ISSUE TITLE
[UI] - Edit Goal Setting page

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#20]
- เพิ่ม column Target, Score Measurement
- ตรง Score Measurement สามารถใส่ข้อมูลแยกเป็น 5 ข้อได้

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c0fa9177-9168-4f41-8f4b-5c71ccea7c86)
