### ISSUE TITLE
[Edit_admin_list] - Modal edit admin responsibility แก้ format department name

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#202]
แก้จาก " : "  เป็น " - "  แทน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f11af90a-7813-4a8d-aa2f-f369dc44774d)

1 | MFEC - Business Innovation Unit
2 | MFEC - Commercial Business Sales
3 | MFEC - Corporate Finance Operation
4 | MFEC - Corporate Operation Management
5 | MFEC - Corporate Strategy Planning and Management
6 | MFEC - Enterprise Solutions
7 | MFEC - Executive
8 | MFEC - Government Business Sales
9 | MFEC - Hybrid Infrastructure Services
10 | MFEC - Internal Audit
11 | MFEC - MTIS Business Unit
12 | MFEC - People Excellence
13 | MFEC - Telco Business Unit

ถ้ามี Msyne ด้วย จะมี Department ตามด้านล่าง

14 | Msyne - Consultant Solution Services

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/53c9cd3a-e21d-4ded-b839-9b6fc092e46c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2bd1b70b-fbd2-403d-8577-909102cdf4b1)
