### ISSUE TITLE
[Edit_admin_list] - Admin ต้องไม่สามารถ delete ตัวเองได้

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#205]
Natthida เป็น Admin อยู่   แต่สามารถ Delete ตัวเองได้
**Expected result :**  Admin ต้อง**ไม่สามารถ** Delete ตัวเองได้

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8c5e8f50-6a4c-436b-b4b0-bae5de5ceb8a)

-------

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/5a3944f2-e2c8-4d4e-94c8-9410af00e937)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/139d433b-a09a-4a73-9dde-f230b2f808ca)
