### ISSUE TITLE
[Function][Bugs] - Filter employee in assign KPI and individual

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#207]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ac302943-5086-486d-b99a-0a41c4a154bf)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f4de18c8-50bf-4343-ab21-0246dc16d23f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e59ebeff-66b9-4df5-b611-f24835905829)

**Comment by nawapornmanyanon** [comment]
pass
