### ISSUE TITLE
[Function] Check Flow Duration Setting

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#209]

**Comment by warakornlj** [comment]
1. เคลีย DB ให้ Duration และ KPI ต่างๆ ให้หมด
2. ลองทดสอบ Flow ตั้งแต่ Login แล้วทำการเข้ามา Setup Duration และ Create KPI ต่างๆเพื่อดูว่า จะเข้าตาม FLow มั้ย
3. ทำการเพิ่ม KPI Setting ว่ามันเข้าตาม Duration นั้ๆมั้ย

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/30ef0f95-c951-480c-8b8c-33a4abb170e7)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bae4f0c3-5c63-453a-8e1f-6a0b4b78d088)
