### ISSUE TITLE
[API] - getTeamMemberWithAssignStatus

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#210]
**Description**: get assign status from percent weight in kpi_evaluate_detail of each type of KPI, if percent = 100 status is 'Submitted', if not 100 status is 'Pending'

**Table**: kpi_evaluate, kpi_evaluate_detail

**Parameters**:
- supervisor_id

**Response**:
```
[
 { 
   "employee_id": "",
   "employee_name": "",
   "department_kpi_status": "",
   "individual_kpi_status": ""
 }
]
```

**Comment by sainamphung** [comment]
เพิ่ม column department_kpi_setting_status กับ individual_kpi_setting_status ไม่ต้องคำนวนตาม description แล้ว

**Comment by sainamphung** [comment]
response key ผิด line 461 department_kpi_name ต้องเป็น department_kpi_status

**Comment by sainamphung** [comment]
ถ้า Status = Null คือ status = Pending

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3977608a-2e03-49e7-96b9-81a704c807b3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/78a43590-9997-4592-9d11-19cbed0d84c3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e8c72288-b3a1-424c-b876-ee3be5cab4b5)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4bb6b4f9-d0a1-4614-bb59-4ec0093aa6d1)

**Comment by nawapornmanyanon** [comment]
ลองดูแล้วเหมือนยังไม่ได้เลย ฝาก Check หน่อย @sainamphung

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b52c94c8-495b-4c31-a8a1-edf373b715d6)
