### ISSUE TITLE
[Edit_admin_List] - ไม่ต้องแสดง telephone column

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#211]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/28a5031c-7be9-46d9-9cb2-8035d42fa880)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/481959d7-a846-4b37-8e6b-32432b354d4d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cd6ac9a5-a709-421e-a3a6-05922c0400d6)
