### ISSUE TITLE
[API] - getTeamKPI

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#215]
**Description**: Get department KPI and individual KPI of all team members

**Table**:
- employee
- kpi_evaluate
- kpi_evaluate_detail
- department_kpi
- corporate_kpi
- perspective

**Params**: 
- supervisor_id (str)

**Response**: 
```
{
 "department_kpis": [
  {
   "employee_id": "employee_id",
   "employee_name": "employee_name",
   "postition": "employee position",
   "perspective": "perspective_name",
   "department_kpi": "department_kpi_name",
   "target": "target",
   "measurements": "measurement",
   "weight": 0
  }
 ],
 "individual_kpis": [
  {
   "employee_id": "employee_id",
   "employee_name": "employee_name",
   "postition": "employee position",
   "perspective": "perspective_name",
   "individual_kpi": "individual_kpi_name",
   "target": "target",
   "measurements": "measurement",
   "weight": 0
  }
 ]
}
```

**Notice**: if individual kpi have department_kpi_id, individual_kpi_name = department_kpi_name

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3b5ecec4-cfc1-4896-9bad-800be85b6795)





![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d8cf22dd-2512-4b2c-bfca-459cebd81ab5)
