### ISSUE TITLE
[API] - addKPIToTeamMember

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#216]
**Description**: Bulk save department/individual KPI to team members

**Table**:
- kpi_evaluate
- kpi_evaluate_detail

**Body**:
```
{
  "kpi_type": "kpi_type"
  "employee_ids": [ "employee_id1", "employee_id2" ],
  "kpi_list": [
     {
      "perspective_id": "perspect_id",
      "department_kpi_id": "department_kpi_id",
      "individual_kpi_name": "individual_kpi_name",
      "target": "target",
      "measurements": "measurements",
      "weight": 0,
      "score1": "",
      "score2": "",
      "score3": "",
      "score4": "",
      "score5": ""
     }
    ]
}
}
```

**Response**:
```
200
```

**Comment by nawapornmanyanon** [comment]
API ตัวนี้ ถ้าเป็น "kpi_type": "Individual"  ตัว KPI name มันจะไม่เข้า 
{
  "employee_ids": [
    "02955"
  ],
  "kpi_list": [
    {
      "individual_kpi_name": "Individual KPI 1 - Business Innovation Unit - M-Lab",
      "measurements": "Measurement 1 - Individual KPI 1 - Business Innovation Unit - M-Lab",
      "perspective_id": 3,
      "score1": "KPI 1 - Score1",
      "score2": "KPI 1 - Score2",
      "score3": "KPI 1 - Score3",
      "score4": "KPI 1 - Score4",
      "score5": "KPI 1 - Score5",
      "target": "M-Lab Target 1",
      "weight": 20
    },
    {
      "individual_kpi_name": "Individual KPI 2 - Business Innovation Unit - M-Lab",
      "measurements": "Measurement 2 - Individual KPI 2 - Business Innovation Unit - M-Lab",
      "perspective_id": 2,
      "score1": "KPI 4 - Score1",
      "score2": "KPI 4 - Score2",
      "score3": "KPI 4 - Score3",
      "score4": "KPI 4 - Score4",
      "score5": "KPI 4 - Score5",
      "target": "M-Lab Target 2",
      "weight": 20
    },
    {
      "individual_kpi_name": "Individual KPI 3 - Business Innovation Unit - M-Lab",
      "measurements": "Measurement 3 - Individual KPI 3 - Business Innovation Unit - M-Lab",
      "perspective_id": 1,
      "score1": "KPI 9 - Score1",
      "score2": "KPI 9 - Score2",
      "score3": "KPI 9 - Score3",
      "score4": "KPI 9 - Score4",
      "score5": "KPI 9 - Score5",
      "target": "M-Lab Target 3",
      "weight": 60
    }
  ],
  "kpi_type": "Individual"
}

**Comment by sainamphung** [comment]
ไม่ update status การ assign ใน kpi_evaluate

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/210

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d96a54f1-0989-4959-86fe-c4cf3fb19401)
