### ISSUE TITLE
[API] - getTeamEvaluationStatus

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#220]
**Description**: Get all status of all team members

**Table**: employee, kpi_evaluate, core_value

**Params**:
- supervisor_id

**Response**:
```
[
 {
  "employee_id": "employee_id",
  "employee_name": "employee_name",
  "kpi_evaluate_status": "",
  "core_value_status": "",
  "evaluate_from_supervisor_status":""
 }
]
```

**Note**:
- evaluate_from_supervisor_status เชคจาก status ของหัวหน้าจากทั้ง 2 ตาราง ถ้าเป็น submitted ทั้งคู่ ถึงจะแสดงเป็น submitted นอกนั้นเป็น pending

**Comment by sainamphung** [comment]
response ซ้ำกัน

**Comment by nawapornmanyanon** [comment]
`{
  "payload": [
    {
      "core_value_status": "Pending",
      "employee_id": "00336",
      "employee_name": "Jaruwan Sakthanawat",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "00336",
      "employee_name": "Jaruwan Sakthanawat",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "00336",
      "employee_name": "Jaruwan Sakthanawat",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "01639",
      "employee_name": "Tarit Eakpinitpittaya",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "01639",
      "employee_name": "Tarit Eakpinitpittaya",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "01639",
      "employee_name": "Tarit Eakpinitpittaya",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "02115",
      "employee_name": "Panisara Juljueavong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "02115",
      "employee_name": "Panisara Juljueavong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "02115",
      "employee_name": "Panisara Juljueavong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "02201",
      "employee_name": "Sainamphung Phanphet",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "02201",
      "employee_name": "Sainamphung Phanphet",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "02201",
      "employee_name": "Sainamphung Phanphet",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "02955",
      "employee_name": "Nawaporn Manyanon",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending "
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "02955",
      "employee_name": "Nawaporn Manyanon",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending "
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "02955",
      "employee_name": "Nawaporn Manyanon",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending "
    },
    {
      "core_value_status": "Pending",
      "employee_id": "02977",
      "employee_name": "Wichita Serchuit",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "02977",
      "employee_name": "Wichita Serchuit",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "02977",
      "employee_name": "Wichita Serchuit",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03087",
      "employee_name": "Phumchanok Sakdakampanart",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03087",
      "employee_name": "Phumchanok Sakdakampanart",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03087",
      "employee_name": "Phumchanok Sakdakampanart",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03093",
      "employee_name": "Chutikarn Puttiwarodom",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03093",
      "employee_name": "Chutikarn Puttiwarodom",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03093",
      "employee_name": "Chutikarn Puttiwarodom",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03331",
      "employee_name": "Nakarin Jungate",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03331",
      "employee_name": "Nakarin Jungate",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03331",
      "employee_name": "Nakarin Jungate",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03356",
      "employee_name": "Kamontip Thitimol",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03356",
      "employee_name": "Kamontip Thitimol",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03356",
      "employee_name": "Kamontip Thitimol",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03357",
      "employee_name": "Sutharat Aumfak",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03357",
      "employee_name": "Sutharat Aumfak",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03357",
      "employee_name": "Sutharat Aumfak",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03549",
      "employee_name": "Peravat Burinkot",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03549",
      "employee_name": "Peravat Burinkot",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03549",
      "employee_name": "Peravat Burinkot",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03626",
      "employee_name": "Tammanoon Karnchuchor",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03626",
      "employee_name": "Tammanoon Karnchuchor",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03626",
      "employee_name": "Tammanoon Karnchuchor",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03827",
      "employee_name": "Tanawat Limsakul",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03827",
      "employee_name": "Tanawat Limsakul",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03827",
      "employee_name": "Tanawat Limsakul",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03832",
      "employee_name": "Prangprai Rattanachetchutha",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03832",
      "employee_name": "Prangprai Rattanachetchutha",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03832",
      "employee_name": "Prangprai Rattanachetchutha",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "03996",
      "employee_name": "Warakorn Lertwattanapong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "03996",
      "employee_name": "Warakorn Lertwattanapong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "03996",
      "employee_name": "Warakorn Lertwattanapong",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "04578",
      "employee_name": "Puttiphong Boonsiri",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "04578",
      "employee_name": "Puttiphong Boonsiri",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "04578",
      "employee_name": "Puttiphong Boonsiri",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending",
      "employee_id": "04619",
      "employee_name": "Tawat Kiatnirun",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Pending ",
      "employee_id": "04619",
      "employee_name": "Tawat Kiatnirun",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    },
    {
      "core_value_status": "Submitted",
      "employee_id": "04619",
      "employee_name": "Tawat Kiatnirun",
      "evaluate_from_supervisor_status": "Pending",
      "kpi_evaluate_status": "Pending"
    }
  ]
}`

**Comment by sainamphung** [comment]
response ซ้ำ หลังมีการประเมิน core value เพิ่ม

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/826db223-64d3-4eab-917a-4189f46942ac)
