### ISSUE TITLE
[UI] Self Evaluate ทำหน้า หัวหน้าให้คะแนนลูกน้อง

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#221]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/950cf882-f33d-4a0d-b7b8-5bb7c65e9edf)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/c38e1f09-ebd4-4ca1-8b6e-98e402c467e1)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6e95b221-7974-4658-aab9-df5660d974ea)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/65f3a895-7d83-4f32-9a5e-8915f61067c1)
