### ISSUE TITLE
Create kpi_evaluate every employee in all company

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#225]

**Comment by warakornlj** [comment]
หลังจาก Admin สร้าง Duration Setting แล้ว ระบบจะต้องดึงพนักงานทุกคนยกเว้นพี่เล้งกับพี่เอ้(ระดับ A) มาทำการสร้างข้อมูลตาม Duration_setting_id ไว้ใน้ตาราง kpi_evaluate

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/f5d588e6-578d-4ab3-a103-6e4286f8cf3f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4cd19db3-81cf-41c2-bbd6-8edff52d7bef)

**Comment by nawapornmanyanon** [comment]
พนักงานมีทั้งหมด 982 คน ตัด A ออก 2 คน
