### ISSUE TITLE
[UI] - Change layout self evaluate

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#226]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/dd542c6f-0e8b-4946-ac91-62088ab32b25)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b41e1bdd-31c8-441f-bb9d-ee2952482c4f)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/72f26926-137d-47af-8dc0-f25cc791657c)
