### ISSUE TITLE
[UI] - Add "auto eva from" in Department KPI

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#229]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/ddf5df85-b82f-49d3-8486-3875e02ec1f4)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0432d6d0-156c-4100-b040-6bfc4b98587e)
