### ISSUE TITLE
[Function] Department KPIs setting add column Auto Evaluate

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#230]

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/00cedf77-c0c3-41c3-9623-2af1e01a59db)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/1eae0bec-24bc-4906-afd5-31fa8eae8c56)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bdf4b1c6-064f-4436-83c4-caab4717df50)
