### ISSUE TITLE
[System setting][Duration] - กรณีกด Edit จาก Detail  Modal Startdate จะ Out of range

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#231]
![Image](https://user-images.githubusercontent.com/126447414/246064785-bf6d93ef-1696-4675-961d-d933f3ff5e0a.png)

![Image](https://user-images.githubusercontent.com/126447414/246064950-609c83d6-8b8f-411f-b28c-b31964b5104c.png)

-----

ถ้ากรณีกด Edit จาก icon ในตารางหน้า Duration ไม่เป็น

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/57fe4ced-e0ed-4c67-ad8d-19303c6e3079)

**Comment by nawapornmanyanon** [comment]
ยัง Error อยู่


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/de392609-0f45-497f-8210-ec827aca0afd)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/9e1a780b-3f9d-4f9c-8888-6849de02999f)

ปรับส่วนของ Min Date

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3b725bee-3b4d-4d19-be16-64cdb2fa3944)

**Comment by nawapornmanyanon** [comment]
Pass
