### ISSUE TITLE
[Evaluate] - แก้คำว่า "Employee" หน้า evaluationemployeepage

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#234]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c1fbfd30-cb99-4b2c-bd1b-86ede68d75cf)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e038a498-1a26-4a7b-97dd-5bbbd0f3c80f)

**Comment by nawapornmanyanon** [comment]
แก้คำว่า "Emlyoyee"  เป็น "Employee name :"


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/456f57af-c850-4c8f-94f6-72cfd639120a)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/49e6734b-69b6-4a84-bc67-60d8ff95e914)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/11d803a3-1048-4295-b9ee-02b3070fdbcd)
