### ISSUE TITLE
[DB] - Create DB for dev

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#24]

**Comment by sainamphung** [comment]
**เปลี่ยนชื่อ table**

self_evaluate -> kpi_evaluate

kpi_setting_department -> department_kpi

kpi_setting_corporate -> corporate_kpi

**Comment by warakornlj** [comment]
- [ ] เพิ่ม Column weight_department_kpi ใน Table kpi_evaluate
- [ ] เพิ่ม Column weight_individual_kpi ใน Table kpi_evaluate
- [ ] แก้ไข employee_id เป็น character varying 20 ทุก Table ยกเว้น Table Employee
- [ ] สร้าง Table office_master สำหรับเรียกใช้ Company Department Division Section Team

**Comment by warakornlj** [comment]
เพิ่ม Column weight_department_kpi ใน Table kpi_evaluate
 เพิ่ม Column weight_individual_kpi ใน Table kpi_evaluate

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/3f7473f2-5188-45b4-8a42-798fa5a13626)

**Comment by warakornlj** [comment]
แก้ไข Employee ID
- admins
- core_value
- core_value_detail ใช้เป็น evalutor_id
- engagement
- kpi_evaluate
