### ISSUE TITLE
[PM Setting] - Execute failed

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#245]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1246a932-588c-45ce-adb5-39b88793be6e)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fb668d54-e584-463d-99ff-0c86f590ea6c)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/51c73ff4-4575-4bfd-a659-b463215f7432)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/eb0e2498-3bbd-47a8-aa61-4efd28373881)

**Comment by nawapornmanyanon** [comment]
**PASS**
