### ISSUE TITLE
[PM Setting][Goal Setting] - Execute failed

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#248]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5149d8f-c9ad-4301-ae2e-a36d43501f5a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/26cf3153-71cd-4256-b4c9-685dac10c961)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/adbd9226-f48a-4f81-bbc6-a1312fc8f8c7)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2479dab5-0d65-4e0e-81fe-a654a3f3f79f)

**Comment by nawapornmanyanon** [comment]
**PASS**
