### ISSUE TITLE
[PM Setting][Update employee KPI weight] - Execute failed

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#251]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1c76d0b1-ea0a-491f-890b-22b167d57a92)

**Comment by nawapornmanyanon** [comment]
ยัง Error อยู่

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/073f5436-8a1c-4a4d-a334-0be1da8e68bf)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ee74fcc7-e88c-4334-bdf2-4199cc40e3e3)
