### ISSUE TITLE
[PM Setting][Update employee KPI weight] - Modal Department KPI ไม่แสดง Data  และเพิ่มความยาวของกล่อง Department และ Division

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#253]
![Image](https://user-images.githubusercontent.com/126447414/247180349-83268d61-023d-48f0-9b42-bf61572c786b.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/87f7498c-2f57-4410-9bbd-e56b8c76b635)

**Comment by nawapornmanyanon** [comment]
Data ไม่มา

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/47ae316e-d3d5-4a0f-b168-e075c6d51c4f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bcaf093f-c5d6-4317-83bf-d3129b840484)

**Comment by nawapornmanyanon** [comment]
data ครบ , PASS

เอา Column Status ออกให้หน่อย 👆

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4abb1de5-2aa8-4d51-8c40-55445833a21c)
