### ISSUE TITLE
[PM Setting][Assign DepartmentKPI] - Execute failed

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#254]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a88f556c-7b2b-4e04-9f91-453d14e2866c)

**Comment by warakornlj** [comment]
ปรับ Team members ให้ใช้  get_my_team.isLoading เพิ่มใน {{selectServices.handleFilter()}}

**Comment by warakornlj** [comment]
แก้ไข หน้า PM Setting ตรง Department KPI

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0ce7e675-9604-4534-aa5d-2ab00a6afa6d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/eff92679-f555-4b80-80ad-b7ed10fff920)
