### ISSUE TITLE
[UI] - PM Setting page

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#26]
- เพิ่มปุ่ม "PM Setting" ทางซ้ายมือ

- [x] Employee มีลูกน้อง

![Image](https://user-images.githubusercontent.com/131150937/239430124-3cbdff73-d00d-491a-ac31-f46403869e4c.png)

- [x] Employee ไม่มีลูกน้อง

![Image](https://user-images.githubusercontent.com/131150937/239430214-993c13f2-8556-4c22-958a-54fa42901a3c.png)

- [x] P'เล้ง, P'เอ้

![Image](https://user-images.githubusercontent.com/131150937/239430378-b8cd09aa-4309-42f5-8317-f7e03530649a.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/30586e01-dee5-455a-8d92-4dcc801fc6c2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/55baec61-0c06-4f0a-96fd-64f24af5972b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c71dffd0-fb1d-4178-a996-0bdd5ecc8dc2)

**Comment by sainamphung** [comment]
ที่พี่อุ @nawapornmanyanon  ทำไว้ถูกแล้ว แต่เหมือนว่าตอนนี้ที่ตาราง Team members มี column Action เกินมา ต้องเอาออกค่ะ


![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/ebd4a28d-faa9-42d0-b5ab-24dbb106f434)
