### ISSUE TITLE
[Evaluation][Selt-Evaluation][DepartmentKPI] - แก้คำ และการแสดงข้อมูลไม่ถูกต้อง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#264]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e78da03a-c9ce-49b3-894f-b14e8cbd85d7)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ccc3fcc0-5dc1-4be5-a17b-e9372cb968c3)

**Comment by nawapornmanyanon** [comment]
@warakornlj  แก้เป็นคำว่า Total score

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3e1bc31d-cbaa-4c62-bd1e-35339a88514e)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/48dc70d2-bf65-4225-8aa3-340f17de37d4)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3bee9369-7448-4a1b-9608-1fa7d546ea9e)
