### ISSUE TITLE
[UI] - Supervisor approval page

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#27]
- ย้าย tab approve จาก KPI มาใส่ tab KPI
- ย้าย tab approve จาก Core value setting มาใส่ tab Core Value

![Image](https://user-images.githubusercontent.com/131150937/239431079-de7b123b-3726-4697-9de7-cab1d9cb0144.png)

**Comment by sainamphung** [comment]
SupervisorApproval

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/35ec4b20-db21-4eaa-a009-6c5412218283)

รอบ Mid years ยังไม่ต้องให้ เพื่อนประเมิน 360 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/41734e1c-e2b4-4572-9636-c3389bd0ecad)
