### ISSUE TITLE
[API] - getAutoEvaluate

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#282]
**Description**: Get score and value from bu_performance_result  to kpi_evaluate_detail in department_kpi

**Table**:
- kpi_evaluate_detail
- bu_performance_result
- score_detail

**Path**:
- employee_id

**Param**:
- year_to_department_kpi_id

**Response**:
```
{
 "performance_type": "",
 "score_no": 1-5,
 "score": 100,
 "result": value
}
```

**Note**: costcenter นับจาก division_id

**Comment by sainamphung** [comment]
Filter ภาพรวมแล้ว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/63244659-dbfa-46b2-9c4a-661367552e5a)

**Comment by nawapornmanyanon** [comment]
ฝากเชคหน่อย

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c78c22ea-50ce-4696-a552-2a59ec331c45)

**Comment by sainamphung** [comment]
แก้ไขภาพรวมเพิ่มเติม

**Comment by nawapornmanyanon** [comment]
มีแก้ไขเพิ่ม #379
