### ISSUE TITLE
[KPI Setting][Upload Department] - ไม่ได้ clear ข้อมูล Feild Department , Division , ปุ่ม Upload

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#283]
เมื่อ Upload ข้อมูลสำเร็จ  clear ข้อมูล Feild Department , Division , ปุ่ม Upload เป็นค่าเริ่มต้น

![Image](https://user-images.githubusercontent.com/126447414/247577513-e5223def-0646-4f4c-96e5-f5f3ec8615de.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/13f9dcac-7cdf-4e76-a07e-034dbbe45856)

**Comment by nawapornmanyanon** [comment]
Test result : **failed** 

ไม่ได้ clear ข้อมูล Feild Department , Division , ปุ่ม Upload

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/9c16449b-2609-49c3-90ba-79c3e36cf1b4)




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/3c8d7647-1eac-4bed-920a-0f59e4386895)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/19fc5560-c539-4317-bee2-ab306475b565)
