### ISSUE TITLE
[PM Setting][Update KPI weight][Edit] ทำเส้น API Update เส้น DepartmentKPI กับ Individual KPI

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#289]

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/462dd433-4eed-409d-b3e8-1dfe1f07463a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/de143137-451a-46cf-ba6f-fa1870698ca4)
