### ISSUE TITLE
[KPI][Add perspective] - TypeError: Cannot read properties of undefined (reading 'office_code')

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#291]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ab342014-e206-47d8-916b-18ff316640ef)

**Comment by nawapornmanyanon** [comment]
https://mfeconcloud.sharepoint.com/:x:/s/M-Lab-Team/Ec7OAk2Kwl5NlrMNMz5cmxQB06LbXChvYIUNZjWc5JgKvA?e=locIFY

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/7820a5f8-dc4f-48ab-b845-5a577bdb8626)
