### ISSUE TITLE
[PM Setting][Department  KPI] - ตำแหน่งของ Employee แสดงไม่ตรงกับข้อมูลใน DB

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#292]
K. Kiitikun position: Senior People Business Partner
แต่หน้า UI แสดงเป็น Software Developer

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cebec7e2-ddb9-454d-9ad5-0fbd5a49e2d4)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/b0256c2f-3e3f-4a15-8aa3-576ecc68211a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7df98a55-5448-4eae-93cf-416f569edafb)
