### ISSUE TITLE
[PM Setting][Inidividual] - กรณีกดเปิด หน้า Individual  Data ใน ตาราง Team member ไม่ถูก Clear

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#295]
กรณีกดเปิด หน้า Individual  Data ใน ตาราง Team member ไม่ถูก Clear

ข้อมูลทีแสดงอยู่หน้าจอ เป็นข้อมูลที่ user เลือกไว้ที่หน้า Department KPI 

Expected result : เมื่อเปิดเข้ามาหน้า Individaul ทุกค่าต้องว่าง

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5e3236a4-be09-4623-bdf6-9d8fab7cec42)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/1e729865-c4b3-49fe-9bae-35d47a6947ba)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/da756fe4-71e9-4fb2-bc68-7d67e7231318)

**Comment by nawapornmanyanon** [comment]
Test result : Pass
