### ISSUE TITLE
[Summary]- Column ในตารางขาด Total score employee และ Total score by supervisor

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#296]
Column ในตารางขาด Total score employee และ Total score by supervisor

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fdcf193c-8d9d-4e8b-95a5-519b17091870)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3a42bca8-655b-4449-aca6-339921e8d9f2)

**Comment by warakornlj** [comment]
API ยังไม่มีการเรียกมากครับ @sainamphung 



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/4075a3cd-36ad-4ec1-b978-0cda725e4096)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/75081b6b-dbcb-4b6c-95a2-16b9d1a5768b)

**Comment by nawapornmanyanon** [comment]
Pass
