### ISSUE TITLE
[PM Setting][Individual] - Column เรียงสลับกัน และแก้ชื่อ cloumn

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#307]
แก้ชื่อและเรียง column ใหม่
Employee ID, Employee name, Position, Perspective, Individual KPI, Target, Measurements, Weight(%)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8cbed321-477f-4460-9040-1794519a7b6d)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/f255cbb0-ecf4-4ff0-83ed-87cb08177a36)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fffde8b4-74a5-4526-99b0-df82e101e528)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ff39b864-0027-4d64-9283-b21b31a44915)
