### ISSUE TITLE
Add modal cancel when a user click cancel action

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#31]

**Comment by sainamphung** [comment]
น่าจะต้องเชคเพิ่ม บางหน้ากด confirm แล้วยังไม่กลับไปหน้าที่ถูกต้อง

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bcb246fc-3f3f-4b10-b122-a0e15ff8adbf)
