### ISSUE TITLE
[PM setting][Performance Managemant Setting] -  ในตาราง team member ช่อง Department KPI status และ Indvidual KPI  ถ้าเกิดพี่นาถ Assign แล้วมันจะต้องเปลี่ยนเป็น Submitted

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#316]
ในตาราง team member ช่อง Department KPI status และ Indvidual KPI  ถ้าเกิดพี่นาถ Assign แล้วมันจะต้องเปลี่ยนเป็น Submitted

Expect result : เมื่อหวหน้างงาน Assign Department KPI และ Individual KPI เรียบร้อย status ต้องเปลี่นย submitted
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bd598a43-4d16-43c7-8e11-2b221da83fb0)

**Comment by TanawatMfec** [comment]
เกิดจากข้างหลัง API ส่งค่า null มา

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/0ffb7954-fe56-4227-a683-8a75854f3723)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/36d9cedd-d57c-40e0-827c-8f28af49aa3a)
