### ISSUE TITLE
Add approve modal when a user complete a task (Appsmith modal) (the same modal in the login page)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#32]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/89160525-aa54-45f0-b16c-8e1ff8805f75)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1edf7366-e636-4c7d-bd53-0b519ac6e0c0)




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/56056bfe-4518-4821-84b8-83b4c04ca410)
