### ISSUE TITLE
[PM setting][Assign Departments KPI] - Upload department KPI ไม่ต้องดักว่า ไม่ตรงกับ Department KPI ของ Supervisor

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#331]
ตอน  Upload department KPI ไม่ต้องดักว่า ไม่ตรงกับ Department KPI ของ Supervisor

จะมีกรณีที่เป็นพี่อาร์ม  เป็นหัวหน้าพี่นาถ แต่แกอยู่ Division : Strategy Office and Business Development   แต่แกต้อง assign Departments  KPI ให้พี่นาถ ซึ่งอยู่ M-LAB เพราะพี่นาถใช้ Department KPI ของ M-LAb

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dec7eebd-b537-442c-9d8a-b8b0e018cad8)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b5928694-96d4-4e7a-9cc7-6356d0f1e3dc)

**Comment by TanawatMfec** [comment]
@warakornlj

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9054c19c-cb18-431b-aa2b-975055a4ae08)
