### ISSUE TITLE
[Evalutetion][Engagement] - ข้อ 24 ไม่ต้อง Required และตัวคำถามไม่ต้องทำตัวใหญ๋

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#332]
- [x] ข้อ 24 ไม่ต้อง Required

- [x] ตัวคำถามไม่ต้องทำตัวใหญ๋

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/45d74e69-9f31-4acc-a002-78ab95e2a249)

**Comment by warakornlj** [comment]
ข้อ 24 ไม่ต้อง Required Deploy ขึ้นรอบ 09.06


 ตัวคำถามไม่ต้องทำตัวใหญ๋ รอขึ้นรอบหน้าครับ

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1015358-fc41-43a6-9e49-43e995755bc8)

**Comment by nawapornmanyanon** [comment]
Pass
