### ISSUE TITLE
[API] - มีแก้ไข KPI เรื่องการรับภาพรวมใหม่ ของทีม  HI04020 Managed Services

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#379]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f756ca06-fe72-4a81-8869-8acd3fef9d55)

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/55d8a7dc-b810-4fd8-be62-9234a9cd947f)

**Comment by sainamphung** [comment]
พี่หญิงแจ้งผิดจาก HI04020 เป็น HI04040 ต้องรับภาพรวมตาม BU พี่ฮวง

**Comment by sainamphung** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/4142ee92-9cac-4363-94fa-76814983995e)

**Comment by nawapornmanyanon** [comment]
OK.
