### ISSUE TITLE
[KPI Setting][Perspective] - Upload file  โดยมี perspective เป็น 0 % แจ้ง Error

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#384]
ถ้ามี perspective ตัวไหนเป็น 0  ถึงแม้ว่าจะรวมได้ 100%  จะแจ้ง Error

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d886d99c-e1f7-45e0-8d64-39abf3931cc4)

**Comment by TanawatMfec** [comment]
1. Bug แถวไหนเป็น 0 มันจะมองว่าเ้ป็น duplicate => จริงๆ ต้องถูกอัพโหลดแล้วไม่โชว duplicate 
2. แถวไไหนมีค่าว่าง ต้องโชว modal error บังคับให้  user ไปแก้file มาก่อน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4680a888-f748-4309-a3d9-aab9c4356b5c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cac10ff5-9401-4bf5-8b71-ba10b0478ab7)
