### ISSUE TITLE
[UI] - Separate score measurement to 5 columns

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#40]
![Image](https://user-images.githubusercontent.com/131150937/241099373-961a5aea-3cb5-4688-a697-b49f9cc508f3.png)

![Image](https://user-images.githubusercontent.com/131150937/241099545-e41344f5-fb12-4c60-a21e-063dd3449395.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/590de271-83c7-4b7f-ad30-1fd168aada93)
