### ISSUE TITLE
[API][Summary]Edit score to 100%

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#413]
(1) column KPI  มาหาร 1.2 และคูณ %ของ Level 

(2) column Core คูณ %ของ Level 

(3) Total = (1) + (2) 

 

จะได้  Total ไม่เกิน 100 %

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/452e0640-88c9-4855-bf3d-6c1b355a0a87)
