### ISSUE TITLE
[Landing Get Token After Login Process] Change the button name from "Cancel" to "Back to Login Page" for both No Duration and No employee data modal

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#423]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/57f51934-103f-4e8c-9862-d457291e32a3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a568392c-5fa0-4a46-ad89-a78fcaa18a48)
