### ISSUE TITLE
[Summary Details modal] Validate token when called API

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#428]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1d5fa72e-28ad-4395-ba1c-9518cc5ecb75)

ปล่อทิ้งไว้ 1 ชม.  ไม่เจอ Error นีแล้ว ตอนเลือก Department ใหม่
