### ISSUE TITLE
[validate token] เวลา user เจอ เคส vpn หลุด ระบบจะขึ้น ข้อความ authentication expire  อันนี้ต้องปรับข้อความให้มันสื่อขึ้นไหม เพราะบางเคสเกิดจาก VPN บางเคสอาจเกิดจาก token หมดอายุจริงๆ  (แยกเป็นสองเคส ไม่น่าได้ เพราะ appsmith ไม่ support )

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#445]
https://github.com/S4-Internal-app/Evaluated/issues/437 จาก Phase 1

**Comment by TanawatMfec** [comment]
อันนี้สามารถปรับโดยให้หลังบ้านส่ง 401 error exception หรือ true false แทน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/36aa9997-a0b4-4691-8a29-5f4b216ef043)
