### ISSUE TITLE
[Enhancement][init] ตอนเรียก หน้า init => ต้องใช้ try catch ทุุกครั้ง => ถ้ามี error API, VPN หลุด ให้ ปิด Modal loading แล้ว แสดง Modal error แทน (ทุกหน้า)

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#446]
https://github.com/S4-Internal-app/Evaluated/issues/440 ย้ายมาจาก Phase 1

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/3efc8f54-d664-4599-9762-9a1a0c63a3d0)

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/0a8d34c4-286a-46bb-80c2-2fa63f355807)

เคส เมื่อ เรียก API หรือ Database ไม่สำเร็จ จะโชว error modal and console log สำหรับ admin เพื่อ inspect ว่าเกิดจากอะไร

**Comment by TanawatMfec** [comment]
SupEvaluationPage ฝากพี่โจ้ดูตรง try catch ให้หน่อย

**Comment by nawapornmanyanon** [comment]
Admin
---


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5e929b3f-96a2-4e02-9d43-101afe076a58)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6916e564-9f07-4e50-80b9-dd3849e202ed)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ce28161d-ab65-4429-b860-e6d0785b2ec6)

**Comment by nawapornmanyanon** [comment]
- [ ] Evaluation  : Self-Evaluate
- [ ] Evaluation  : Selt Corevalue
- [ ] Evaluation  : Selt

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/66b03a9c-c67c-4e66-bf58-5a5763f7818d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/008f49c2-ca5b-47ad-89ea-46e129988ae4)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2e8762d0-c832-4ce2-ab2b-7d3ddd5b95cf)
