### ISSUE TITLE
[UI] Modal Info department KPI ต้องใส่ Target กับ Score measurement 

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#45]
![Image](https://user-images.githubusercontent.com/126447414/241233872-cc81963d-8e08-418c-8896-d4e4caf0c25a.png)

![Image](https://user-images.githubusercontent.com/126447414/241233772-9442e936-8b50-4167-ab5e-633628a9a492.png)

**Comment by sainamphung** [comment]
ใส่ด้วยค่ะ
