### ISSUE TITLE
[Administrator] - Division Progress monitor กรณี Msyne แสดงชื่อ department ผิด

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#451]
กรณี Msyne 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b2f0c479-6a3a-4d17-9614-1004d5ad9f45)

**Comment by wichita-ser** [comment]
หน้าบ้านส่ง msyne company มาให้แล้ว

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/2885e1c0-3936-45d1-928b-ff6237c933c4)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/82e1f382-7180-47a8-ab99-7bf5f340bc71)

@wichita-ser   มาถูกแระ  แต่สลับกัน

Department   : "Consultant Solution Services"

division : "Service Delivery"
