### ISSUE TITLE
[Phase 2][Evaluation][Individual] ระบบ ต้อง Save ข้อมูลเสมอ ทั้งตอนกดปุ่ม Next สำหรับ Evaluation ที่มีหลายหน้า หรือ ตอนกด ปุ่ม Submit  เพื่อกันเคส reload หน้า, Server or API พัง หรือ VPN หลุด

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#452]
จาก Phase 1 : https://github.com/S4-Internal-app/Evaluated/issues/438
Case VPN หลุด OR API error:  Save data after clicking the submit button => save data to store => API error => show error modal
Case ไม่ติดปัญหาอะไร:  After clicking the submit button => Send data to Back-end => Clear Store
Case กดปุ่ม Next: Click Next button => Save data from that page in the store

-------------------------------
Check แล้ว ระบบมีการเก็บ data score ที่ user เคยทำไว้ใน store (ต้องเปลี่ยนเป็น API ตอน submit)(Code ดูใช้ยาก เพราะเรียก database หลายต่อ)

![Image](https://user-images.githubusercontent.com/126447414/264519836-0b654280-0664-41dd-ab5a-af0a388b81db.png)
-------------------------
user ไม่ต้องทำใหม่ แม้ว่าเค้าจะกด refresh หน้าจอ หรือ ไปหน้าอื่นก็ตาม (tab หรือ โดน redirect ไปหน้าอื่นที่ ไม่ใช่ Log in) มีเคสเดียวเท่านั้น ที่จะ reset สิ่งที่ user ทำไว้แล้วคือ ปุ่ม submit (success) กับ เด้งไปหน้า Login

--------------------------
user เด้งไปหน้า login หลัง VPN หลุด แล้วทำให้สิ่งที่ทำอยู่หาย เพราะ เส้น validate token มันเคลีย JWT (ต้องเอาอันนี้ออก) กับ ต้อง make sure ว่า มันไม่ redirect ไปหน้า login หลัง vpn หลุด

-----------------------------
ปุ่ม next จะเซฟหน้านั้นๆไว้ สำหรับหน้าอื่นๆ ให้เรา save data ไว้ตอน submit แทน ลง store เพือ backup ในเคส ที่มัน Fail หลังกด submit ค่อยแสดง Modal error "Connect VPN แทน" (483)

Case VPN หลุด OR API error: Save data after clicking the submit button => save data to store => API error => show error modal
Case ไม่ติดปัญหาอะไร : After clicking the submit button => Send data to Back-end => Clear Store

**Comment by TanawatMfec** [comment]
ถ้า user กดปุ่ม submit แล้ว API หลุด หรือมีปัญหาจาก API ระบบ จะทำการเซฟ Data ที่ User กรอกไว้ แม้ว่า user จะไปหน้าอื่น แล้วกลับมาก็ตาม Data นั้นก็จะยังคงอยู่  Data ชุดนั้นจะหายไปก็ต่อเมื่อ user submit ผ่านแล้ว

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/ce56d622-eae7-429e-a72e-c959c39659d2)

**Comment by nawapornmanyanon** [comment]
### Self - Evaluation 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e0c281e0-4425-42d3-b0c6-6918796192ce)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/355852d8-fe4c-4092-8434-d435cfe28e8c)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4959bd22-f06b-47ca-83e0-e0974f3fa802)

**Comment by nawapornmanyanon** [comment]
### Evaluate team member by Supervisor 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e224231f-b7ce-4dde-b72d-f618b8daa1e3)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8b33360b-0396-407e-9802-37cef85be31c)

### Re Evalued


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6bb69978-6ab9-4f8c-8f25-199b25d379b6)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/356cbf48-68ea-4ef7-8d9d-3054c0d399b6)
