### ISSUE TITLE
[Error Modal] - แก้ข้อความให้ User เข้าใจมากขึ้น

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#455]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cb8d7b81-7f1a-4b9d-aa7a-b76edcc6ca08)

**Comment by TanawatMfec** [comment]
กรณี ที่ไม่เจอ  มันจะมี

email ใน DB สะกดผิด เช่น spacebar
employee ยังไม่ผ่านโปร
employee ไม่ใช้ type ที่ต้องทำประเมิน เช่น เป็น contract , เป็น outsource

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/79f9c68b-5cd5-45b0-bbb2-a94e84012f8e)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec  
เขียนเป็นประมาณ ว่า
ให้เขา check ตัวเองก่อน 

- employee ยังไม่ผ่านโปร
- employee ไม่ใช้ type ที่ต้องทำประเมิน เช่น เป็น contract , เป็น outsource 

ถ้าไม่ใช่  ให้ติดต่อ Admin

เป็น EN อ่ะ

**Comment by TanawatMfec** [comment]
To access the system, please ensure that your employee's status does not match the conditions below.

1. You are still in the probation period.
2. If you are contract or outsourcing, you do not need to complete the evaluation

If your employee's status does not match the conditions above and you still can not access the system, please contact the admin

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8945a007-c715-48b7-9aed-3389ac77fb06)
