### ISSUE TITLE
[PM setting] - ตอนอัพโหลดไฟล์ KPI ไฟล์อัพโหลดผ่าน save ได้ปกติ แต่ข้อมูลรายละเอียดขึ้นในระบบไม่ครบ เช่น KPI rowขึ้นไม่ครบแถวเหมือนในไฟล์ CSV ถ้าไม่สังเกตอีกรอบ และแก้ไขใหม่ อาจจะทำให้เกิดข้อผิดพลาดในการประเมิน  (KPI เข้าไม่ครบ)

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#456]
**Department KPI**

- ชื่อไม่ตรงกับระบบ
- Trim หน้าหลัง
- สะกด Perspective ผิด

**Individual KPI**
- Perspective name สะกดผิด
- Trim หน้าหลัง

**Comment by nawapornmanyanon** [comment]
Upload


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bb470d22-d609-4f0e-b8f5-dfe60e2f35f4)

-------------------

กด Save


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3c68ed54-ff08-4453-b1d1-350559ee5c78)


-------------------------
มันจะเข้ามาแค่ Record เดียว 

- Record ที่ชื่อ Department KPI ผิด ไม่ตรงกับในระบบ

- ชื่อ เกิน DB กำหนด ( เกิน 200 ตัว )

- Perspective  สะกดผิด ไม่ถูก Save 

จะไม่ถูก save เข้าระบบ

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/0784d6e1-ef74-42ad-997e-96d3b439b98a)

เด้ง Modal error ตอนอัพโหลดfile

**Comment by TanawatMfec** [comment]
ชื่อ เกิน DB กำหนด ( เกิน 200 ตัว ) - ดักเป็นเคสเดียวกันแบบไม่มี department นี้ในระบบ (ไม่มี department ในระบบที่เกิน 200 char อยู่แล้ว)

**Comment by nawapornmanyanon** [comment]
- ชื่อ เกิน DB กำหนด ( เกิน 200 ตัว ) 
- Record ที่ชื่อ Department KPI ผิด ไม่ตรงกับในระบบ

- Perspective สะกดผิด ไม่ถูก Save  >> ใน File ไม่มี Perspective

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/82639eb9-62e0-4c91-b5f8-b0a285534269)
