### ISSUE TITLE
[Validate Token] Handle Error Exception from Back-end

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#460]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0de034ad-a49f-4cb7-90ed-541e78d9a358)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b4b308f3-c628-4971-8f8d-befce95db7bb)
