### ISSUE TITLE
[UI][PMsetting] - เพิ่มรายละเอียด ตาราง Teammember

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#466]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7447ee81-98d1-4111-8eee-49068c67e25b)

**Comment by nawapornmanyanon** [comment]
**Team Members** 

- เพิ่ม Position และ Level

- Status กรณีเป็น Submitted ให้เปลี่ยนเป็นตัวอักษรสีเขียว 

- กรณี Level E ที่ไม่มี Individual KPI ให้ field นั้น ใส่เป็น ( - )


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e0806ee1-14fb-4cf3-9917-63729937029a)



- เปิด Search  ของ appsmith

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/eac64abd-01a9-4abc-bc59-ce9db9c937a0)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1c10b12b-7964-4e77-ac5c-ad990ce568a6)

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/664 รอการ์ดนี้ @nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
ขาด Column : employee_level   @TanawatMfec

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7968d132-8e24-491c-9735-e3a9d748c63d)

@TanawatMfec  กรณี Status เปลี่ยนเป็น Submitted แล้ว .... ต้องเปลี้ยนสีตัวอักษรเป็นสีเขียวด้วย
