### ISSUE TITLE
[Core value Evaluation][UI] Add text on the modal confirmation

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#472]
https://appsmith-canary.mfec.dev/app/au-mpulse/au-360evaluteform-2-64fe74cccbc33c5d051a8174/edit

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/a6398f26-601c-4d69-aa94-ed76c7a9fd5a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/51145828-c9d0-456b-9113-8e9401a29a45)
