### ISSUE TITLE
[UI][Teammember_Individual KPI] - แก้เป็นหน้าใหม่

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#476]
จะเหมือนของ Self-Individual แค่เพิ่มกล่อง Team member , Employee Evaluate , Employee comment

https://appsmith-canary.mfec.dev/app/au-mpulse/aucf-supindividualevapage-2-64fe74cccbc33c5d051a8178

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d1110734-349b-4ea1-934f-c1c283969813)

**Comment by nawapornmanyanon** [comment]
https://mfeconcloud.sharepoint.com/sites/PMSapp/_layouts/OneNote.aspx?id=%2Fsites%2FPMSapp%2FSiteAssets%2FPMS%20app%20Notebook&wd=target%28UI%20Improved%202.one%7C6906FE75-8964-4EB1-800F-1193E6AA2C38%2FSupervisor%20Evaluation_CF%7C9C918BF6-15DF-4071-AE95-C7956940F7B0%2F%29
onenote:https://mfeconcloud.sharepoint.com/sites/PMSapp/SiteAssets/PMS%20app%20Notebook/UI%20Improved%202.one#Supervisor%20Evaluation_CF&section-id={6906FE75-8964-4EB1-800F-1193E6AA2C38}&page-id={9C918BF6-15DF-4071-AE95-C7956940F7B0}&end

**Comment by warakornlj** [comment]
Commit เดียวกับการ์ด 475

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/643d6f01-b384-43d0-8d38-1c342c4832e4)

มันไม่แสดง Box Individual KPI report

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon : รอ Data test

**Comment by nawapornmanyanon** [comment]
@warakornlj  ปิดกรอบ Team meber


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b6f2dd73-4ac5-4d19-b350-028f0a67c07f)

**Comment by nawapornmanyanon** [comment]
@warakornlj Individual KPI detail DATA not found


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6f8f694d-76a1-4d51-ab44-42a6ba1e809f)

**Comment by nawapornmanyanon** [comment]
@warakornlj ปรับ Area ให้พดีหน้า


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/de7c64d0-7254-4258-b46a-a656291cfc3d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ef9cc46f-84ce-4327-b5f3-8e076bf359d9)
