### ISSUE TITLE
[PMsetting][DepartmentKPI] -  Uploadจาก file lสำเร็จ แต่ข้อมูลไม่ถูก save หลังกดปุ่ม Save

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#480]
File ที่ใช้

[Department_KPI_by_Supervisor_V1_MLAB_DEV.csv](https://github.com/S4-Internal-app/Evaluated/files/12667837/Department_KPI_by_Supervisor_V1_MLAB_DEV.csv)

--------------------

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b4622124-43b3-4466-a727-437cb11c1c68)

**Comment by TanawatMfec** [comment]
KPIEmployeeIndividual component

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2d50cd6d-768c-4097-bbca-84130a1912f2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/63b10d4a-c143-4de1-ae04-5a5db520bd65)
