### ISSUE TITLE
[UI][Home][SummaryReport] - เพิ่มหน้า Summary

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#486]
เพิ่มหน้า Summary report  สำหรับ Sup ดู summary team member , Admin ดู summary employee 
---------------

https://appsmith-canary.mfec.dev/app/au-mpulse/au-summaryreport-65091c59cbc33c5d051ae698?embed=true

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f406f570-4c06-484f-8036-13914ae0ff7f)

**Comment by nawapornmanyanon** [comment]
ขาด Column


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7f0487df-6284-451b-a770-59287df85e4a)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  Recheck ตอนมี DATA อีกที

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
@warakornlj  กด Summary แล้วยังไม่มี Column ของ Supervisor เลยอ่ะ
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/da1f9450-9fcc-41d4-8b3e-4a68c587e60c)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/4435d851-802f-49c9-b587-8112e21b5937)

เพิ่ม Key is_supervisor ขึ้นมา หากกดมาจาก Teammember

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/00d62ec5-246a-4247-8ba6-08cdb1cb315c)

**Comment by nawapornmanyanon** [comment]
Check Score ดึงจาก API ถูกต้อง
