### ISSUE TITLE
[API][All] - Get duration list

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#498]
**Description**: Get all duration list for select button

**Table**:
- duration_setting

**Response**:
```
duration_list: [
 {
  "duration_id": 1,
  "label": "year - round"
 },{
  "duration_id": 2,
  "label": "year - round"
 }
]
```

**Note**:
- sort by duration_id -> DESC

**Comment by wichita-ser** [comment]
[GET] /api/v1/masters/evaluate/durations

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4d7de8ed-6735-4115-a04e-87bcbc890dac)

**Comment by TanawatMfec** [comment]
Connect front-end at Home page

**Comment by nawapornmanyanon** [comment]
@wichita-ser  ฝากเพิ่มชื่อยาวๆ 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0483a58d-6713-42a8-b2d8-48dca789ec0b)

2023 - Mid-Year Performance Evaluation
2023 - Annual year Performance Evaluation

**Comment by wichita-ser** [comment]
at evaluate_test DB

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/31d48a05-2a75-409f-bb18-eeae50e28f3c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ee6dbe49-0c1b-48a9-b1e3-fcf69cdf8233)
