### ISSUE TITLE
[UI][Summary] - เพิ่ม Score compare report

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#499]
เพิ่ม Score compare report
--------------
https://appsmith-canary.mfec.dev/app/au-mpulse/au-summary-64fe74cccbc33c5d051a8182?embed=true

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0cdef3f3-d6d1-4fd6-8530-1d924b3cc6eb)

**Comment by nawapornmanyanon** [comment]
[Score compare report](https://mfeconcloud.sharepoint.com/:fl:/g/contentstorage/CSP_2a64939e-b50f-410d-8b79-57008fc4b59d/EezuVzHeb8pGhZc4y_-D3BABqptQs608dgB_VXmuPf7sog?e=zIuSdK&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF8yYTY0OTM5ZS1iNTBmLTQxMGQtOGI3OS01NzAwOGZjNGI1OWQmZD1iJTIxbnBOa0tnLTFEVUdMZVZjQWo4UzFuWDVJeEdtVlUyZERqNGdKdlduYXdydFBsbC1TN0Q0QVNxal95MGtGSzIzdyZmPTAxM0NCM0dWWE01WkxURFhUUFpKRElMRlpZWlA3WUhYQVEmYz0lMkYmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4dFptVmpiMjVqYkc5MVpDNXphR0Z5WlhCdmFXNTBMbU52Ylh4aUlXNXdUbXRMWnkweFJGVkhUR1ZXWTBGcU9GTXhibGcxU1hoSGJWWlZNbVJFYWpSblNuWlhibUYzY25SUWJHd3RVemRFTkVGVGNXcGZlVEJyUmtzeU0zZDhNREV6UTBJelIxWlhORTFYTTBGQ1F6TlhTVlpHU1RkV05VVlBSVUpRU2xOQ1Z3JTNEJTNEJTIyJTJDJTIyaSUyMiUzQSUyMjlhMjRjNzM4LTNjNDAtNDZjNi05MzExLTZmY2U0NjFjNjEwMyUyMiU3RA%3D%3D)

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/57e2bb2c-4000-4f25-a44f-c5f5fea89c57)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/613eff9b-33fb-4db2-b178-1025a687ab3a)
