### ISSUE TITLE
[Function] - Monitor progress page for admin

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#50]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/11f07dc8-edf6-4f32-8a5b-ea6e39b8db0f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/48101980-f007-4ba9-b959-af5d84ac39aa)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2818900c-82e3-409c-addc-af5694be74b9)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3297096c-4fc6-4881-9122-de45e77cc3d2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5407d804-8697-4a02-82bb-272dcc7960d1)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6a7ba77a-c6c9-445e-977c-409fd8b5a983)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/703f200a-dfc5-4f5c-84aa-c78924da6380)
