### ISSUE TITLE
[Front-end[Connect API] get employee by email from Card 497

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#500]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=39607260

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/beddc397-daae-4b75-8418-27ac6f11659f)
