### ISSUE TITLE
[API][Report] - Get core value report by employee_id

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#507]
**Description**: Get report of core value score

**Table**:
- employee
- core_value
- core_value_detail
- score_detail

**Query string**:
- employee_id
- duration_id

**Response**:
```
{
 "employee":{
  "name": "firstname lastname",
  "position": "position",
  "level": "H",
  "division": ""
 },
 "core_value_list": [{
   "choice": 1,
   "comment": "",
   "weight": 10,
   "employee_score": 1,
   "supervisor_score": 2
 }]
}
```

**Comment by sainamphung** [comment]
New response
```
{
 "employee":{
  "name": "firstname lastname",
  "position": "position",
  "level": "H",
  "division": ""
 },
 "core_value_list": [{
   "choice": 1,
   "comment": "",
   "weight": 10,
   "employee_score": 1,
   "supervisor_score": 2
 }],
 "status": "Submitted"
}
```

**Comment by wichita-ser** [comment]
[GET] /api/v1/summary/report/core_value?employee=&duration_setting_id=

**Comment by wichita-ser** [comment]
New response เพิ่ม supervisor comment

{
 "employee":{
  "name": "firstname lastname",
  "position": "position",
  "level": "H",
  "division": ""
 },
 "core_value_list": [{
   "choice": 1,
   "employee_score": 1,
   "employee_comment: "",
   "supervisor_score": 2,
   "supervisor_score": 1
 }],
 "status": "Submitted"
}

**Comment by TanawatMfec** [comment]
Connected in Home page

**Comment by wichita-ser** [comment]
New API Path : [GET] /api/v1/evaluates/report/core_value

**Comment by wichita-ser** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/8b28a9a0-1dcb-4808-a101-71919933d7b1)

ถ้าไม่มี score ก็ให้ส่ง object ใน core_value_list ไปอยู่ดี แต่ว่า score/rating = 0

**Comment by wichita-ser** [comment]
Deploy done ka


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/5b59ea7e-5954-481f-9aa6-6369b76b9755)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/897679f9-8937-4c70-948c-20189af9e9a4)
