### ISSUE TITLE
[Front-end][Connect_API][Duration] - Update duration from card 495

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#512]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=39606443

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c64ec767-c0f4-4b0d-94f5-cc9185d435bc)
