### ISSUE TITLE
[Front-end][Connect_API][Duration]- Create duration from card 493

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#513]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=39605671

**Comment by nawapornmanyanon** [comment]
[Result](https://mfeconcloud.sharepoint.com/sites/PMSapp/_layouts/OneNote.aspx?id=%2Fsites%2FPMSapp%2FSiteAssets%2FPMS%20app%20Notebook&wd=target%28Test%20report%20-%20Phase%202.one%7C965F0EE5-7545-4CE9-93DB-03116471DF80%2FAdd%20round%7CA685F1EF-E3B7-4AAC-8291-6552C17830C4%2F%29
onenote:https://mfeconcloud.sharepoint.com/sites/PMSapp/SiteAssets/PMS%20app%20Notebook/Test%20report%20-%20Phase%202.one#Add%20round&section-id={965F0EE5-7545-4CE9-93DB-03116471DF80}&page-id={A685F1EF-E3B7-4AAC-8291-6552C17830C4}&end)
