### ISSUE TITLE
[Function] - Update admin with responsibility

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#52]
รวม validate ด้วย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/db6673d3-f4d4-48ae-ab4d-08fcde6ec01f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f64971ce-ea7b-4e76-b3e0-05fceca71e2c)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c2b16880-047b-4a6a-a7c7-cb797ed38bcc)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cc15919d-0ce5-404a-82f3-3b0bf81bbb55)
