### ISSUE TITLE
[Database] Add column to tables related to the feature score setting

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#520]
**Description**: Add columns to the tables related to feature score setting to specify the year of the data

**Tables**:
1. score_detail
    - year (integer)

2. nine_boxes_grid_info
    - year (integer)

3. grade
    - year (integer)
    - quota (integer)

**Comment by wichita-ser** [comment]
Migrate to `evaluate_for_dev` database done
