### ISSUE TITLE
[API][Admin] - Get grade range

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#521]
**Description**: Get grade range for score setting detail by year

**Table**:
- grade

**Params**:
- year
 

**Response**:
```
{
   "grade_range" : [{
     "grade": "A",
     "min_score": 95.1,
     "max_score": 100.0,
     "quota_percentage": 10
   },{
     "grade": "B",
     "min_score": 91.0,
     "max_score": 95.0,
     "quota_percentage": 20
   }],
   "year": 2023
}
```

Note:
- Only admin can access this API
- Order by grade asc

**Comment by wichita-ser** [comment]
[GET] /api/v1/admins/score/grade_range/{year}/detail

**Comment by wichita-ser** [comment]
ขออัพเดท response body ค่ะ
เปลี่ยน `grade: str` เป็น `grade_name: str` และเพิ่ม `grade_id`: 1

```
{
   "grade_range" : [{
     "grade_id": 1,
     "grade_name": "A",
     "min_score": 95.1,
     "max_score": 100.0,
     "quota_percentage": 10
   },{
     "grade_id": 2,
     "grade": "B",
     "min_score": 91.0,
     "max_score": 95.0,
     "quota_percentage": 20
   }],
   "year": 2023
}
```

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e89818fd-8d85-4c8d-9100-393285c23217)

`{
  "payload": {
    "grade_range": [
      {
        "grade_id": 1,
        "grade_name": "A+",
        "max_score": "100.0",
        "min_score": "95.0",
        "quota_percentage": 10
      },
      {
        "grade_id": 2,
        "grade_name": "A",
        "max_score": "95.0",
        "min_score": "91.0",
        "quota_percentage": 20
      },
      {
        "grade_id": 3,
        "grade_name": "B",
        "max_score": "90.0",
        "min_score": "80.0",
        "quota_percentage": 50
      },
      {
        "grade_id": 4,
        "grade_name": "C",
        "max_score": "79.0",
        "min_score": "75.0",
        "quota_percentage": 10
      },
      {
        "grade_id": 5,
        "grade_name": "D",
        "max_score": "74.0",
        "min_score": "0.0",
        "quota_percentage": 10
      }
    ],
    "year": "2023"
  }
}`
