### ISSUE TITLE
[API][Admin] - Update KPI score detail

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#522]
**Description**: update kpi score detail by year

**Table**:
- score_detail

**Params**:
- year

**Body**:
```
{
   "kpi_score": [{
     "number": 1,
     "description": "below",
     "score": 80
   },{
     "number": 2,
     "description": "partially meet",
     "score": 90
   }]
}
```

**Response**:
```
200
```

**Note**:
- Only admin can access this API

**Comment by wichita-ser** [comment]
[POST] /api/v1/admins/score/kpi/{year}

**Comment by wichita-ser** [comment]
ขอเปลี่ยน request body และ API Path

```
{
  "year": 2023,
  "evaluate_type": "kpi",
  "score_list": [{
     "rating": 1,
     "score": 30
   },
   {
     "rating": 2,
     "score": 50
   }]
}
```

[POST] /api/v1/admins/score/detail

**Comment by nawapornmanyanon** [comment]
Update DATA ลง DB ได้ 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a09d0e62-4c44-4d4b-94bf-200fe1c04cc2)
