### ISSUE TITLE
[API][Admin] - Update grade quota

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#527]
**Description**: update grade quota by year

**Table**:
- score_detail

**Params**:
- year

**Body**:

```
{
   "grade_detail" : [{
     "grade": "A",
     "quota_percentage": 50
   },{
     "grade": "B",
     "quota_percentage": 50
   }]
}
```

Note:
- Only admin can access this API

**Comment by wichita-ser** [comment]
[POST] /api/v1/admins/score/grade_quota/{year}

**Comment by TanawatMfec** [comment]
Connected in Create Duration

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/63358358-6af9-4461-aec9-cefab9515118)
