### ISSUE TITLE
Handle condition in Duration page Mid year == Final year so disabled ||   Final year !== new Mid year => can set score

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#528]

**Comment by TanawatMfec** [comment]
+ Handle Save data after losing the connection from VPN

**Comment by TanawatMfec** [comment]
ตอน Update ต้องปิด ไม่ให้ Admin แก้ Round กับ Year ไม่งั้นจะทำให้ระบบพังไปหมด

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/fde2ff74-5cab-4431-b6e7-d6011caa93a7)

**Comment by TanawatMfec** [comment]
ถ้า User Update duration ให้แสดงหน้า Duration แค่หน้าเดียว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fde36844-ef26-4caa-82a0-d7d06b0a9205)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/14b2b4f2-97d8-4a0a-bbd1-1f3b7b952ac2)
