### ISSUE TITLE
[API][Evaluate] - Update KPI score

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#537]
**Description**: Update KPI score (department kpi/individual kpi)

**Role**:
- All user

**Table**:
- kpi_evaluate
- kpi_evaluate_detail
- employee_grade
- grade

**Body**:
```
{
"duration_id": 1,
"is_supervisor": true,
"kpi_evaluate_id": 1,
"kpi_type": "Department/Individual",
"kpi_list": [{
 "kpi_evaluate_detail_id": 1,
 "rating": 3,
  "result": "Text"},
 {
 "kpi_evaluate_detail_id": 2,
 "rating": 3,
 "result": ""}
 ]
}
```

**Response**:
```
200
```

**Note**:
- API นี้เอา reuse ในการ update คะแนนของ KPI ลงใน DB ได้ทั้ง department_kpi และ individual_kpi
- ต้องคำนวณและ update total score ของแต่ KPI ลงใน table ที่เกี่ยวข้องด้วย
- ต้องเอา total score ที่คำนวณได้ไปเชค grade และ update ที่ table grade ด้วย
- คะแนนที่ update ใน employee_grade จะเป็นเฉพาะคะแนนจากการประเมินของ supervisor เท่านั้น

**Comment by sainamphung** [comment]
[POST] /api/v1/evaluates/kpi/update_score

**Comment by TanawatMfec** [comment]
connected on individual and department kpi Evaluate
