### ISSUE TITLE
[API][Admin] - Get employee list with status

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#539]
**Description**: Get all employee in system with KPI setting, evaluate status

**Role**:
- Admin

**Table**:
- employee
- kpi_evaluate
- core_value
- engagement

**Params**:
- duration_id

**Response**:
```
{
"employee_list": [{
 "employee_name": "firstname_en lastname_en",
 "employee_id": "",
 "supervisor": "firstname_en lastname_en",
 "company": "",
 "department": "",
 "division": "",
 "level": "",
 "department_kpi_setting": "Pending",
 "individual_kpi_setting": "Pending",
 "kpi_evaluate_status": "Pending",
 "core_value_evaluate_status": "Pending",
 "supervisor_kpi_evaluate_status": "Pending",
 "supervisor_core_value_evaluate_status": "Pending",
 "current_duration_status": "Active"
},
{
 "employee_name": "firstname_en lastname_en",
 "employee_id": "",
 "supervisor": "firstname_en lastname_en",
 "company": "",
 "department": "",
 "division": "",
 "level": "",
 "department_kpi_setting": None,
 "individual_kpi_setting": None,
 "kpi_evaluate_status": None,
 "core_value_evaluate_status": None,
 "supervisor_kpi_evaluate_status": None,
 "supervisor_core_value_evaluate_status": None,
 "current_duration_status": "Inactive"
}]
}
```

**Comment by wichita-ser** [comment]
อัพเดท response body: เพิ่ม engagement_status

{
"employee_list": [{
 "employee_name": "firstname_en lastname_en",
 "employee_id": "",
 "supervisor": "firstname_en lastname_en",
 "company": "",
 "department": "",
 "division": "",
 "level": "",
 "department_kpi_setting": "Pending",
 "individual_kpi_setting": "Pending",
 "kpi_evaluate_status": "Pending",
 "core_value_evaluate_status": "Pending",
 "supervisor_kpi_evaluate_status": "Pending",
 "supervisor_core_value_evaluate_status": "Pending",
 "engagement_status": "Pending",
 "current_duration_status": "Active"
}]

**Comment by wichita-ser** [comment]
[GET] /api/v1/admins/employees/status/duration/{ duration_id }

**Comment by TanawatMfec** [comment]
connected on Admin page in Employee tab

**Comment by nawapornmanyanon** [comment]
@wichita-ser  Order by Employee ID ให้หน่อยจิ  เส้นเดียวกับที่ เอิร์ธ ให้เพิ่ม KEY : is_supervisor อ่ะ


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b9087f60-aeda-46d1-9e6e-3f97d801d7c2)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fb1fc22a-0fd5-4524-8cf7-5427e8cf53d2)
