### ISSUE TITLE
[UI] Self Evaluate เปลี่ยนจากให้ Rating ตาม Table เป็นให้ User โฟกัสเป็นข้อๆ

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#54]

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/0c618bd6-a593-4168-ad4a-3cbdb9f3b7dc)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4103eee9-53c5-4847-a73b-bea80abe3fab)
