### ISSUE TITLE
[API][Admin] - Activate employee by employee_id

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#540]
**Description**: Create kpi_evaluate, core_value, engagement for employee that come to system after create duration

**Role**:
- Admin

**Table**:
- kpi_evaluate
- core_value
- engagement

**Body**:
```
{
"employee_id": "",
"duration_id": integer
}
```

**Response**:
```
200
```

**Note**:
- Create kpi_evaluate, core_value, engagement เหมือนตอน create duration แต่ทำให้แค่คนที่ได้ employee_id มา

**Comment by wichita-ser** [comment]
[POST] /api/v1/admins/employee/activate

**Comment by TanawatMfec** [comment]
Connected in the employee tab and table (Admin Page)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/76665461-5284-4a30-b610-5acb76d1dd9f)

**Comment by wichita-ser** [comment]
@nawapornmanyanon
Backend TODO:
- ปรับ code 201 ให้เป็น 200

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ca22348f-37bb-4dd8-b7d3-d82b18da7bb8)

**Comment by wichita-ser** [comment]
**หลังบ้าน recheck:**
กด activate แล้วสร้าง table ที่เกี่ยวข้องซ้ำซ้อน แก้ให้ดักว่าถ้ามี ไม่สร้าง
