### ISSUE TITLE
[API][Admin] - Deactivate employee by employee_id

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#541]
**Description**: Delete kpi_evaluate, core_value, engagement for employee that come to system but don't need to evaluate in this duration

**Role**:
- Admin

**Table**:
- kpi_evaluate
- core_value
- engagement

**Body**:
```
{
"employee_id": ""
}
```

**Response**:
```
200
```

**Note**:
- Delete kpi_evaluate, core_value, engagement ออก

**Comment by wichita-ser** [comment]
[POST] /api/v1/admins/employee/deactivate

**Comment by wichita-ser** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/39cbb7a7-60bb-4183-be14-1d14562040a3)

**Comment by wichita-ser** [comment]
ขออัพเดท request body

```
{
"employee_id": "",
"duration_id": integer
}
```

**Comment by TanawatMfec** [comment]
Connected in the employee tab and table (Admin Page)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/55dbd1a1-c6cb-4854-8ac9-c7463fb11504)

**Comment by wichita-ser** [comment]
@nawapornmanyanon 
Backend TODO:
- ปรับ code 201 ให้เป็น 200

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/da66cac1-9e89-47ab-8c6e-2812f1e7fe7c)

**Comment by sainamphung** [comment]
ถ้ากด deactivate แล้วจะต้องเอาลบ data จาก  table kpi_evaluate, core_value, engagement และ employee_grade
ถ้ามีการ assign detail ไปแล้ว ก็ลบ detail ออกด้วย
