### ISSUE TITLE
[API][Summary] - Fix bug to show all employee below BU head

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#543]
**AC**:  [Summary page  AC](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlLmxvb3A%2FZD13YmNmMmI1OGRjOTIxNDI4NDlkZjc4ZDAzZmQ4NmY4MTQmY3NmPTEmd2ViPTEmbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY4eVlUWTBPVE01WlMxaU5UQm1MVFF4TUdRdE9HSTNPUzAxTnpBd09HWmpOR0kxT1dRbVpEMWlJVzV3VG10TFp5MHhSRlZIVEdWV1kwRnFPRk14YmxnMVNYaEhiVlpWTW1SRWFqUm5TblpYYm1GM2NuUlFiR3d0VXpkRU5FRlRjV3BmZVRCclJrc3lNM2NtWmowd01UTkRRak5IVmxWT1YxaGFURmxKVDBwUlVrSktNelUwVGtGUU5sbE9Oa0ZWSm1NOUpUSkdKbVpzZFdsa1BURW1ZVDFNYjI5d1FYQndKbkE5SlRRd1pteDFhV1I0SlRKR2JHOXZjQzF3WVdkbExXTnZiblJoYVc1bGNpWjRQU1UzUWlVeU1uY2xNaklsTTBFbE1qSlVNRkpVVlVoNGRGcHRWbXBpTWpWcVlrYzVNVnBETlhwaFIwWjVXbGhDZG1GWE5UQk1iVTUyWWxoNGFVbFhOWGRVYlhSTVdua3dlRkpHVmtoVVIxWlhXVEJHY1U5R1RYaGliR2N4VTFob1NHSldXbFpOYlZKRllXcFNibE51V2xoaWJVWXpZMjVTVVdKSGQzUlZlbVJGVGtWR1ZHTlhjR1psVkVKeVVtdHplVTB6WkRoTlJFVjZVVEJKZWxJeFdsaE9SVEZZVFRCR1ExRjZUbGhUVmxwSFUxUmtWMDVWVmxCU1ZVcFJVMnhPUTFaM0pUTkVKVE5FSlRJeUpUSkRKVEl5YVNVeU1pVXpRU1V5TWpkaU1EZzNNR0kyTFdSa1pHUXROR1ZoWlMxaU9UQmtMV1UyWkRBNVkyWmpOV1F4WkNVeU1pVTNSQSUzRCUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiN2IwODcwYjYtZGRkZC00ZWFlLWI5MGQtZTZkMDljZmM1ZDFkIn19)

**Description**: แก้บัค summary ที่ตอนนี้แสดงแค่ลูกน้องใกล้ตัว เป็นแสดงลูกน้องของลูกน้องได้

**Comment by nawapornmanyanon** [comment]
P'ARM

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/622a1457-8033-4cae-879b-aaee507a1e9c)
