### ISSUE TITLE
[Admin][Duration] - แก้ Format date

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#544]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e7ebc3ad-f179-414b-bc00-a7fd79b46671)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9fe8200f-3548-4fa3-8388-e0a0942e3ec9)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7340e6e2-c143-4dd5-b832-6ab9a792ea9e)

**Comment by TanawatMfec** [comment]
เปลี่ยนเป็น Oct, Jul แทนทั้งหมด

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/608a8237-2589-44fb-84cf-743f3ca4fff7)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ce6528fe-b7dd-41da-a5e9-d482158b5ee1)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2de69837-6635-432c-9cfe-236dda4d7d3b)
