### ISSUE TITLE
[Home] Handle all API

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#546]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e6b5ca2c-99ed-4b82-80f4-a790fe8549c9)

ยิง API Duplicate : 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9f74979c-47da-45fb-bbe2-b555b7185b38)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0e80b94e-fe02-40e5-9a19-40e1a0177cd9)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/95fc1a31-85fd-4046-a0ad-3c9e24968042)
