### ISSUE TITLE
[API][Summary] - Get summary grade by filter

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#549]
**AC**: [Grade report](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlJTIwMy5sb29wP2Q9dzNiMmFjZDljN2ViZjQxNTk5ZmZlODE5MWJjMzMwMWM4JmNzZj0xJndlYj0xJm5hdj1jejBsTWtaamIyNTBaVzUwYzNSdmNtRm5aU1V5UmtOVFVGOHlZVFkwT1RNNVpTMWlOVEJtTFRReE1HUXRPR0kzT1MwMU56QXdPR1pqTkdJMU9XUW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsVTBXbFZXUkZoUU16Wk1Sa0ZhTnpkVlFsTkhOa1JIUVU5SkptTTlKVEpHSm1ac2RXbGtQVEVtWVQxTWIyOXdRWEJ3Sm5BOUpUUXdabXgxYVdSNEpUSkdiRzl2Y0Mxd1lXZGxMV052Ym5SaGFXNWxjaVo0UFNVM1FpVXlNbmNsTWpJbE0wRWxNakpVTUZKVVZVaDRkRnB0Vm1waU1qVnFZa2M1TVZwRE5YcGhSMFo1V2xoQ2RtRlhOVEJNYlU1MllsaDRhVWxYTlhkVWJYUk1Xbmt3ZUZKR1ZraFVSMVpYV1RCR2NVOUdUWGhpYkdjeFUxaG9TR0pXV2xaTmJWSkZZV3BTYmxOdVdsaGliVVl6WTI1U1VXSkhkM1JWZW1SRlRrVkdWR05YY0dabFZFSnlVbXR6ZVUwelpEaE5SRVY2VVRCSmVsSXhXbGhPUlRGWVRUQkdRMUY2VGxoVFZscEhVMVJrVjA1VlZsQlNWVXBSVTJ4T1ExWjNKVE5FSlRORUpUSXlKVEpESlRJeWFTVXlNaVV6UVNVeU1qaGtZVGM1TlRZekxXRTVOR1V0TkdJM1lpMWhaalJoTFdOak1ETmtZVFJpTXprek5TVXlNaVUzUkElM0QlM0QiLCJyIjpmYWxzZX0sImkiOnsiaSI6IjhkYTc5NTYzLWE5NGUtNGI3Yi1hZjRhLWNjMDNkYTRiMzkzNSJ9fQ%3D%3D)

**Description**: Show list of grade report

**Table**:
- employee_grade
- grade

**Query String**:
- company (id)
- department (id)
- division (id)
- grade_id
- level

**Response**:
```
{
"employee_grade": [
 "employee_name": "firstname_en lastname_en",
 "employee_id": "",
 "level": "",
 "department": "",
 "division": "",
 "position": "",
 "total_score_percentage": 70,
 "grade": "A",
 "adjusted_grade": "",
 "adjusted_remark": ""
]
}
```

**Note**:
- Validate current user by access token
- total_score_percentage เอาจาก table `EmployeeGrade` column: total_score

**Comment by wichita-ser** [comment]
[GET] /api/v1/report/grade?company=&department_id=&division_id=

**Comment by wichita-ser** [comment]
เพิ่ม `company` ใน response key
New response body:
```
{
  "employee_grade": [
   "employee_name": "firstname_en lastname_en",
   "employee_id": "",
   "level": "",
   "department": "",
   "division": "",
   "position": "",
   "company": "",
   "total_score_percentage": 70,
   "grade": "A",
   "adjusted_grade": "",
   "adjusted_remark": ""
  ]
}
```

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  รอ DATA Recheck อีกที

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/eb01b2c8-9e69-442e-aad1-c28ad9788595)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/edd068af-832a-4a66-98ae-d9f95bba27e6)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/02d00b10-34f8-4f24-a2f9-8d987dd06d5f)
