### ISSUE TITLE
[API][Summary] - Get department KPI score report

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#552]
**AC**: [Department KPI score report](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlLmxvb3A%2FZD13MTczMjU2YzE3Nzk1NGMwMzlkYTc1ZmYxZjVkMmZkNDAmY3NmPTEmd2ViPTEmbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY4eVlUWTBPVE01WlMxaU5UQm1MVFF4TUdRdE9HSTNPUzAxTnpBd09HWmpOR0kxT1dRbVpEMWlJVzV3VG10TFp5MHhSRlZIVEdWV1kwRnFPRk14YmxnMVNYaEhiVlpWTW1SRWFqUm5TblpYYm1GM2NuUlFiR3d0VXpkRU5FRlRjV3BmZVRCclJrc3lNM2NtWmowd01UTkRRak5IVmxkQ1MxbGFRbEJHVEZoQlRrZEtNMG95TnpaSU1qVkdOMHRCSm1NOUpUSkdKbVpzZFdsa1BURW1ZVDFNYjI5d1FYQndKbkE5SlRRd1pteDFhV1I0SlRKR2JHOXZjQzF3WVdkbExXTnZiblJoYVc1bGNpWjRQU1UzUWlVeU1uY2xNaklsTTBFbE1qSlVNRkpVVlVoNGRGcHRWbXBpTWpWcVlrYzVNVnBETlhwaFIwWjVXbGhDZG1GWE5UQk1iVTUyWWxoNGFVbFhOWGRVYlhSTVdua3dlRkpHVmtoVVIxWlhXVEJHY1U5R1RYaGliR2N4VTFob1NHSldXbFpOYlZKRllXcFNibE51V2xoaWJVWXpZMjVTVVdKSGQzUlZlbVJGVGtWR1ZHTlhjR1psVkVKeVVtdHplVTB6WkRoTlJFVjZVVEJKZWxJeFdsaE9SVEZZVFRCR1ExRjZUbGhUVmxwSFUxUmtWMDVWVmxCU1ZVcFJVMnhPUTFaM0pUTkVKVE5FSlRJeUpUSkRKVEl5YVNVeU1pVXpRU1V5TWpsak9EUmlaRGMyTFdVeE5UWXROR0ZqTWkxaU5XWmhMVGcwWWpNeU1URmtPVGMyWVNVeU1pVTNSQSUzRCUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiOWM4NGJkNzYtZTE1Ni00YWMyLWI1ZmEtODRiMzIxMWQ5NzZhIn19)

**Description**: Get department KPI score of all department

**Role**:
- Admin

**Table**:
- year_to_department_kpi
- department_kpi
- corporate_kpi
- perspective
- department_kpi_score

**Params**:
- duration_id

**Query String**:
- company_id
- department_id
- division_id

**Response**:
```
{
  payload: [{
    "company": "",
    "department": "",
    "division": "",
    "department_kpi_list": [{
       "perspective_name": "",
       "corporate_kpi_name": "",
       "department_kpi_name": "",
       "target": "",
       "weight": 50,
       "rating": 3,
       "score_with_weight": 50
     }],
    "total": 110.2,
    "total_percentage": 98.5
  }]
}
```

**Note**:
- validate current user by access token
- `score_with_weight` เป็นคะแนนที่เอาไปคูณกับ weight แล้ว
- `total` เป็นคะแนนเต็ม 120
- `total_percentage` เป็นคะแนนเต็ม 100

**Comment by wichita-ser** [comment]
[GET] /api/v1/admins/report/scores/department_kpi/duration/7?company_id=&department_id=&division_id=

**Comment by nawapornmanyanon** [comment]
**Employee Role : Nawaporn_m** 
-----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/685e1704-2f4d-4389-83fa-61fc4b06903d)

**Comment by nawapornmanyanon** [comment]
**Supervisor role : Natnaka**
----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2305987e-1246-4cd9-9528-69a6d717216e)

**Comment by nawapornmanyanon** [comment]
**Admin role : Natthida**
----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0198c1ff-cf8b-4590-9228-44dccf26e03a)

**Comment by wichita-ser** [comment]
ถ้าไม่มีข้อมูลที่ get มาได้ ควรจะได้ข้อมูลของ department, division มาของทุก division 
ตัวอย่าง response body:
```
{
  "payload": [
    {
      "company": "MFEC",
      "department": "Business Innovation",
      "department_kpi_list": [],
      "division": "M-Lab",
      "total": 0,
      "total_percentage": 0
    }
  ]
}
```

**Comment by nawapornmanyanon** [comment]
@wichita-ser  ถามๆ @ 10.00

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/37a3e1b9-e67a-4c95-9cbf-52e2353125e7)

**Comment by wichita-ser** [comment]
**หลังบ้าน recheck:**
filter duration_id = 4 แต่ของ duration_id = 3 มาด้วย (year_to_department_kpi_id = 169)

**Comment by wichita-ser** [comment]
แนะนำให้ test ด้วย department_id = 'IN00000', division_id = 'IN04000' 
ทั้ง 2 duration (3,4) จะมีทั้งหมด 4 rows

**Comment by nawapornmanyanon** [comment]
{
  "payload": [
    {
      "Profitability": [
        {
          "corporate_kpi_name": "KPI 1 - Net profit (NP)",
          "department_kpi_name": "KPI 1 - Net profit (NP)",
          "rating": 0,
          "score": 0,
          "target": "225 MB",
          "weight": "0.7",
          "year_to_department_kpi_id": 375
        }
      ],
      "Resource Performance": [
        {
          "corporate_kpi_name": "KPI 6 - Resource Utilization (RUI)",
          "department_kpi_name": "KPI 6 - Resource Utilization (RUI)",
          "rating": 0,
          "score": 0,
          "target": "0.75",
          "weight": "0.1",
          "year_to_department_kpi_id": 376
        },
        {
          "corporate_kpi_name": "KPI 7 - Resource Booking (RBI)",
          "department_kpi_name": "KPI 7 - Resource Booking (RBI)",
          "rating": 0,
          "score": 0,
          "target": "0.75",
          "weight": "0.1",
          "year_to_department_kpi_id": 377
        }
      ],
      "Strategic Conformance Rating": [
        {
          "corporate_kpi_name": "KPI 8 - Strategic Conformance Ratio (STG)",
          "department_kpi_name": "KPI 8 - Strategic Conformance Ratio (STG)",
          "rating": 0,
          "score": 0,
          "target": "meet target of Strategic conformance ratio",
          "weight": "0.1",
          "year_to_department_kpi_id": 378
        }
      ],
      "company": "MFEC",
      "department": "Digital Sustainability",
      "division": "Business Innovation Unit",
      "total": 0,
      "total_percentage": 0
    }
  ]
}

**Comment by nawapornmanyanon** [comment]
https://s4-test-api.mfec.dev/api/v1/summaries/report/scores/department_kpi?duration_id=3&company=MFEC&department_id=IN00000&division_id=IN03000


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dd3ba0e9-ebea-46a3-a648-7053b7c3df9b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/536c1dd3-5955-47bf-a4f6-1a374410e809)


@sainamphung  @wichita-ser  อันนี้ หลังบ้านต้องลง ทั้ง Rating และ Score มาให้เลยมั้ย

**Rating** ถ้าเป็น 
Auto  มันน่าจะต้องไปดึงมาจาก  Table : bu_performance_result 
Score by admin  มันน่าจะต้องไปดึงมาจาก  Table : department_kpi_score  ป

แล้วจากนั้น เอามา คูณกับ weight 
score = Rating x weigt/100 



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dbfc443a-8519-4c34-80fe-bc30472a6297)

**Comment by nawapornmanyanon** [comment]
@wichita-ser  Copy code cal  
มาจาก เส้นนี้ https://s4-test-api.mfec.dev/api/v1/evaluates/performance/04407/duration/4


REF :
- https://github.com/S4-Internal-app/Evaluated/issues/597

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7cd5b75e-e721-45e4-a9b4-83dcd89f7380)
