### ISSUE TITLE
[KPIsetting][Prespective] - กรณี Edit แล้ว ข้อมูล department และ Devision หาย

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#553]
ต่อ DB : for_dev

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cf604193-a393-4b6c-b993-b147dc1f45a3)

**Comment by TanawatMfec** [comment]
รอ API เสร็จแล้วแก้ทีเดียว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3680461a-3461-450c-aa95-7434fce25726)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c253cab0-2a8b-4c44-8517-d330290cf7ce)
