### ISSUE TITLE
[API][Summary] - Get summary percentage total score of year

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#554]
**AC**: [Score compare report](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlLmxvb3A%2FZD13MzE1N2VlZWM2ZmRlNDZjYTg1OTczOGNiZmY4M2RjMTAmY3NmPTEmd2ViPTEmbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY4eVlUWTBPVE01WlMxaU5UQm1MVFF4TUdRdE9HSTNPUzAxTnpBd09HWmpOR0kxT1dRbVpEMWlJVzV3VG10TFp5MHhSRlZIVEdWV1kwRnFPRk14YmxnMVNYaEhiVlpWTW1SRWFqUm5TblpYYm1GM2NuUlFiR3d0VXpkRU5FRlRjV3BmZVRCclJrc3lNM2NtWmowd01UTkRRak5IVmxoTk5WcE1WRVJZVkZCYVNrUkpURVphV1ZwUU4xbElXRUZSSm1NOUpUSkdKbVpzZFdsa1BURW1ZVDFNYjI5d1FYQndKbkE5SlRRd1pteDFhV1I0SlRKR2JHOXZjQzF3WVdkbExXTnZiblJoYVc1bGNpWjRQU1UzUWlVeU1uY2xNaklsTTBFbE1qSlVNRkpVVlVoNGRGcHRWbXBpTWpWcVlrYzVNVnBETlhwaFIwWjVXbGhDZG1GWE5UQk1iVTUyWWxoNGFVbFhOWGRVYlhSTVdua3dlRkpHVmtoVVIxWlhXVEJHY1U5R1RYaGliR2N4VTFob1NHSldXbFpOYlZKRllXcFNibE51V2xoaWJVWXpZMjVTVVdKSGQzUlZlbVJGVGtWR1ZHTlhjR1psVkVKeVVtdHplVTB6WkRoTlJFVjZVVEJKZWxJeFdsaE9SVEZZVFRCR1ExRjZUbGhUVmxwSFUxUmtWMDVWVmxCU1ZVcFJVMnhPUTFaM0pUTkVKVE5FSlRJeUpUSkRKVEl5YVNVeU1pVXpRU1V5TWpsaE1qUmpOek00TFROak5EQXRORFpqTmkwNU16RXhMVFptWTJVME5qRmpOakV3TXlVeU1pVTNSQSUzRCUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiOWEyNGM3MzgtM2M0MC00NmM2LTkzMTEtNmZjZTQ2MWM2MTAzIn19)

**Description**: Get total percentage score by multiple round, default round (current duration)

**Role**:
- Admin
- Supervisor

**Table**:
- employee
- employee_grade

**Query String**:
- duration_id (array)
- company
- department_id
- division_id
- level

**Response**:
```
{
  "payload": [
    "employee_name": "firstname_en lastname_en",
    "employee_id": "",
    "level": "",
    "department": "",
    "division":"",
    "position":"",
    "total_percentage_list": [
      {
        "duration_id": 1,
        "round_name": "",
        "total_score": 80
      }
    ]
  ]
}
```

**Note**:
- validate current user by access token

**Comment by sainamphung** [comment]
[GET] /api/v1/summaries/report/scores/percentage

**Comment by nawapornmanyanon** [comment]
@sainamphung 
ถ้าจะทำให้ Duration_ID = 3 มี DATA ต้องทำงัย
Duration_id = 3 เป็นการประเมินก่อนหน้า
Duration_id = 4 เป็นการประเมินปัจจุบัน  สามารถ Get DATA ได้  แต่ยังไม่ได้ check คะแนนต้องรอให้ eva ก่อน
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/477e6fdb-72a2-428e-a8b2-f2d42c6852ef)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/34f54ad0-70f3-4e7d-9801-13e12b8b7eef)

**Comment by wichita-ser** [comment]
**หลังบ้าน Recheck:**
จริงๆ ใน DB duration_id = 3 มีข้อมูล แต่ยิง API แล้วออกเป็น empty array

**Comment by sainamphung** [comment]
เกิดจากว่าเรา query มาจาก employee_grade ซึ่งเป็น table ใหม่เนื่องจากใน table นี้มีครบทุกอย่างที่เราจะแสดง มันจะช่วยลดการ join กันได้มากกว่าดึงมาจาก table เก่าอย่างพวก kpi_evaluate กับ core_value ค่ะ

ทีนี้ที่ employee_grade มันมีแค่ duration 4 อย่างเดียว duration 3 เลยเป็นค่าว่าง

**Comment by nawapornmanyanon** [comment]
@sainamphung ตอน PROD เราต้องทำงัย ถึงจะทำให้ DURATION : MID สามารถดึงข้อมูลมา compare กับ ปัจจจุบันได้อ่า

แบบเขาจะเทียบคะแนน TOTAL ของ Annual กับ Mid  year 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/357fc12b-3356-4544-8a67-e3f5c6527fd8)

**Comment by sainamphung** [comment]
มี 2 ทางค่ะ
1. migrate data ของรอบ Mid year ไปลงใน table employee_grade
2. แก้ query ใหม่เลยเป็นแบบ join กันแล้วดึงมาแสดง แต่จะเหมือนกับหน้า summary คือต้อง join เยอะแล้วก็มีคำนวณระหว่างทางทุกครั้งที่เรียกค่ะ

ถ้าให้แนะนำคิดว่าแบบ 1 น่าจะดีกว่าค่ะ ทำแค่รอบเดียว

**Comment by nawapornmanyanon** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/708
