### ISSUE TITLE
[Front-end][Connect_API][Admin] - get employee list on employee tab from card 539

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#555]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=40313633

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/ce604c6e-c4ec-4706-b659-2301d631d197)

**Comment by nawapornmanyanon** [comment]
ต่อ API แล้ว แต่ DATA มาไม่ครบ เปิดการ์ดรายจุดไปให้ DEV

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/34908aa5-c7f1-4d2b-86b8-a57ea88bc24a)
