### ISSUE TITLE
[Front-end][Connect_API] - get department KPI from card 536

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#556]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?filterQuery=536&pane=issue&itemId=40567889

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/4127d6c7-e195-4b30-8c68-fc4cc1adad4d)

**Comment by nawapornmanyanon** [comment]
#536 In progress

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d31a75c3-54a2-4d71-80a6-ce5a0da013a8)

**Comment by nawapornmanyanon** [comment]
ติดเรื่อง Response ไปการ์ดหลังบ้าน แทน
- https://github.com/S4-Internal-app/Evaluated/issues/733
