### ISSUE TITLE
[API][KPI Setting] - Get current department KPI score of all division

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#557]
**AC**: [Score by admin](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlJTIwMy5sb29wP2Q9dzY0NjA3NjBhNzY0ZDRjYTViOTdiNjUwNmZmOTJmM2Y0JmNzZj0xJndlYj0xJm5hdj1jejBsTWtaamIyNTBaVzUwYzNSdmNtRm5aU1V5UmtOVFVGOHlZVFkwT1RNNVpTMWlOVEJtTFRReE1HUXRPR0kzT1MwMU56QXdPR1pqTkdJMU9XUW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsRkxUMXBSUjBsVVRGZFZWa2RNVXpZelJrRXpOMXBHTkRkVkptTTlKVEpHSm1ac2RXbGtQVEVtWVQxTWIyOXdRWEJ3Sm5BOUpUUXdabXgxYVdSNEpUSkdiRzl2Y0Mxd1lXZGxMV052Ym5SaGFXNWxjaVo0UFNVM1FpVXlNbmNsTWpJbE0wRWxNakpVTUZKVVZVaDRkRnB0Vm1waU1qVnFZa2M1TVZwRE5YcGhSMFo1V2xoQ2RtRlhOVEJNYlU1MllsaDRhVWxYTlhkVWJYUk1Xbmt3ZUZKR1ZraFVSMVpYV1RCR2NVOUdUWGhpYkdjeFUxaG9TR0pXV2xaTmJWSkZZV3BTYmxOdVdsaGliVVl6WTI1U1VXSkhkM1JWZW1SRlRrVkdWR05YY0dabFZFSnlVbXR6ZVUwelpEaE5SRVY2VVRCSmVsSXhXbGhPUlRGWVRUQkdRMUY2VGxoVFZscEhVMVJrVjA1VlZsQlNWVXBSVTJ4T1ExWjNKVE5FSlRORUpUSXlKVEpESlRJeWFTVXlNaVV6UVNVeU1tRXdNREJoTTJRMkxUQXpZemd0TkRGaFpDMWhPREUxTFRreFlUVm1Oak16TlRNeE55VXlNaVUzUkElM0QlM0QiLCJyIjpmYWxzZX0sImkiOnsiaSI6ImEwMDBhM2Q2LTAzYzgtNDFhZC1hODE1LTkxYTVmNjMzNTMxNyJ9fQ%3D%3D)

**Description**: Get department KPI score in current duration

**Role**:
- Admin

**Table**:
- department_kpi
- year_to_department_kpi
- department_kpi_score

**Params**:
- duration_id

**Response**:
```
payload: {
  "department_kpi_score_list": [{
     "year_to_department_kpi_id": 1,
     "department_name": "",
     "division_name": "",
     "department_kpi_name": "",
     "division_id": "",
     "rating": 3,
     "score": 100
  }]
}
```

**Comment by wichita-ser** [comment]
[GET] /api/v1/evaluates/department_kpi/<duration_id>/score

**Comment by wichita-ser** [comment]
เส้นนี้ การ์ดนี้ ไม่ใช้แล้ว 
Duplicated with https://github.com/S4-Internal-app/Evaluated/issues/671
