### ISSUE TITLE
[Bug] - Upload file (Add null value)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#56]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4a764bbe-682d-4383-82b8-48cd2d39e001)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f4211603-439d-414d-8559-78352b9a8d5f)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9ddf71c2-ea97-4e4d-b96c-7f875d28c7c8)
