### ISSUE TITLE
[Bug][Duration][Layout] Fix Layout + change word create and update duratuion

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#564]

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/4d3c09dd-2a13-4702-8f3c-7aa7491346e1)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2046b9f9-88b5-4a5f-8833-532e1a0366b0)
