### ISSUE TITLE
[API][Summary] - Get grade quota

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#565]
**AC**: [Grade report](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlJTIwMy5sb29wP2Q9dzNiMmFjZDljN2ViZjQxNTk5ZmZlODE5MWJjMzMwMWM4JmNzZj0xJndlYj0xJm5hdj1jejBsTWtaamIyNTBaVzUwYzNSdmNtRm5aU1V5UmtOVFVGOHlZVFkwT1RNNVpTMWlOVEJtTFRReE1HUXRPR0kzT1MwMU56QXdPR1pqTkdJMU9XUW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsVTBXbFZXUkZoUU16Wk1Sa0ZhTnpkVlFsTkhOa1JIUVU5SkptTTlKVEpHSm1ac2RXbGtQVEVtWVQxTWIyOXdRWEJ3Sm5BOUpUUXdabXgxYVdSNEpUSkdiRzl2Y0Mxd1lXZGxMV052Ym5SaGFXNWxjaVo0UFNVM1FpVXlNbmNsTWpJbE0wRWxNakpVTUZKVVZVaDRkRnB0Vm1waU1qVnFZa2M1TVZwRE5YcGhSMFo1V2xoQ2RtRlhOVEJNYlU1MllsaDRhVWxYTlhkVWJYUk1Xbmt3ZUZKR1ZraFVSMVpYV1RCR2NVOUdUWGhpYkdjeFUxaG9TR0pXV2xaTmJWSkZZV3BTYmxOdVdsaGliVVl6WTI1U1VXSkhkM1JWZW1SRlRrVkdWR05YY0dabFZFSnlVbXR6ZVUwelpEaE5SRVY2VVRCSmVsSXhXbGhPUlRGWVRUQkdRMUY2VGxoVFZscEhVMVJrVjA1VlZsQlNWVXBSVTJ4T1ExWjNKVE5FSlRORUpUSXlKVEpESlRJeWFTVXlNaVV6UVNVeU1qaGtZVGM1TlRZekxXRTVOR1V0TkdJM1lpMWhaalJoTFdOak1ETmtZVFJpTXprek5TVXlNaVUzUkElM0QlM0QiLCJyIjpmYWxzZX0sImkiOnsiaSI6IjhkYTc5NTYzLWE5NGUtNGI3Yi1hZjRhLWNjMDNkYTRiMzkzNSJ9fQ%3D%3D)

**Description**: Show list of grade quota of department/division

**Table**:
- employee_grade
- grade

**Query String**:
- company (id)
- department_id (id)
- division_id (id)

**Response**:
```
{
"payload": [
 "grade": "A+",
 "range": "",
 "quota_percentage": 10,
 "actual_percentage": 1,
 "diff_percentage": 9,
 "quota_person": 10,
 "actual_person"; 1,
 "diff_person": 9
]
}
```

**Note**:
- Validate current user by access token

`จำนวนคนทั้งหมด` ความหมายคือ จำนวนคนทั้งหมดในทีม หรือที่รับผิดชอบ โดยจะขึ้นอยู่กับ level ที่ access เข้าไป
เช่น พี่นาทเห็นแค่ 20 คน จำนวนคนทั้งหมด = 20

- actual_percentage  => (จำนวนคนที่ได้เกรดนั้น/จำนวนคนในทีม)*100
- actual_person => นับตามจำนวนคนที่ได้เกรดนั้นๆ จาก `EmployeeGrade`
- quota_person => (จำนวนคนทั้งหมด x quota_percentage)  / 100
- diff_percentage => (quota_percentage - actual_percentage)/จำนวนคนในทีม * 100
- diff_person => quota_person - actual_person

**Comment by wichita-ser** [comment]
[GET] /api/v1/summaries/report/grade/quota?company=&department_id=&division_id

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4ed9099d-c31b-4df0-bf27-42865a1a1a18)

**Comment by nawapornmanyanon** [comment]
@sainamphung  ฝาก Order grade ให้หน่อย


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7c656681-d53d-4df1-a76b-f3d6a02e8186)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/40ab952d-400f-41bc-b3e5-b18481016e4f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/53088e86-7072-415d-9ba6-27b8fb9fc981)
