### ISSUE TITLE
[API][All] - Get division list by department

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#569]
**Description**: Get division list for dropdown filter by department_id

**Table**:
- office_master

**Params**:
- department_id

**Response**:
```
{
"division_list": [{
  "division_id": "",
  "division_name": ""
}]
}
```

**Comment by wichita-ser** [comment]
[GET] /api/v1/masters/divisions?department_id=

**Comment by nawapornmanyanon** [comment]
Role : Admin


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/630cf4d1-6ce8-4c02-a261-66d8e58071fa)
