### ISSUE TITLE
[API][Evaluate] - Update core value score

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#570]
**Description**: Update core value score from evaluation

**Role**:
- All user

**Table**:
- core_value
- core_value_detail
- employee_grade
- grade

**Body**:
```
{
"duration_id": 1,
"is_supervisor": true,
"core_value_id": 1,
"core_value_list": [{
 "choice": 1,
 "rating": 3,
 "comment": ""},
 {
 "choice": 2,
 "rating": 3,
 "comment": ""}
 ]
}
```

**Response**:
```
200
```

**Note**:
- Only admin can access this API
- ต้องคำนวณและ update total score ลงใน table `EmployeeGrade` ด้วย
- ต้องเอา total score ที่คำนวณได้ไปเชค grade และ update ที่ table `Grade` ด้วย

- ถ้าจะ update ที่ `EmployeeGrade` ต้องเป็น sup ของ row นั้นๆ (เป็น sup ของคนนั้นๆ)

**Comment by wichita-ser** [comment]
[POST] /api/v1/admins/evaluate/core_value

**Comment by wichita-ser** [comment]
need discussion with P'Phung before testing/done

**Comment by wichita-ser** [comment]
New request body:
เปลี่ยน `core_value_id` เป็น `employee_id`
```
{
   "duration_id": 1,
   "is_supervisor": true,
   "employee_id": "00159",
   "core_value_list": [{
     "choice": 1,
     "rating": 3,
     "comment": ""
   },{
     "choice": 2,
     "rating": 3,
     "comment": ""
   }]
}
```

**Comment by TanawatMfec** [comment]
Connected in Evaluate Core value

**Comment by wichita-ser** [comment]
ขอแก้ PATH ค่า 
[POST] /api/v1/evaluates/core_value/update_score

**Comment by wichita-ser** [comment]
Example of request body:

```
{
  "core_value_list": [
    {
      "choice": 1,
      "comment": "string",
      "rating": 5
    },
    {
      "choice": 2,
      "comment": "Comment from swagger",
      "rating": 5
    },
    {
      "choice": 3,
      "comment": "Comment from swagger",
      "rating": 5
    },
    {
      "choice": 4,
      "comment": "Comment from swagger",
      "rating": 5
    },
    {
      "choice": 5,
      "comment": "Comment from swagger",
      "rating": 5
    },
    {
      "choice": 6,
      "comment": "#2 Comment from swagger",
      "rating": 5
    },
    {
      "choice": 7,
      "comment": "#2 Comment from swagger",
      "rating": 5
    }
  ],
  "duration_id": 4,
  "employee_id": "03832",
  "is_supervisor": true
}
```

**Comment by nawapornmanyanon** [comment]
เส้นนี้ 500

**Comment by wichita-ser** [comment]
พอจะมี detail ที่ยิงแล้ว 500 ไหมคะ ยังเทสไม่เจอค่ะ @nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
ไม่ 500 แล้ว  แต่เป็น 400 BAD_REQUEST

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fbc8035d-36d8-4630-830f-ea70bccb3d3a)
