### ISSUE TITLE
[Front-end][Connect-API][Admin] Deactive employee from card 541

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#571]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?filterQuery=541&pane=issue&itemId=40425122

**Comment by nawapornmanyanon** [comment]
กด Deactive แล้วError  Status ไม่เปลี่ยน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fbe331ac-de66-4dc9-bb37-e839d385aded)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8a05c501-0923-43cc-8769-feebf4edec5b)

**Comment by nawapornmanyanon** [comment]
กรณี Deactivated  Employee ที่เคย Assign DepartmentKPI ให้แล้ว จะ Error
 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9288e81a-859e-4c5c-a13d-59e420f8f505)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/27cbaec6-8c25-4615-9f31-00c2e3782b36)

**Comment by wichita-ser** [comment]
REF API: https://github.com/S4-Internal-app/Evaluated/issues/540

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7dd88bb4-7389-48b7-96e9-cee56a49acca)
