### ISSUE TITLE
[Front-end][Connect-API][Admin] Active Employee from card 540

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#572]

**Comment by nawapornmanyanon** [comment]
กด Deactivate แล้ว Error  status ไม่เปลี่ยน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a8b99143-3247-4c50-9b4f-5ce5cb446d80)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5f5a929-661d-4d62-9b78-c4ee66ec54f7)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7ef0bfe1-0a7c-4f64-8d2f-9516baaefbfc)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b7f51ced-4231-480d-ade7-e025f5bff2f3)
