### ISSUE TITLE
[Front-End][PageList] List Page ว่าหน้าไหนต่อ API อะไรบ้าง

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#573]
List All Page  หน้าไหนเสร็จแล้ว ยังไม่ได้ทำ หรือ ยังทำไม่เสร็จ 
และเช็คว่าหน้าไหนต่อ API อะไรไปบ้าง

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon อันนี้ list ไว้ไหนนะ @warakornlj

**Comment by warakornlj** [comment]
ใน Loop ครับพี่ [https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21mZWNvbmNsb3VkLnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVc1d1RtdExaeTB4UkZWSFRHVldZMEZxT0ZNeGJsZzFTWGhIYlZaVk1tUkVhalJuU25aWGJtRjNjblJRYkd3dFV6ZEVORUZUY1dwZmVUQnJSa3N5TTNjbVpqMHdNVE5EUWpOSFZsYzBUVmN6UVVKRE0xZEpWa1pKTjFZMVJVOUZRbEJLVTBKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9tZmVjb25jbG91ZC5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzJhNjQ5MzllLWI1MGYtNDEwZC04Yjc5LTU3MDA4ZmM0YjU5ZC9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQlMjBwYWdlLmxvb3A%2FZD13MmVlNGMwYmQ2NzExNDNkN2E2OWYyMzgyZmU4MmI5OTUmY3NmPTEmd2ViPTEmbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY4eVlUWTBPVE01WlMxaU5UQm1MVFF4TUdRdE9HSTNPUzAxTnpBd09HWmpOR0kxT1dRbVpEMWlJVzV3VG10TFp5MHhSRlZIVEdWV1kwRnFPRk14YmxnMVNYaEhiVlpWTW1SRWFqUm5TblpYYm1GM2NuUlFiR3d0VXpkRU5FRlRjV3BmZVRCclJrc3lNM2NtWmowd01UTkRRak5IVmxZMVdVUlRRelJGVEVneU5VSXlUa2hhUkZGTU4wbEdUMDFXSm1NOUpUSkdKbVpzZFdsa1BURW1ZVDFNYjI5d1FYQndKbkE5SlRRd1pteDFhV1I0SlRKR2JHOXZjQzF3WVdkbExXTnZiblJoYVc1bGNpWjRQU1UzUWlVeU1uY2xNaklsTTBFbE1qSlVNRkpVVlVoNGRGcHRWbXBpTWpWcVlrYzVNVnBETlhwaFIwWjVXbGhDZG1GWE5UQk1iVTUyWWxoNGFVbFhOWGRVYlhSTVdua3dlRkpHVmtoVVIxWlhXVEJHY1U5R1RYaGliR2N4VTFob1NHSldXbFpOYlZKRllXcFNibE51V2xoaWJVWXpZMjVTVVdKSGQzUlZlbVJGVGtWR1ZHTlhjR1psVkVKeVVtdHplVTB6WkRoTlJFVjZVVEJKZWxJeFdsaE9SVEZZVFRCR1ExRjZUbGhUVmxwSFUxUmtWMDVWVmxCU1ZVcFJVMnhPUTFaM0pUTkVKVE5FSlRJeUpUSkRKVEl5YVNVeU1pVXpRU1V5TWpoa016UXhObU14TFdZMlptUXROREF3WVMxaFpUUTJMVGd6TkRsbFpXWmhOV1UyTWlVeU1pVTNSQSUzRCUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiOGQzNDE2YzEtZjZmZC00MDBhLWFlNDYtODM0OWVlZmE1ZTYyIn19](url)
