### ISSUE TITLE
[Front-end][Connect_API][Summary] Connect API summary grade report from card 549

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#574]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=40430532

**Comment by nawapornmanyanon** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/716 ไปต่อการ์ดนี้
