### ISSUE TITLE
[Front-end][Connect_API][Summary] conenct API from card 565

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#575]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=41062053

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/be97c6e6-5ed0-48ef-b9ee-a79bf6ed8e71)
