### ISSUE TITLE
[Front-end][Connect_API][Report] Connect API for summary report from card 504

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#576]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=39805023

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2a9ff296-284a-469b-bd89-1edc189226cc)
