### ISSUE TITLE
[Report] [Department][Individual][Core Value] [Summary] Handle all reports by showing content base on selected report. (See their own or another report)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#577]

**Comment by nawapornmanyanon** [comment]
Department KPI report
----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ff5e6059-cb7a-4e3f-b343-6fbc4be12b0d)

**Comment by nawapornmanyanon** [comment]
Individual KPI report
-----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b907e5af-4781-461e-82c1-00189decb128)

**Comment by nawapornmanyanon** [comment]
Core value
-----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ce2aa719-9f95-4088-bbe3-9bf5278c9b5b)

**Comment by nawapornmanyanon** [comment]
Summary report
---


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/599e8a11-3d1c-413b-bea2-bac4e7088826)
