### ISSUE TITLE
[Bug][Duration][Modal Details] แก้การแสดงปุ่ม Edit and Close

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#578]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f40985b4-13c9-4337-9933-e8ad1f48fed0)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1314693b-ad5d-419c-abb2-0a3801235a55)
