### ISSUE TITLE
[Front-end][Connect_API][Evaluate] - update core value score from card 570

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#579]

**Comment by TanawatMfec** [comment]
https://github.com/orgs/S4-Internal-app/projects/4/views/1?pane=issue&itemId=41190615

**Comment by nawapornmanyanon** [comment]
รอให้ Evaluate ได้ถึงจะ Update ได้ @nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ca0dd9f9-506c-4d38-a3b2-1e5908a92c60)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f8b5a912-03a4-438d-92f3-7dc9d74b8dd2)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2b1f8185-b1bf-4cf2-a4a7-5457e2151af9)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9258b9aa-a789-4c44-a53d-5c55b4fce816)
