### ISSUE TITLE
[Front-end][Connect_API] - Handle Update KPI score from card 537

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#586]

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/537

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/930b839a-44a0-44e4-a1fe-a85b7c89440d)

**Comment by nawapornmanyanon** [comment]
รอ https://github.com/S4-Internal-app/Evaluated/issues/802 ใบนนี้ @nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c02e6f26-14f3-4067-bc50-bea3748834f8)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ba1add22-f8e9-4fc2-b189-ba3cf3f4710a)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/66b706c9-a489-4fa8-afc6-b70f7c3670e1)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/acabced4-0471-4959-ac87-d1c1dcbfb136)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5f92d188-1cf6-4fe5-b94a-12c37cb5fab5)
