### ISSUE TITLE
[Front-end][Connect_API] [Evaluate]-  from card 535

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#587]

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/535

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f08b10ee-2644-493b-9a09-fd686c5e9c31)
