### ISSUE TITLE
[Front-end][Connect_API][KPI Setting][Department KPI] connect API

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#591]

**Comment by warakornlj** [comment]
หาก Department KPI ตัวนั้นใช้งานไปแล้ว จะต้องทำยังไง

**Comment by warakornlj** [comment]
ทดสอบ add_kpi_list แล้ว เหลือลอง update_kpi_list กับ delete_kpi_list

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/889afe87-8ec5-4da6-a83a-29e606efd088)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/10f7f5a0-9acc-41a9-909b-cfe345417903)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/42afffff-d828-4711-8540-ce5bf8f85c52)
