### ISSUE TITLE
[API][Evalaute] แก้ไข response เส้น report get kpi, core value

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#592]
เพิ่ม key เข้าไปใน response body ของ API ดังต่อไปนี้:

- Report Department KPI API [Link](https://s4-dev-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_report_department_kpi)
  - total_score
  - total_score_percentage
  - employee rating
  - supervisor rating
  - kpi_total (ผลรวม department kpi + individual kpi)
  - kpi_total_percentage (ผลรวม % department kpi + individual kpi)
  - kpi_evaluate_id
 

- Report Individual KPI API [Link](https://s4-dev-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_report_individual_kpi)
  - total_score
  - total_score_percentage
  - employee rating
  - supervisor rating
  - kpi_total (ผลรวม department kpi + individual kpi)
  - kpi_total_percentage (ผลรวม % department kpi + individual kpi)
  - kpi_evaluate_id

- Report Core value API [Link](https://s4-dev-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_report_core_value)
  - total_score
  - total_score_percentage
  - employee rating
  - supervisor rating

**Comment by oxenearth55** [comment]
อาจจะต้องส่ง kpi_evaluate_id มาเพิ่มครับ พอดีเหมือนตอน evaluate kpi หลังบ้านต้องใช้อันนี้ด้วย

**Comment by wichita-ser** [comment]
@nawapornmanyanon
Backend TODO:
1. Recheck total score ต่างๆ
- total_score, total_score_percentag, kpi_total_percentagee เต็ม 100
- kpi_total เต็ม 120

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/45dec4d6-8512-4a13-859a-1952f027f52d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8f123158-844e-4948-b30e-e66ba12dd50a)

**Comment by nawapornmanyanon** [comment]
@wichita-ser @nawapornmanyanon  เด๋วรอน้องแก้ ทศนิยม จาก 87.125  เป็น 87.13  ก็เสร็จแล้ว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/59e69de3-905e-4432-8c41-d7e2deb7c494)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5c902d6c-25c4-4604-8422-657ec83f3312)
