### ISSUE TITLE
[API][Evaluate] - Edit API get auto evaluate score

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#597]
ของเดิมมันดึงเฉพาะ auto_eva ที่มาจาก pivot
- ภาพรวมใน function เดิมต้องเปลี่ยนเป็น จาก constant แทน

ของใหม่ต้องแก้ให้ดึง department kpi score ที่ admin ใส่คะแนนไว้ให้ด้วย

**Params**:
- duration_id
- employee_id

**Response**:
```
{
"department_kpi_list": [{
   "department_kpi_id": 1,
   "department_kpi_name": "",
   "target": "",
   "measurement": "",
   "weight": 10,
   "rating": 3,
   "score": 10,
   "perspective": ""
}],
"total_score": 0,
"total_score_percentage": 0
}
```

**Comment by sainamphung** [comment]
score = คะแนนตาม rating * weight
ถ้าตามตวอย่าง response score จะเท่ากับ 10

**Comment by wichita-ser** [comment]
[GET] /api/v1/evalautes/performance/<employee_id>/duration/<duration_id>

**Comment by nawapornmanyanon** [comment]
Durtion 4
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/14e67046-2f31-4baa-8c9e-a8785fe5bbe9)

Duration 3
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8a28edf3-c5b8-4193-a17c-ea6849888b13)

**Comment by nawapornmanyanon** [comment]
AUTO Score
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ecf5e953-2a86-408c-8c71-aabe69d55a09)

Score by Admin
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6de0fe45-4ba0-49fc-ae7c-4ec94374f8fe)

**Comment by nawapornmanyanon** [comment]
Department KPI list : 04407 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e954fd77-5281-4f58-9c84-6fbd4595afa4)

**Comment by wichita-ser** [comment]
**Backend Note แก้ไข:**
จะต้องส่งทุก department kpi ที่เขามี
เพราะฉะนั้น employee_id = 04407, duration_id = 4 จะมี 6 rows (admin 4, auto score 2)

**Comment by wichita-ser** [comment]
ตอนนี้ deploy แล้ว department kpi แสดงจำนวนรายการแล้วค่ะ @nawapornmanyanon 
แต่ต้องขอ recheck เรื่อง score เพิ่มเติม

แตงไม่แน่ใจว่า `target`, `measurement`, `weight` มาจาก table `year_to_department_kpi` หรือ `kpi_evaluate_detail`
@sainamphung

**Comment by nawapornmanyanon** [comment]
weight ดึงจาก kpi_evaluate_detail เป็นของ employee รายคน

**Comment by wichita-ser** [comment]
**หลังบ้าน Recheck:**
department kpi ใน department เดียวกันสามารถมีจำนวนข้อไม่เท่ากัน เพราะแต่ละคนมี weight/kpi ไม่เหมือนกัน
เช่น พี่นาท กับน้องในทีม

**Comment by wichita-ser** [comment]
need P'ผึ้ง help @sainamphung

**Comment by nawapornmanyanon** [comment]
@sainamphung   @wichita-ser Score แปลกๆ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/09aef605-16fd-4b6e-a6d6-938bc0006a92)

**Comment by nawapornmanyanon** [comment]
{
  "payload": {
    "department_kpi_list": [
      {
        "department_kpi_id": 452,
        "department_kpi_name": "Quality of hire - Number of employee pass probation",
        "measurement": "Employee demographic  report 2023",
        "perspective": "Strategic Conformance Rating",
        "rating": 1,
        "score": "1600",
        "target": "0.9",
        "weight": "20",
        "year_to_department_kpi_id": 452
      },
      {
        "department_kpi_id": 449,
        "department_kpi_name": "15% turnover rate",
        "measurement": "Employee demographic  report 2023",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": "0",
        "target": "0.15",
        "weight": "20",
        "year_to_department_kpi_id": 449
      },
      {
        "department_kpi_id": 447,
        "department_kpi_name": "KPI 6 - Resource Utilization (RUI)",
        "measurement": "RUI  from Pivot report",
        "perspective": "Resource Performance",
        "rating": 2,
        "score": "9",
        "target": "0.75",
        "weight": "10",
        "year_to_department_kpi_id": 447
      },
      {
        "department_kpi_id": 450,
        "department_kpi_name": "OLA recruitment of Manager Level",
        "measurement": "TA Report",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": "0",
        "target": "75-90 Days",
        "weight": "20",
        "year_to_department_kpi_id": 450
      },
      {
        "department_kpi_id": 451,
        "department_kpi_name": "OLA recruitment of officer Level",
        "measurement": "TA Report",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": "0",
        "target": "45-60 Days",
        "weight": "20",
        "year_to_department_kpi_id": 451
      },
      {
        "department_kpi_id": 448,
        "department_kpi_name": "KPI 7 - Resource Booking (RBI)",
        "measurement": "RBI  from Pivot report",
        "perspective": "Resource Performance",
        "rating": 2,
        "score": "9",
        "target": "0.75",
        "weight": "10",
        "year_to_department_kpi_id": 448
      }
    ],
    "total_score": "1618",
    "total_score_percentage": 1348.33
  }
}

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  น้องแก้แล้ว Wait for deploy

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9e257593-3a02-46d7-b7c1-e8152bbcb5a9)

**Comment by nawapornmanyanon** [comment]
{
  "payload": {
    "department_kpi_list": [
      {
        "department_kpi_id": 452,
        "department_kpi_name": "Quality of hire - Number of employee pass probation",
        "measurement": "Employee demographic  report 2023",
        "perspective": "Strategic Conformance Rating",
        "rating": 1,
        "score": 16,
        "target": "0.9",
        "weight": "20",
        "year_to_department_kpi_id": 452
      },
      {
        "department_kpi_id": 449,
        "department_kpi_name": "15% turnover rate",
        "measurement": "Employee demographic  report 2023",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": 0,
        "target": "0.15",
        "weight": "20",
        "year_to_department_kpi_id": 449
      },
      {
        "department_kpi_id": 447,
        "department_kpi_name": "KPI 6 - Resource Utilization (RUI)",
        "measurement": "RUI  from Pivot report",
        "perspective": "Resource Performance",
        "rating": 2,
        "score": 9,
        "target": "0.75",
        "weight": "10",
        "year_to_department_kpi_id": 447
      },
      {
        "department_kpi_id": 450,
        "department_kpi_name": "OLA recruitment of Manager Level",
        "measurement": "TA Report",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": 0,
        "target": "75-90 Days",
        "weight": "20",
        "year_to_department_kpi_id": 450
      },
      {
        "department_kpi_id": 451,
        "department_kpi_name": "OLA recruitment of officer Level",
        "measurement": "TA Report",
        "perspective": "Strategic Conformance Rating",
        "rating": 0,
        "score": 0,
        "target": "45-60 Days",
        "weight": "20",
        "year_to_department_kpi_id": 451
      },
      {
        "department_kpi_id": 448,
        "department_kpi_name": "KPI 7 - Resource Booking (RBI)",
        "measurement": "RBI  from Pivot report",
        "perspective": "Resource Performance",
        "rating": 2,
        "score": 9,
        "target": "0.75",
        "weight": "10",
        "year_to_department_kpi_id": 448
      }
    ],
    "total_score": 34,
    "total_score_percentage": 28.33
  }
}
