### ISSUE TITLE
[Bug] - Edit Duration => not show every data

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#61]
![Image](https://user-images.githubusercontent.com/132323829/242459585-fe77e4f2-eaa9-4d2d-981e-0a637f1c9b5a.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8baf0127-2c7f-42bd-b6aa-f0ade0d9e257)
