### ISSUE TITLE
[Front-end][Connect_API][KPI Setting][Corporate KPI] connect API

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#615]

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/662

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/df6fe704-a268-4e7e-b61a-9f6e33faa0de)

**Comment by nawapornmanyanon** [comment]
@warakornlj   @nawapornmanyanon   ยังสามารถ Delete Corporate KPI ที่ใช้ไปแล้วได้

**Comment by nawapornmanyanon** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/737

TEST ต่ออันนี้
