### ISSUE TITLE
[KPISetting][ScoreByAdmin] - หน้าบ้านเพิ่ม UI filter

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#617]
pdate score By admin อ่า
 
ใส่ Filter เหมือนหน้า Department ที่โจ้กำลังทำนะ  
 
กด Update score  แลวเปิดหน้า Update score ให้เลือก Company  , Department , Division  แล้วก็ Update score กด save
 
ให้ทำไปทีละ Division  จะได้ลดภาระหลังบ้าน ตอนวิ่งไปตาม Update

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/98282db1-faf2-4fde-a0a7-d2f4ed2cfd0f)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/50c3a1c7-1f4b-42e6-b344-12d47e94ecda)

**Comment by warakornlj** [comment]
ใช้รวมกับ branch 582_kpi_setting_page

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2e1fd2f8-f3e0-4831-abd9-57e90883e42c)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1ef43923-36d2-4a6e-86ee-35ec9b179857)
