### ISSUE TITLE
[Front-end][Connect-API] Get auto from card 597 in Department

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#618]

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/597

**Comment by nawapornmanyanon** [comment]
@TanawatMfec 
Rating ไม่แสดงที่หน้าจอ 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6d81a968-0024-4cb9-9524-21248c9369af)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec  ไม่สามารถกด Save ได้

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/89448278-5713-41ed-8b69-a6d113c1256d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7b5fbc03-d9a3-408d-a3e4-2bf154bc3cc8)
