### ISSUE TITLE
[PMSetting][IndividualKPI] - Perspective ต้องสามารถ upload ด้วยตัวเล็ก ตัวใหญ่ได้

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#622]
- perspective ต้องสามารถ upload ด้วยตัวเล็กตัวใหญ่ได้ (Insentitive) 

- ปุ่ม Close เปลี่ยนเป็นสีน้ำเงิน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b6103481-e05d-4fad-aba6-f526f4949803)

[Individual_KPI_by_Supervisor_V1_PeopleBusinessPartner(PBP).csv](https://github.com/S4-Internal-app/Evaluated/files/13222436/Individual_KPI_by_Supervisor_V1_PeopleBusinessPartner.PBP.csv)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  Recheck
-----

[Individual_KPI_by_Supervisor_Mlab_lower_Upper_perspective.csv](https://github.com/S4-Internal-app/Evaluated/files/13263778/Individual_KPI_by_Supervisor_Mlab_lower_Upper_perspective.csv)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/387e4368-8b9e-4d4a-a679-7758992ebe6b)

**Comment by nawapornmanyanon** [comment]
เราสามารถทำให้เป็น   >>> Strategic Conformance Rating   ตอน upload file ลงไป 
-----------

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ebaf36ec-890b-44bf-879c-f91f865bc03b)

**Comment by TanawatMfec** [comment]
ได้ครับ เดียวจัดให้ครับ @nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a429c435-2dc7-4fa0-8cb7-445eaf0d9b2f)
