### ISSUE TITLE
[PMSetting][GoalSetting] - Duration ดึงมาแสดงไม่ถูก

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#628]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cae85897-10a0-4008-9c28-ca1e1ee83526)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/24ac8501-955e-4c08-8ef4-0d1fff272f56)

**Comment by warakornlj** [comment]
หน้า PM Setting ใช้กับการ์ด [#677](https://github.com/S4-Internal-app/Evaluated/issues/677)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8dd01e27-0f48-4ed9-bad2-56ed133f686b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1b31e48e-ed08-47cd-b114-68c044d79cb0)
