### ISSUE TITLE
[Summary][Front-end] Handle API Summary Tab

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#629]

**Comment by TanawatMfec** [comment]
Summary ทุก tab + handle functions

**Comment by nawapornmanyanon** [comment]
@TanawatMfec 
9 Box grid ไม่แสดง Search box
---

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/10585193-cbc0-41f3-89a2-201842ff579f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8e35047b-a7af-4018-9286-e631fa7edc5e)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f1764956-8db5-4a17-9a56-064db7767a0d)
