### ISSUE TITLE
[Home][Previous] - Team member List  ต้องแสดงเฉพาะลูกน้องของตัวเอง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#630]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5fb4e87-6f0e-4afd-941b-415f2df0ce0a)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/44cbd10d-abc6-4d35-92b5-c38858a5f871)


จากการตรวจสอบ พบว่า ถ้าหาก API ตัวนี้จะมองว่า หากเป็น Admin จะแสดงทั้งหมด แต่หากไม่ใช่ แล้วเป็นแค่ Supervisor ข้อมูลนั้นจะแสดงแค่เฉพาะลูกน้องของตนเอง

1. กรณี Login เป็น Natnaka (Supervisor)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/3d5390c7-bd8b-4083-a6d0-c7f8f59b0029)


2. กรณี Login เป็น Natthida (Admin)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/720d4664-2a6b-4fac-b8cf-8fccb7946325)

อาจต้องให้ทางหลังบ้านช่วยดูให้ครับ

**Comment by nawapornmanyanon** [comment]
Admin ได้แล้ว 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/850c7b04-ce7a-4a03-8911-93e5c1832e00)
