### ISSUE TITLE
[Home][AdminReport] - Default แสดงกล่อง Search พร้อม icon  No data

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#631]
เมื่อ Admin กดปุ่ม Admin report ระบบแสดงกล่อง search เพื่อให้ admin เลือก criteria ก่อน โดยสามารถเลือก search by Department , Division , Level และมี Dropdown list ให้เลือก Company, Department, Division

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/14cdb0ad-583c-47b7-af2e-b6bc8a30e894)

**Expected result :**
---

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c377d6da-d2d0-42ff-b4a5-85c01ba5b091)

**Comment by nawapornmanyanon** [comment]
@warakornlj 
กรณี Admin เลือก Search by Department ให้ เปิดกล่อง Company ให้เลือกก่อน แล้วค่อยเปิด Department  ให้เลือก ไม่งั้นจะไม่มีข้อมูลให้เลือก
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1242bceb-099b-40b6-889e-940f2d840bae)

**Comment by nawapornmanyanon** [comment]
@warakornlj 
กรณี เลือก Search by Department  แล้วเปลี่ยนใจไปเลือก Devision ต่อ มันจะไม่แสดง Box ให้เลือก 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a545a522-d414-4a72-a254-137bd36bf36c)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  Level OK> แล้ว

**Comment by warakornlj** [comment]
ไปที่หน้า
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/30cae569-da46-4d9a-9206-752244d826f9)
