### ISSUE TITLE
[Home] - กรณีที่ไม่ใช่ Admin จะต้องแสดงแค่ 2 Menu

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#637]
กรณีที่ไม่ใช่ Admin ต้องแสดงแค่ Current round และ Previous Round เท่านั้น

ต้องไม่แสดง Admin Report

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c54e2366-6244-47bf-8222-0ea0b1ca12c8)

**Comment by nawapornmanyanon** [comment]
**กรณี เป็น Supervisor / Employee เมื่อ Login เข้ามา ให้ Default อยู่ที่ Current Round**
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/49f38050-d526-4986-8528-768c390ecdd3)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
@warakornlj 
step
1. login : Admin > Click Admin report > Logout
2. login : Supervisor ( Natnaka ) 

Expect to 
----
ระบบต้องเปิดหน้า Current Round 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fb5b9ed5-1305-491b-898a-02d353847f71)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/7e6c3a2c-0ddc-4dc5-b163-a0afd01c70e0)

กรณีไม่ใช่ admin จะแสดงตามรูปนี้ครับ

**Comment by nawapornmanyanon** [comment]
@warakornlj 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b84302e7-dda2-4881-a45a-c545833fa2a1)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/20083f8c-fb19-4e5d-86c9-88143203c4e2)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6877708e-60da-4048-bba0-209813c8674f)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bedbd611-2649-452c-af11-e98ec35c230b)

![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4f4a2911-be9d-4ee9-9496-ccfd3179ccee)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/93aa87e4-5b00-4c52-acad-7fbcd6ffc391)
