### ISSUE TITLE
[PMsetting][IndividualKPI] - Teammember list ไม่แสดงข้อมูล

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#639]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8ecc8544-d918-40dc-b0cf-e0a6d39d4776)

**Comment by warakornlj** [comment]
หน้า PM Setting ใช้กับการ์ด [#677](https://github.com/S4-Internal-app/Evaluated/issues/677)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/effe5d18-4a44-46ce-8cf8-299359ae538c)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/72348621-5e92-405d-9d30-609979945914)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/71c297e7-7857-414c-8608-446b59fcaa52)
