### ISSUE TITLE
[Function] - Button appear according to admin role

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#64]
ถ้า Login เป็น admin main button จะต้องขึ้นตามนี้

![Image](https://user-images.githubusercontent.com/131150937/242487918-e6339f46-b9c3-4de5-929c-b3ad1b87701c.png)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/339d5602-e04d-436b-807a-7d7b50c52244)
