### ISSUE TITLE
[PMsetting][DepartmentKPI]- Teammember list ไม่แสดงขอมูล

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#640]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/dc788a5b-2e00-49d1-af06-ad1190c4c610)

**Comment by warakornlj** [comment]
หน้า PM Setting ใช้กับการ์ด [#677](https://github.com/S4-Internal-app/Evaluated/issues/677)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/64b726e4-3a05-49fc-b92f-6673c3ecb3fb)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2ce18284-5f5c-4a05-9c1e-dea4582843e0)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/13b078ac-8de8-45c9-996d-89296f1b4f54)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8d1077a4-5c3d-4b39-91db-5f202f2c10a0)
