### ISSUE TITLE
[Administrator][Employee] - Employee list ไม่มีข้อมูลแสดง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#642]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/30ccbbae-df67-4467-a3dd-3d3df22529d3)
Expected result :
---
ระบบแสดง Employee  list

**Comment by wichita-ser** [comment]
ถ้ามีอะไรที่หลังบ้านต้องแก้ให้เพิ่ม แจ้งได้เลยนะครับ @TanawatMfec 
https://s4-test-api.mfec.dev/apidocs/#/admins/get_api_v1_admins_employees_status_duration__duration_id_

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7a3e592e-12b0-4970-8ca5-e5462429bfbe)
