### ISSUE TITLE
[Administrator][ScoreSetting] - Order garde data incorrect

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#643]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/da50f8eb-78ad-420d-9379-b00cc9614bfc)

🎈**Expect to result:**
เปลี่ยนชื่อ page เป็น Administrator
เรียงเกรด A+  , A  , B , C , D
เพิ่ม Quota
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b9d115b4-483b-4e0e-b9f2-8385953c4cb9)

**Comment by nawapornmanyanon** [comment]
😵‍💫**ข้อมูลตอน Save กับ DB ไม่เหมือนกัน**
----


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e8382bb9-6b1f-4bec-9f4f-f8f0b1b3b3d9)

**Comment by wichita-ser** [comment]
แตงรบกวนเช็คได้ไหมคะ ว่าเส้นนี้ที่ใช้อยู่เรียกเป็น API Test หรือ API Dev
@TanawatMfec 

DB Dev


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/d87fa013-5437-4a1b-98ca-a4e42e689ff7)


DB Test


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/15649a5f-d14b-4242-9cd5-54b2fb657039)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/94158ce4-4cf9-465a-9440-a9da7ea2f96d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8005cbb3-2e20-49d6-a185-94982cf78cd6)
