### ISSUE TITLE
[KPISetting][UI] - แก้ UI

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#646]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ad658679-978e-4af6-ab21-c883db64e282)
🎈Expect to result:
----------

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c126e83d-528b-437f-9f42-02f766767f1f)

**Comment by warakornlj** [comment]
ใช้รวมกับ branch 582_kpi_setting_page

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5ccb3b55-1ac8-477b-ac0e-8930cb7ddc30)

**Comment by warakornlj** [comment]
ทำอยู่ที่ Branch 737_kpisetting_fix_bug
- https://github.com/S4-Internal-app/Evaluated/issues/737

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/98305c2a-fb74-4335-a25c-35e4352fbe31)
