### ISSUE TITLE
[KPISetting][AutoScore] - เรียง Department  > Division > Department KPI และเปิด Search , filter , Download ของ Table

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#647]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/10e69958-f2cb-416f-b681-898ca7f9872f)

🎈Expect result :
----
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f7aca192-0fa6-4fe4-aef3-e504a955f985)

**Comment by warakornlj** [comment]
ใช้รวมกับ branch 582_kpi_setting_page

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/27065b63-dad2-4369-bcf5-37bafcf50c76)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d8c2c530-59f3-4f1c-82ba-c4b1f511f813)
