### ISSUE TITLE
[KPISetting] - ทำมั้ยยิง API 2 รอบ

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#648]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/47b5dacc-1de7-42f4-8f5c-b50bc4935d0f)

**Comment by warakornlj** [comment]
ใช้รวมกับ branch 582_kpi_setting_page

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/007ca035-cc13-4e43-b126-432859ce61b7)
ปิด On load page
