### ISSUE TITLE
[API][All] - Get core value score detail for dropdown list

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#649]
**Description**: Get core value score setting detail  for dropdown list

**Table**:
- score_detail
- evaluate_type

**Params**:
- year
 

**Response**:
```
{
   "core_value_score": [{
     "number": 1,
     "description": "never",
     "score": 50
   },{
     "number": 2,
     "description": "rarely",
     "score": 60
   }],
   "year": 2023
}
```

Note:
- Implement on master controller

**Comment by wichita-ser** [comment]
https://s4-dev-api.mfec.dev/apidocs/#/masters/get_api_v1_masters_score_core_value__year__detail

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6dde785e-af19-43f9-918e-4c97e762e461)
