### ISSUE TITLE
[API][All] - Get kpi score for dropdown list

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#650]
**Description**: Get kpi value score setting detail by year for dropdown list

**Table**:
- score_detail
- evaluate_type
 

**Params**:
- year

**Response**:
```
{
   "kpi_score" : [{
     "number": 1,
     "description": "below",
     "score": 80
   },{
     "number": 2,
     "description": "partially meet",
     "score": 90
   }],
   "year": 2023
}
```

Note:
- Implement on master controller

**Comment by wichita-ser** [comment]
https://s4-dev-api.mfec.dev/apidocs/#/masters/get_api_v1_masters_score_kpi__year__detail

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1a8e4b68-48b2-488a-8a34-528cb6f6b72e)
