### ISSUE TITLE
[Front-end][Home][Fixbug] - แก้บัคหน้า Home

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#652]
- https://github.com/S4-Internal-app/Evaluated/issues/637

- https://github.com/S4-Internal-app/Evaluated/issues/631

- https://github.com/S4-Internal-app/Evaluated/issues/630

- https://github.com/S4-Internal-app/Evaluated/issues/594

- https://github.com/S4-Internal-app/Evaluated/issues/638

- https://github.com/S4-Internal-app/Evaluated/issues/593

- https://github.com/S4-Internal-app/Evaluated/issues/632

- https://github.com/S4-Internal-app/Evaluated/issues/633
 
- https://github.com/S4-Internal-app/Evaluated/issues/634

- https://github.com/S4-Internal-app/Evaluated/issues/635

- https://github.com/S4-Internal-app/Evaluated/issues/636

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/546

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/666
https://github.com/S4-Internal-app/Evaluated/issues/667

**Comment by warakornlj** [comment]
07/11/23 API คงเหลือ
https://github.com/S4-Internal-app/Evaluated/issues/630
https://github.com/S4-Internal-app/Evaluated/issues/632
https://github.com/S4-Internal-app/Evaluated/issues/633
https://github.com/S4-Internal-app/Evaluated/issues/634
https://github.com/S4-Internal-app/Evaluated/issues/635
https://github.com/S4-Internal-app/Evaluated/issues/665
https://github.com/S4-Internal-app/Evaluated/issues/666
https://github.com/S4-Internal-app/Evaluated/issues/667

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/465

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/658

**Comment by warakornlj** [comment]
เหลือ https://github.com/S4-Internal-app/Evaluated/issues/486

**Comment by warakornlj** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/486 ย้ายไปเปิด branch ใหม่

**Comment by nawapornmanyanon** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705  ไป Test ต่อที่การ์ดนี้
