### ISSUE TITLE
[API][Home]{Previous] - เพิ่ม API ของ Teammemer และแก้ Key total_score

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#654]
สำหรับแสดง Teammember
เพิ่ม Key : position
แก้ total_score

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/19cc6dd7-6ca5-49fe-ab43-84f48d346124)
Expected result:
-----
KEY ที่มีคำว่า raw นำหน้า  คะแนนจะเต็ม 120   ถ้าไม่มี จะเป็น % 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f92f821d-28bb-4747-b33d-43c99ec3e7c7)

**Comment by wichita-ser** [comment]
**NOTE** : total_score มันต้องไม่เกิน 100

**Comment by wichita-ser** [comment]
เส้นใหม่ไว้ใช้หน้านี้


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/c36aa451-0d0c-46d2-b365-515426da0ea5)

ไว้แสดงเฉพาะของ team member ที่ under คนนี้เท่านั้น
ถ้าเขาเป็น admin ก็เหมือนกัน (แสดงทั้งหมดแค่ในหน้า admin report)

**Comment by nawapornmanyanon** [comment]
@wichita-ser ให้หน้าบ้านใช้เส้นนี้แทน จะได้ไม่ต้องทำใหม่


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a546aeb4-9c3e-47bb-9c47-6ca03e3007c1)

**Comment by wichita-ser** [comment]
**Note:** คุยกับพี่โจ้แล้วว่า ให้แก้ไข API เป็นดังนี้
- ให้ส่ง `is_supervisor_report=True` มาใน query params ในกรณีที่ต้องการดูแค่ของ under team member ตัวเอง

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bcee13c9-d72f-4b46-9c5e-33ea789617e0)
