### ISSUE TITLE
[Administrator][Division][Progress] - Employees list duplicate data

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#655]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a11788a6-8827-4a35-9be7-5476ff26a0f8)

**Comment by wichita-ser** [comment]
API: [GET] /api/v1/admins/evaluates/status/companies/{company_name}/divisions/{division_id}
[Swagger URL](https://s4-dev-api.mfec.dev/apidocs/#/admins/get_api_v1_admins_evaluates_status_companies__company_name__divisions__division_id_)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon check with FE

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5abb5439-056f-4411-9eb8-fe67c989b9f2)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/74c40521-66f2-44a4-b04f-375051e06b7f)
