### ISSUE TITLE
[Evaluation][Teammember] - ข้อมูล Level , KPI Supervisor , Core value Supervisor ส่งมาไม่ครบ

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#656]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/63aa5d8d-bf18-4737-9118-d1d55f0ce837)

**Comment by wichita-ser** [comment]
API: [GET] /api/v1/evaluates/supervisors/{supervisor_id}
[Swagger URL](https://s4-dev-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_supervisors__supervisor_id_)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon check with FE

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5a600b0a-3a3e-4414-83a0-13530db8d2dc)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/78308024-a746-4a75-9204-dc714a9aa8ff)
