### ISSUE TITLE
[Function] - Handle Duplicate in kpi admin add perspective

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#66]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d847308b-2dde-4df7-a638-61b0ed107779)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/005f0eb6-85e5-465e-a91d-0e7d9460c502)
