### ISSUE TITLE
[KPISetting][CorporateKPI] - Update corporate KPI ปิด coulmn : id , year_to

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#662]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/645d7671-c109-4c67-a912-a6f1b196da20)

**Comment by warakornlj** [comment]
ใช้รวมกับ branch 615_update_corporate_kpi

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e834e489-7d1b-42b2-a91d-36308c40c053)
