### ISSUE TITLE
[KPISetting][PerspectiveWeight] - หน้า Perspective List ไม่มีข้อมูลแสดง  แต่กดเข้าไปหน้า Update มีข้อมูลของ perspective

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#663]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f439c595-3fb5-455a-98bc-277c92e90cc4)

**Comment by warakornlj** [comment]
หน้า KPI List Page ใช้กับการ์ด [#582](https://github.com/S4-Internal-app/Evaluated/issues/582)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a2583788-8ce8-4f3d-8b0d-19a3c8a472e9)
