### ISSUE TITLE
[PMSetting][GoalSetting] - ไม่ข้อมูล Position ,  Level ส่งมา และ Status เป็น Null

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#664]
API: https://s4-test-api.mfec.dev/api/v1/pmSetinngs/evaluates/status/supervisors/04407

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c9eddfc0-7baa-477b-964c-79141906c71b)

Expected to
____

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/663bf0ce-1c57-4f08-a33a-91ced537f89a)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/168dce01-9fe5-45b2-b234-29aca7f6a5c6)

**Comment by wichita-ser** [comment]
@TanawatMfec 
แก้ emplotee_level เป็น employee_level ให้หน่อยค้าบ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/eb1e4964-0f02-4c97-b531-227d275f0cd5)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec 
กรณี Status : 
Pending จะใช้ตัวอักษรสีดำ
Submitted จะใช้ตัวอักษรสีเขียว


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/54e64ffe-c969-4cc7-93ec-30d34b1fadf0)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/99414b9a-020d-49c3-9fc5-c6012a51b716)
