### ISSUE TITLE
[Home][Previous][IndividualKPIreport] - Main menu ต้องเป็น Home

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#666]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/669def86-273d-4d07-93e6-3bc911297090)

**Comment by nawapornmanyanon** [comment]
@warakornlj   Main menu ต้องเป็น Home
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2c49a018-3c83-45f4-a783-5732b6d09598)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8e63ffd3-ae96-468b-9b10-4b5b69371bf0)
