### ISSUE TITLE
[Home][Previous][CoreValeReport] - กรณี Admin ต้องแสดง 6 menu และกรณี Supervisor ต้องแสดง 4 menu

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#667]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a82c5241-99ba-4ddc-b5bf-a9cfdaa5eff0)

**Comment by nawapornmanyanon** [comment]
Admin ต้องเห็น Main Manu  6 ข้อ
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7c230eb3-7595-478a-b6f5-213ec0c75d28)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/58b14f3c-3ad6-449f-91a4-f299166253f6)

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/785 ไป TEST card นี้ต่อ
