### ISSUE TITLE
[API][Summay] - Department Score tab ปรับ response + เปลี่ยน API เพราะอันปัจจะบันเป็นของ Admin

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#673]
https://s4-test-api.mfec.dev/apidocs/#/admins/get_api_v1_admins_report_scores_department_kpi_duration__duration_id_

**new response:**

```
{
    "payload": [
        {
            "duration_id": 3,
            "company": "string",
            "division": "string",
            "department": "string",
            "total": 0,
            "total_percentage": 0,
            "profitability": [{
                "corporate_kpi_name": "string",
                "department_kpi_name": "string",
                "target": "string",
                "weight": 0,
                "rating": 0,
                "score": 0
            }],
            "resource_performance": [{
                "corporate_kpi_name": "string",
                "department_kpi_name": "string",
                "target": "string",
                "weight": 0,
                "rating": 0,
                "score": 0
            }],
            "strategic_conforamnce_rating": [{
                "corporate_kpi_name": "string",
                "department_kpi_name": "string",
                "target": "string",
                "weight": 0,
                "rating": 0,
                "score": 0
            }]
        }
    ]
}
```

**Comment by wichita-ser** [comment]
**Note:**
- ในกรณีที่ Division นั้นไม่มีข้อมูลจะส่ง array เปล่าของแต่ละ perspective ให้
```
 "payload": [
        {
            "company": "string",
            "division": "string",
            "department": "string",
            "total": 0,
            "total_percentage": 0,
            "profitability": [],
            "resource_performance": [],
            "strategic_conforamnce_rating": []
        }
    ]
}
```
- ถ้า `score` เท่ากับ 0 `rating` จะเท่ากับ 0
- ถ้า filter แค่ duration (required field) เท่านั้น จะส่งของทุกๆ division ใน office_master มา

**Comment by wichita-ser** [comment]
Update: มีแก้ไขย้ายให้ filter duration_id ใน query แทน path

**Comment by wichita-ser** [comment]
🚩 **ตัวอย่าง division ที่มี data**

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9057a0ab-bcec-4e94-99dd-f0c729f60bfa)


🚩 **ตัวอย่าง division ที่ไม่มี data**


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/45a5095f-50b4-4da4-a6b6-9e31c7224cdb)




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/09603f61-5387-4ffc-815e-47f322500cd2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/485611c2-2f94-4b50-86e7-679315a36790)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9ddf5bfe-2049-4b1b-9720-10dec5db2c4a)

**Comment by wichita-ser** [comment]
Login with P'Natnaka account


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/72f9e813-9aef-4786-b7fd-a4c5d122e5af)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/ed89fe8d-3f45-4148-b65e-595efc92c8b2)

**Comment by nawapornmanyanon** [comment]
### มี Score มาให้   แต่ไม่ส่ง Rating มา  ฝากดูให้อีกหน่อย @wichita-ser 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8c6dc68d-80b2-4177-9def-66dd7c4e3bb8)

จาก DB มีข้อมูลนะ


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/334c9f46-5dcc-41bc-ba52-f49e7bc7f763)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b30e1163-e049-4d7f-870f-79c1484e4adc)

**Comment by wichita-ser** [comment]
Deploy done + dev test @nawapornmanyanon 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/d984a8ff-32e8-4a4f-953b-3243ffd63630)

**Comment by nawapornmanyanon** [comment]
มันจะมี Condition เรื่องรับ ภาพรวมด้วย  ถ้า Auto score ไหน รับภาพรวม ให้ใช่ BU00000  พี่ลืมบอกไป

@wichita-ser  @sainamphung 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/79f50f18-2888-4033-bad6-0a2102aebd6b)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bc79971e-6fa9-4174-818c-e451ed92d5e0)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/01932874-07ff-4b1e-94a2-d463687c908f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/49b1efbc-d6d0-4831-9161-32e6394b7250)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6ed95d93-e0b2-4f1f-8102-c19cc94a1ddd)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5ddfdc8-a6fe-40c1-9c82-665c60c7c623)

**Comment by nawapornmanyanon** [comment]
Admin >> Kittikun

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e223360a-d603-4f35-883e-c68370b4ed16)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ada2e338-d99e-4128-99ca-82cbd83697f1)
