### ISSUE TITLE
[API] - evaluates/report/department_kpi?employee_id&duration_id

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#674]
#592
Key กับ Value  แปลกๆ เหมือนสลับกัน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0f7049b5-3a64-4e22-a1b1-2321902253b9)

**Comment by nawapornmanyanon** [comment]
https://s4-test-api.mfec.dev/api/v1/evaluates/report/individual_kpi?employee_id=02955&duration_id=3


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6d395368-cec6-4065-b592-a6aad12ed1fa)

**Comment by wichita-ser** [comment]
@nawapornmanyanon
Backend TODO:
- Recheck การคำนวณของ total_score ต่างๆ percent จะต้องไม่เกิน 100

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ca891a33-d24b-495e-8dc4-523b4b663b1b)

**Comment by nawapornmanyanon** [comment]
คิดเฉพาะ Department KPI ถูกนะ  @wichita-ser  ถามๆ @10.00
แต่งง 
"kpi_total_score": 104.55,
"kpi_total_score_percentage": 87.12, 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d59d28d6-d378-4ce6-8581-d1d025a3f106)

**Comment by wichita-ser** [comment]
[like]  Wichita Serchuit reacted to your message:
________________________________

**Comment by wichita-ser** [comment]
detail เพิ่มเติมของเส้น department kpi และ individual kpi
https://github.com/S4-Internal-app/Evaluated/issues/592

**Comment by nawapornmanyanon** [comment]
Cal ตามนี้ OK 🎉

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/45baba6c-3c7b-4eff-80b2-60d7365a536c)

**Comment by nawapornmanyanon** [comment]
@wichita-ser @nawapornmanyanon  เด๋วรอน้องแก้ ทศนิยม จาก 87.125  เป็น 87.13  ก็เสร็จแล้ว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b234ea75-a0b3-446c-a335-2c42a7ab2ff3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5901b3d8-2117-4f5f-b3ed-c2e0b9cf81e4)
