### ISSUE TITLE
[KPIsetting][DepartmentKPI] - Department list ไม่โชว์ DATA

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#676]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/660449d9-3efe-45ab-a919-a205573d3f59)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c5267626-d478-4094-a3bd-9e328041ed21)

**Comment by warakornlj** [comment]
หน้า KPI Setting ใช้กับการ์ด https://github.com/S4-Internal-app/Evaluated/issues/582

**Comment by warakornlj** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/5893733c-d7ea-4825-a71a-f58646dc433f)

ใน Dev ใช้งานได้ครับ ติดตรง API getDepartmentKPIScoreByAdmin ส่วนนี้อาจต้องให้หลังบ้านลองช่วยดูให้ครับ

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/090333c9-f374-4ff7-a195-838df24e7606)
