### ISSUE TITLE
[UI] - Information tooltip in Home page

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#68]
![Image](https://user-images.githubusercontent.com/131150937/242554022-a72d0512-b3f6-4116-b964-52a047e47e96.png)

**Comment by nawapornmanyanon** [comment]
Goal Seeting ใช้ตามด้านล่าง

- Assign Department KPI to team members
- Create your team members' individual KPI

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/242e8937-5329-4c40-9fb4-2337fe89be20)

- Supervisor self-evaluate and evaluate your team members 
- Employees selt-evaluate

**Comment by TanawatMfec** [comment]
- Supervisor evaluate themself and their team members
- Employees evaluate themsel  

ปรับแกรมม่า

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/42df27ff-4a06-4feb-9a68-19bbe0e62013)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c034209b-6a84-4973-a9a4-61e55b97ba3e)
