### ISSUE TITLE
[PMSetting][UpdateDepartment] - Modal Department KPI  data not found

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#681]
API ไม่มี DATA ส่งมา

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/806d4408-893a-4fbe-933c-0cf9c1e5c976)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b14099b2-c5c3-44e3-b2b7-24ea0eacc6e6)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/c08bf2cb-1179-4200-962e-c52630517c2f)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/94dd451c-7cb8-4fdb-ae94-3c761c6d9fb0)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0e8d12e0-5a60-48f9-8b9d-23b54cf8f368)

**Comment by nawapornmanyanon** [comment]
### P'Arm w,j-7ho department
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/91e56626-4f82-46b4-be0e-e8149668cabf)

**Comment by nawapornmanyanon** [comment]
P'Ying  ปลอมตัวจะไม่ขึ้น Department 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6c09c0f2-42cd-407b-9403-513ad603b64b)

login ตัวเอง แสดง Department KPI   นะ @warakornlj 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/43168a24-753a-4efb-8a04-f785356a2eeb)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/133725cb-7da5-432f-a2c8-fc3204c76f5c)
 ## ปลอมตัว DATA department  , division จะไม่แสดง
