### ISSUE TITLE
[PMSetting][Detail][UpdateDepartment] - Modal : Corporate KPI , Department KPI data not found , URL_NOT_FOUND

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#683]
**Step**

1. PM setting > Overall > TANAWAT > Click Detail ( ●●● )
2. Overall > TANAWAT > Click Update Department KPI
3. Click Corporate KPI information > Modal : data not found
-----

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/01b0d309-98ed-4222-836c-38ba226c43cf)

**Comment by nawapornmanyanon** [comment]
**Step**

1. PM setting > Overall > TANAWAT > Click Detail ( ●●● )
2. Overall > TANAWAT > Click Update Department KPI
3. Click Department KPI information > Modal : data not found

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7e0e4224-e92c-406e-9ec4-8c9b357e792c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/01fe5859-703f-4aba-890b-240238c4cbf6)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d279e55f-112a-41e3-8f41-441d463ab08e)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/2f2eb1c9-694a-439b-9ba1-4b31f7b68ee4)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/6accb7a7-337f-4de5-96d2-a4297df2f11c)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/1edeb280-1df9-4bc5-9ba3-dda9fd01431c)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/2dfdd41e-a5d6-4a34-b9d4-8b9197a6c8cd)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/effd1842-9b23-49e8-b187-c25061443f86)

**Comment by nawapornmanyanon** [comment]
@warakornlj  พี่หญิงมี Role : Admin ด้วย ทำให้เห็น 107 record มั้ยหว่า
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2c06abbd-5c15-4e39-96a8-2107ade71bfe)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/38baa40b-c1cf-4981-9d8b-d79694c963ee)

**Comment by nawapornmanyanon** [comment]
Step

1. PM setting > Overall > TANAWAT > Click Detail ( ●●● )
2. Overall > TANAWAT > Click Update Individual KPI
3. Click Department KPI information > Modal : DATA เกินจาก department  ตัวเอง

![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4d1e2599-f370-42cb-92d8-a0e9b9f5c8aa)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bda4b5dd-fe83-4853-bcd6-7d0e62815733)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/531cc8c4-0d5d-486f-9ec5-8fa556b68bad)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1fedc10a-8abd-484a-a644-2642177ec02b)
