### ISSUE TITLE
[PMSetting][Detail][UpdateIndividual] - Modal : Corporate KPI , Department KPI data not found , URL_NOT_FOUND

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#684]
**Step**

1. PM setting > Click Update Individual KPI
2. 
- Click Corporate KPI information > Modal : data not found
- Click Department KPI information > Modal : data not found

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/71bb5303-983a-4b78-9ec4-9c4f30149f0e)

**Comment by nawapornmanyanon** [comment]
@warakornlj  Corporate KPI ไม่มา


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/05cabe6e-868a-4474-8f89-bb50d272e716)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ff59e0d3-6d76-4814-8ada-8c9a94afc7d6)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/167845b2-723c-43d5-9ecb-7d7105d2602b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/cc26bad1-c14c-4ce1-9aea-b682c3074822)
