### ISSUE TITLE
[Admin][Employee][Action] - Handle Monitor PM-Setting กับ check เรื่องการสวมรอย แทน employee คนนั้นๆ (ค่า employee id หรือ data ของคนที่ถูกสวมรอย ต้องส่งไปที่หลังบ้าน แทนที่ data ของเราเอง)

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#693]

**Comment by TanawatMfec** [comment]
ไฟล์นี้ใช้แสดงผล พวก ชื่อ, department, division การ navigate ปุ่ม ไปที่หน้า amin employee tab หรือ หน้า Division progress 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/e8445282-613c-4c3b-9c25-241211eb4acb)

**Comment by TanawatMfec** [comment]
ใช้ monitorEmp.isComeFromProgress ในการบ่งบอกว่า เรา กดสวมรอย มาจากหน้า Admin tab employee หรือ Division progress page   
ถ้า isComeFromProgress เป็น true แปลว่า เค้าเข้าจากหน้า Division progress 

ตัวแปรนี้เอาไปแยก พวก key ที่จะเอาไปใช้ เพราะ key ของ admin tab กับ Division page ไม่เหมือนกัน (สังเกตุ key จากรูป comment บน)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/ca23dfe1-0970-4b27-84e0-1bdf7918342c)

**Comment by TanawatMfec** [comment]
ชื้่อ Key ของ หน้า Amin tab employee กับ หน้า Division progress ต่างกัน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/ee4111cb-a2f3-4c5c-9df7-e2d417575d43)

**Comment by TanawatMfec** [comment]
อันนี้ ใช้เพื่อ กำหนดค่า Employee ID ว่า ค่านี้จะต้องเอา ค่า จากหน้า Admin employee tab หรือ Division progress มาใช้ใน API   และ ถ้าเกิดไม่ได้มีการสวมรอย หรือ remote employee จะใช้ employee id ของตัว user เอง (พี่โจ้ใช้เงื่อนไขนี้ ในการแยก ไอดีได้เลย หรือ แยก พวก data ส่วนอื่นๆ ก็น่าจะทำประมาณนี้)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/417f4a28-cdfe-49d6-afe0-1b3f6811dbf3)

**Comment by TanawatMfec** [comment]
ตัวอย่าง handle หน้า evaluation ใน init กับ settingJS

**Comment by nawapornmanyanon** [comment]
@warakornlj ตาราง Team member หาย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d9f08756-ea51-44fd-9a62-f932cf12ce90)

**Comment by nawapornmanyanon** [comment]
#### ปลอมตัวมาจาก Employee tab มันตายตรง กด update weight อ่ะ  @warakornlj 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f9703592-5dbe-41b4-83a4-d5c09baead11)

**Comment by nawapornmanyanon** [comment]
@warakornlj 

ปลอมตัวเป็นพี่นาถ จาก TAB progress แล้ว Team member หาย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a08708cc-7ac3-40dc-ac2e-b575c164e7b3)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b7ff2561-4add-48ec-b09d-a278c85f6c9c)
