### ISSUE TITLE
[PMSetting][TeamMember] - ถ้าเป็น Employee ที่ %Individual KPI = 0% ให้ใส่ Status เป็น - ได้มั้ย  USER จะได้รู้ว่า ลกน้องคนนี้ เขาไม่ Individual KPI ไม่ต้อง assignให้

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#695]
ถ้าเป็น Employee ที่ %Individual KPI = 0% ให้ใส่ Status เป็น - ได้มั้ย  USER จะได้รู้ว่า ลกน้องคนนี้ เขาไม่ Individual KPI ไม่ต้อง assignให้   เช่น  พี่นาถ  รับ Department KPI 100% เลย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/75759b72-e35e-4f51-9dad-462d8c3aa362)

**Comment by warakornlj** [comment]
API : https://s4-dev-api.mfec.dev/api/v1/pmSetinngs/evaluates/status/supervisors/{supervisor_id}

ไม่ได้ส่ง Weight ของ Department กับ Individual มาให้ครับ อาจต้องให้หลังบ้านส่งค่า Weight มาให้ด้วยครับ

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/e3881b7e-04f4-4e38-b112-1b75bdc806ff)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/e46bcf09-0a6d-4c07-8a04-adf34ace0a38)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/99ec3d37-9e7c-4a16-9785-bc25b31adbeb)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/05059f9a-8945-4e46-ab0a-070dad2f332e)
### DONE
