### ISSUE TITLE
[Administrator][Progress] - %Goal setting คำนวณไม่ถูกต้องเพราะ มี Level E ที่รับ Department KPI อย่างเดียว ร่วมอยู่ด้วย

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#697]
%Goal setting คำนวณไม่ถูกต้อง  เพราะมี Level E ที่รับแค่ department kpi
เช่น 
**Division : HR Solution Services   
มีสมาชิก  2 คน คือ** 
Phanchitar Wipatchwatee Level E  ที่รับ Department KPI เท่านั้น 
Areeya Phuphan  Level F รับทั้ง Department KPI และ Individual KPI 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f6cf2fb0-7dd9-402a-8078-f6a9e9efda1f)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1a803b1-6ecc-44fa-90f8-f36402d003da)

-----

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d8bf285a-201a-4c7c-8f82-66f00c11ed4d)

🎈Expected 
----
%Goal setting **Division : HR Solution Services   เป็น 100 % เพราะ Assign ให้ครบแล้ว
มีสมาชิก  2 คน คือ** 
Phanchitar Wipatchwatee Level E  ที่รับ Department KPI เท่านั้น 
Areeya Phuphan  Level F รับทั้ง Department KPI และ Individual KPI

**Comment by sainamphung** [comment]
โค้ดเก่าไม่ได้ filter active duration ไว้
