### ISSUE TITLE
[KPISetting][UpdateDepartmentKPI] - กรณี Weigh ใน Excel file ที่ Upload เป็น % เวลา save ลงไปใน DB มันทศนิยม

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#700]
Template: 

[Department_KPI_V1_VentureLab.csv](https://github.com/S4-Internal-app/Evaluated/files/13316678/Department_KPI_V1_VentureLab.csv)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bbd0ded4-b246-413d-9cfa-7a2bc8e1503a)

**Comment by nawapornmanyanon** [comment]
พี่ยัง Recheck ไม่ได้เพราะไม่ยอมให้ Uplode


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ffda4a59-0d4a-4197-97b4-143baadb7a37)

**Comment by warakornlj** [comment]
ตอนส่งค่า Weight ไป ผมส่งไปเป็นเลข Number นะครับ 

`{
  "add_kpi_list": [
    {
      "auto_eva_from": "NP",
      "corporate_id": 19,
      "department_id": "IN00000",
      "department_kpi_name": "KPI 1 - Net profit (NP)",
      "division_id": "IN02000",
      "measurements": "NP from Pivot reports",
      "perspective_id": 3,
      "score1": "<= 180",
      "score2": ">180 - <225",
      "score3": "22500",
      "score4": "> 225 - <270",
      "score5": ">= 270",
      "target": "225 MB",
      "weight": 70
    },
    {
      "auto_eva_from": "RUI",
      "corporate_id": 30,
      "department_id": "IN00000",
      "department_kpi_name": "KPI 6 - Resource Utilization (RUI)",
      "division_id": "IN02000",
      "measurements": "RUI  from Pivot reports",
      "perspective_id": 2,
      "score1": "<60%",
      "score2": "61",
      "score3": "75",
      "score4": "80",
      "score5": "85",
      "target": "75",
      "weight": 10
    },
    {
      "auto_eva_from": "RBI",
      "corporate_id": 25,
      "department_id": "IN00000",
      "department_kpi_name": "KPI 7 - Resource Booking (RBI)",
      "division_id": "IN02000",
      "measurements": "RBI  from Pivot reports",
      "perspective_id": 2,
      "score1": "<60%",
      "score2": "61",
      "score3": "75",
      "score4": "80",
      "score5": "85",
      "target": "75",
      "weight": 10
    },
    {
      "auto_eva_from": "STG",
      "corporate_id": 27,
      "department_id": "IN00000",
      "department_kpi_name": "KPI 8 - Strategic Conformance Ratio (STG)",
      "division_id": "IN02000",
      "measurements": "Feedback from Green team report\r\nconformance rating qualitative based on\r\n- Attempt/find potential for BU & MFEC\r\n- Made it happened (with result)\r\n- Support internal tasks",
      "perspective_id": 1,
      "score1": "-",
      "score2": "Partially Meet",
      "score3": "Meet",
      "score4": "Exceed",
      "score5": "-",
      "target": "meet target of Strategic conformance ratio",
      "weight": 10
    }
  ],
  "delete_kpi_list": [
    120,
    119,
    121
  ],
  "update_kpi_list": []
}`

พี่อุอาจจะลองเช็คกับหลังบ้านดูตอนเก็บข้อมูลครับ

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cda40f3f-edd7-4c8b-81f1-e9198b753e31)

ลงไปเป็น 100  ก่อนยังไม่สามารถเป็น 100% ได้ เพราะ App smith แปลงให้ จาก Excel file ให้เป็น TEXT หรือ GENERAL  แต่ก็ยังไม่ได้  ติดไว้ก่อน



[Department_KPI_V1_AI.csv](https://github.com/S4-Internal-app/Evaluated/files/13445982/Department_KPI_V1_AI.csv)

@nawapornmanyanon  @warakornlj @wichita-ser

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8344064f-1682-4e06-9d51-21a1e0f3a98e)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b7612bc3-3004-49c0-a75b-a3aeaa45a88c)

**Comment by nawapornmanyanon** [comment]
@warakornlj ปิดตรงนี้ให้หน่อย   >> Default appsmith จะเปิดไว้
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6cc47468-b748-4c48-8ca0-52c4b4c27150)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/51df17ce-890f-41aa-bff4-72c0a603935e)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5df3c5be-ff04-4291-9c56-166a937564fa)
