### ISSUE TITLE
[API][KPISetting][DepartmentKPI]  - api/v1/kpi/deparmentKpis/duration/3 ทำมั้ยถึง get ได้ NULL

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#702]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7ff73776-eaff-4556-8269-d77f6f729b6a)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/98cb81d9-d1d9-42bf-89af-1c43b24e0d3f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f2f83343-bb82-4333-8594-26a74b5aa41a)

**Comment by wichita-ser** [comment]
**หลังบ้าน Recheck:**
จริงๆมันมี้ข้อมูล (จากภาพ auto score) แต่ยิง GET departmentKpis เป็น null

**Comment by sainamphung** [comment]
Confirm จากหน้าบ้านแล้ว API นี้ใช้ที่ Department kpi ใน kpi setting ลองยิงแล้วมีข้อมูลกลับมา แต่มีบัคตรง division ในแต่ละ row ไม่ขึ้น

**Comment by nawapornmanyanon** [comment]
@sainamphung  ได้ Division มาแล้วนะ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/97673243-151d-471a-b4e8-19b5f0e924df)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/698445da-6ccf-4576-adc0-4a55cf9b460a)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0c3ee851-74c4-46b6-a232-1a2ac3d6166a)
