### ISSUE TITLE
[KPISetting][DepartmentKPI TAB] - Department KPI list ไม่แสดงข้อมูล DIVISION

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#703]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9624c8ee-9076-48a0-bf3c-b7016e3f2f37)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/757256fb-79b9-4cf5-9d54-be9e8a44b942)
