### ISSUE TITLE
[Front-end][Home][Fixbug] - แก้บัคหน้า Home ครั้งที่ 2

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#705]
แก้บัคหน้า Home ครั้งที่ 2

เนื่องจาก 652 แตก

**Comment by warakornlj** [comment]
- [ ] https://github.com/S4-Internal-app/Evaluated/issues/710

**Comment by nawapornmanyanon** [comment]
Fail
- https://github.com/S4-Internal-app/Evaluated/issues/486
- https://github.com/S4-Internal-app/Evaluated/issues/667 ยังไม่ได้ API เลยขัง Test ของ Sup ไม่ได้

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/735

**Comment by nawapornmanyanon** [comment]
ย้ายไป TEST - https://github.com/S4-Internal-app/Evaluated/issues/785
