### ISSUE TITLE
[API][Summary] แก้เส้น get summary by employee

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#706]
แก้ API ดังต่อไปนี้
1. [GET] ​/api​/v1​/summaries​/employees​/{employee_id}​/durationSetting​/{duration_setting_id}
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_employees__employee_id__durationSetting__duration_setting_id_

2. [GET] ​/api​/v1​/summaries​/employees​/{employee_id}​/durationSetting​/{duration_setting_id}/details
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_employees__employee_id__durationSetting__duration_setting_id__details

**DoD:**
1. เพิ่ม position ใน reponse
2. ให้ return มาให้ครบทุกคนที่อยู่ภายใต้ employee คนนั้น เช่น พี่นาท ก็ต้อง return น้องที่อยู่ใต้พี่นาททั้งหมด

**Comment by wichita-ser** [comment]
- ส่ง array เปล่าเพราะว่า employee_id = 02977 (แตง) ไม่มีคน under


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/d52486c8-b36c-482b-81a0-5b36f9203e2b)


- พี่นาท (00159) มี 18 คน



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/d5e3f10c-1651-4ff9-b17f-df1df1c1f1c9)


พี่อาม (01695) มี 10 คน (ไม่มีใต้ลงไปอีกที เช่น ไม่มีน้องใต้พี่นาท)
❓**question:** ขอคอนเฟิร์มหน่อยค่า เหมือนจำได้ว่าเคยมีคุยกันระหว่างฟลุ๊คกับพี่อุ ว่าให้ปรับเป็นแบบนี้ (ไม่ชัวร์)

**Comment by wichita-ser** [comment]
**Answer:**

เส้น detail ต้องเอาทุกคนทั้งหมดที่ under เช่น ถ้าใช้รหัสพี่อามต้องได้มา 75 คน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/00dfe3b1-6ac2-4ba7-b498-483a7264824e)
