### ISSUE TITLE
[Evaluation][Self-CoreValue] - กด Submit Core value แล้ว URL_NOT_FOUND

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#707]
Step
1. Login : Natthida
2. Evaluation menu > Self core value
3. Evaluate core value > Save > Submit

**message :  "URL Not found"**

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/93bdd8e3-2156-4883-a94b-efbc18faba2d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5811046-983c-4411-9b88-407336c6c123)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec   
total percentage  คำนวณผิด  ต้องได้ 72.5 
แสดงทศนิยม 1 ตำแหน่ง 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1df56603-555f-4429-b3cc-39611b9dece6)

**Comment by TanawatMfec** [comment]
status api หลังบ้านไม่เปลี่ยน เลยไม่เปลี่ยนสีปุ่ม รอแก้ update corevalue

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/525ddd1d-ef63-42c1-b5a2-8a8d29e2e20e)

**Comment by nawapornmanyanon** [comment]
@wichita-ser  เส้น Update core value

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3845077e-f0ca-47fb-b99f-517063c18961)

**Comment by wichita-ser** [comment]
@TanawatMfec ใช่เส้นนี้ใช่มั้ย https://s4-test-api.mfec.dev/apidocs/#/evaluate/post_api_v1_evaluates_core_value_update_score
ถ้าใช่ ขอดู request body ครับ

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ec23533a-a8db-4736-a5ce-06b0b74a3009)

@TanawatMfec  @wichita-ser  ใครแก้ไรมั้ย ตนแรกมันได้

**Comment by wichita-ser** [comment]
ม่ายได้แก้

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c2941773-1d96-4003-9cfe-ba8b7c3b46a9)
![screencapture-s4-dev-mpulse-mfec-dev-2023-11-22-15_28_26](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d7db4d7e-ccee-4ed3-8206-18f3385dca8c)
