### ISSUE TITLE
[Home][AdminReport][SummaryReport] - Column : Supervisor score ต้องเป็นคะแนนจาก Rating x weight

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#709]
Department KPI
----
Column : Supervisor score ต้องเป็นคะแนนจาก Rating x weight
Supervisor score , total score , total percentage  แสดงทศนิยม 1 ตน.
ให้เรียงลำดับ ตามชื่อ Department KPI
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/efbf0df7-3faa-4bb8-b3ff-755034b501e7)

**Comment by nawapornmanyanon** [comment]
Core value
----
Column : Supervisor score ต้องเป็นคะแนนจาก Rating x weight
Supervisor score , total score , total percentage  แสดงทศนิยม 1 ตน.


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d5df9cd9-4c42-4b89-bbdb-be2bd46e1ee2)

**Comment by nawapornmanyanon** [comment]
ทศนิยม 1 ตำแหน่ง


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/aa8c54bf-9857-4c36-89d0-71283ad3658c)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/16cc9b6c-e336-435c-b069-0554e174e1af)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b21e19c6-4057-40e6-81aa-588a9583862b)

**Comment by nawapornmanyanon** [comment]
@warakornlj  Core value Fail!!
----
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6046621c-abf7-43db-9a5e-575771dabec0)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f812ea4e-dac7-43a0-afc9-08588cf98367)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/edce3bef-a74b-4423-80b8-1c1e5fa32214)

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/785 ไป TEST CARD นี้
