### ISSUE TITLE
[Home][AdminReport][DepartmentKPIReport_Detail] - Detail department KPI report  จำนวนข้อแสดงเกิน , ข้อไม่เรียงลำดับ KPI 1 - 6 , Detail แต่ละข้อไม้แสดงข้อมูล

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#710]
Detail department KPI report  จำนวนข้อแสดงเกิน , ข้อไม่เรียงลำดับ KPI 1 - 6 , Detail แต่ละข้อไม้แสดงข้อมูล

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/274bf5f1-e5fe-4a0c-a6f4-f684f1b44fa7)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a3eb642a-da12-4d69-9faa-88e5e101b281)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5316bdca-8b7d-4fb4-ad64-42526aeba2a4)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5755fdf5-e506-46dc-9a56-0b4e0bd6a881)

**Comment by nawapornmanyanon** [comment]
@warakornlj เรียงตามชื่อ Department KPI name ให้หน่อย
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1be65cd-782f-4b60-b091-59b3ef9995ab)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a16ee58d-64e8-4010-afe1-e62d1702c8bd)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/68d56729-c162-4a58-9219-78fa118e656e)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/66c8f4c5-3480-4085-8569-4aef0c7a453b)
