### ISSUE TITLE
[Home][AdminReport][IndividualKPIReport_Detail] - Detail Individual KPI report  จำนวนข้อแสดงเกิน , ข้อไม่เรียงลำดับตามชื่อ KPI, แต่ละข้อไม่แสดง Score และ Comment ,  Detail แต่ละข้อไม้แสดงข้อมูล

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#711]
[Home][AdminReport][IndividualKPIReport_Detail] - Detail Individual KPI report  จำนวนข้อแสดงเกิน , ข้อไม่เรียงลำดับตามชื่อ KPI, แต่ละข้อไม่แสดง Score และ Comment ,  Detail แต่ละข้อไม้แสดงข้อมูล

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/029dc9c6-b05b-4c44-95fc-7d451a3909fe)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/67c9950e-8140-4820-ab78-a68ee88ddf11)

**Comment by nawapornmanyanon** [comment]
@warakornlj ขาด Perspective 
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9324a736-8580-492c-a5be-dce00b299fe9)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/72531d0d-352a-4c38-b149-4dc736710435)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/87d2e946-473f-45db-bfe1-7c2cfee104a0)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fe9f319b-7360-4b79-b26e-5b7ab1b7b027)
