### ISSUE TITLE
[Summary][ScoreReport] - DATA และ Chart ไม่แสดง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#715]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c5b10d08-f597-4fd3-b0c6-19f543355c78)

**Comment by warakornlj** [comment]
ทำที่ https://github.com/S4-Internal-app/Evaluated/issues/717

**Comment by nawapornmanyanon** [comment]
@warakornlj 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/27c79ec3-9efb-4232-b83e-669416216f46)

**Comment by warakornlj** [comment]
ทำที่ https://github.com/S4-Internal-app/Evaluated/issues/717

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b2d8a3d0-8a13-445f-afef-66bbfed001ed)
