### ISSUE TITLE
[Summary][GradeReport] - DATA และ Chart ไม่แสดง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#716]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2552f9b1-9264-4982-bcdd-da7e5df482c5)

**Comment by warakornlj** [comment]
ทำที่ https://github.com/S4-Internal-app/Evaluated/issues/717

**Comment by nawapornmanyanon** [comment]
Data ยังไม่มา

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7eb0b13f-f7f5-4385-b711-114fe4442c07)

**Comment by nawapornmanyanon** [comment]
ย้ายไป TEST ต่อ 
- #717
