### ISSUE TITLE
[Admin][Employee] -DeActive or InActive แล้ว table ต้องอัพเดทค่าด้วย

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#719]

**Comment by nawapornmanyanon** [comment]
กด Deactivate  แล้ว  Column : Supervisor core value evaluation ต้องเป็นค่าป่ะ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3c1dc659-22c3-4638-933e-ba1c77a545a6)

**Comment by wichita-ser** [comment]
REF API: https://github.com/S4-Internal-app/Evaluated/issues/540

**Comment by sainamphung** [comment]
REF API: #541
