### ISSUE TITLE
[KPISetting][ScoreByAdmin][Update] - Dropdown :  Department KPI มีข้อมูลของ division มาให้เลือกด้วย

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#722]
Dropdown : Department KPI ควรมีแต่ข้อมูล department แสดง

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0f487994-1c19-400a-b686-26308a866b5a)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/efe1911f-8f24-4c33-a897-3b5e5f514c5b)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/75524c83-5173-419a-ba60-bf3a13af6a73)

API ตัวนี้ส่ง Division มาด้วยครับ

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e6976144-c98a-4cf5-9144-ef4f87169380)

@sainamphung

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/5ea670cd-4cbc-4450-a9c6-21d539414121)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/2e319b75-d442-4dcc-8c99-cb39349c45ae)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/039f67e4-8775-4fc5-b0e0-13ff8a2ae0f6)
