### ISSUE TITLE
[KPISetting][Department][Update] - Dropdown : Department KPI มีข้อมูลของ division มาให้เลือก

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#723]
Dropdown : Department KPI ต้องไม่มีมีข้อมูลของ division มาให้เลือก

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c077f221-cdcb-4fb7-8ddd-035b9cadfbbd)

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/66564ace-83bd-4d26-987a-30bf68ff85b1)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/5ea670cd-4cbc-4450-a9c6-21d539414121)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/2e319b75-d442-4dcc-8c99-cb39349c45ae)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4403c647-b384-4a64-b0b2-d1b108854c60)
