### ISSUE TITLE
[Evaluate][Self-CoreValue] - เมื่อกดทำCore value ข้อ 4 ถูกเลือกไว้แล้ว

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#730]
กรณี Employee กดทำ core value ทุกข้อต้องยังเป็นค่าว่าง

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8f05d61d-a84d-4ef4-82ea-449500b757f8)
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b34e193a-70a6-49dd-8c98-90f9af34d786)

**Comment by TanawatMfec** [comment]
อันนี้เป็นบัคที่ user นี้น่าจะเคยทำไปก่อนหน้านี้ ปกติจะไม่มี default (เลขในภาพมาจากหลังบ้าน)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/24cd575b-f1b5-4fc9-a73b-592ae91b4324)
