### ISSUE TITLE
[Home][Previous] - กรณี round นั้นๆ Employee ไม่มี Individual KPI จะต้องไม่แสดง และ Column ของ Team เรียงลำดับไม่ถูก ขาด column %Core value ไป

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#735]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d2fe95bc-1885-4fba-ab27-e82bbf03a036)

**Comment by warakornlj** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/705

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/06bd8745-8f5f-4235-af26-4c292a477d5e)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6342ecef-82ee-46ee-8231-1796fc59aaa5)
