### ISSUE TITLE
[Front-end][KPISetting] - แก้บัคหน้า KPI Setting

### ISSUE THREAD

**Issue by warakornlj** [S4-Internal-app/Evaluated#737]
- https://github.com/S4-Internal-app/Evaluated/issues/646
- https://github.com/S4-Internal-app/Evaluated/issues/723
- https://github.com/S4-Internal-app/Evaluated/issues/722
- https://github.com/S4-Internal-app/Evaluated/issues/620
- https://github.com/S4-Internal-app/Evaluated/issues/700
- https://github.com/S4-Internal-app/Evaluated/issues/591
- https://github.com/S4-Internal-app/Evaluated/issues/615
- https://github.com/S4-Internal-app/Evaluated/issues/582
- https://github.com/S4-Internal-app/Evaluated/issues/600

**Comment by warakornlj** [comment]
แก้ Score by admin เป็นเลข 1-5 จากเดิมเป็น
{
  "department_kpi_score_list": [
    {
      "rating": 120,
      "year_to_department_kpi_id": 50
    },
    {
      "rating": 90,
      "year_to_department_kpi_id": 63
    }
  ],
  "division_id": "IN03000",
  "duration_id": 60
}
 

จะแก้เป็น 
{
  "department_kpi_score_list": [
    {
      "rating": 5,
      "year_to_department_kpi_id": 50
    },
    {
      "rating": 2,
      "year_to_department_kpi_id": 63
    }
  ],
  "division_id": "IN03000",
  "duration_id": 60
}

**Comment by warakornlj** [comment]
แก้ Score by admin เป็นเลข 1-5 จากเดิมเป็น เคลีย

**Comment by nawapornmanyanon** [comment]
Fail   >>> @warakornlj 
-----

- https://github.com/S4-Internal-app/Evaluated/issues/600
- https://github.com/S4-Internal-app/Evaluated/issues/722
- https://github.com/S4-Internal-app/Evaluated/issues/723

**Comment by nawapornmanyanon** [comment]
@warakornlj 
### Update Department KPI 
ปรับให้เป็น Insensitive ให้หน่อย ไม่สนตัวเล็ก - ใหญ่  ขอแค่ เหมือนกัน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f0bd5a49-b885-454d-b8f7-8a60fd7257f8)

**Comment by nawapornmanyanon** [comment]
Target มันควรจะลงไปเป็น TEXT เลยไม่น่าต้องไปตัด % ออก 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/de142360-c0cb-4daf-aed6-2d31db1f23df)

ไปปิดตาม Card - https://github.com/S4-Internal-app/Evaluated/issues/700  ก็จะได้

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/faae40c6-dd61-45df-a976-18dfb01b9d89)
