### ISSUE TITLE
[Evaluation] - เอากด team member ที่ Row ออก ให้กดปุ่ม ไอค่อนแทน - Recheck bug สวมรอย พี่เพรียว แต่ทำแล้ว ไปเข้าของพี่อุแทน

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#738]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/af77f639-1d96-4ab8-a2e1-edae9b156225)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/36568df4-32a7-4af6-8e93-8065ea69f90c)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/96e20322-674a-403f-8644-2af8547d0b95)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/94898803-659f-4d4f-ab17-6b2af26a7422)
