### ISSUE TITLE
[Query] - Add new department KPI to DB

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#74]
Insert new department KPI to DB
เชคว่าถ้า department KPI มีชื่อเหมือนกับที่มีในอยู่ในตาราง ให้ update รายละเอียดของ department KPI ชื่อนั้นในปีนั้น

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ffd66deb-6d77-4198-8ef8-b554a18d6f2a)
