### ISSUE TITLE
[Evaluation][TeamMember] - กรณี Supervisor กดเข้ามาประเมินให้ Team members  Department KPI evaluation จะถูก Evaluate ให้เลย  ปุ่มต้องเปลี่ยนเป็นสีขาว พร้อมแสดง icon ว่า submitted แล้ว  Column Your rating , Your Score ต้องแสดงข้อมูล โดยแสดงทศนิยม 1 ตน.

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#744]
กรณี Supervisor กดเข้ามาประเมินให้ Team members 
Department KPI evaluation จะถูก Evaluate ให้เลย
-  ปุ่มต้องเปลี่ยนเป็นสีขาว พร้อมแสดง icon ว่า submitted แล้ว 
- Column Your rating , Your Score ต้องแสดงข้อมูลโดยแสดงทศนิยม 1 ตน.

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/aa14456d-f274-4989-a545-01562d61a8dc)

**Comment by TanawatMfec** [comment]
ข้อมูลในตาราง กับ โชว icon + btn color เดียว หลังบ้านแก้ให้

**Comment by TanawatMfec** [comment]
มีแก้ พวกสี btn ด้านบน เพิ่ม

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1717c74b-4e13-45e6-8fa5-882815f68d9f)
