### ISSUE TITLE
[Evaluation][TeamMember] - Table ของ Core value ไม่แสดงข้อมูล

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#745]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7d5c1bb5-36f0-427f-8981-b4aa11c12c19)

**Comment by TanawatMfec** [comment]
ไม่มี data มา จาก API core_value_list (เป็น Array เปล่า) @nawapornmanyanon  @wichita-ser

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b5ce4405-9f3d-409d-9cd4-35097ed5dba9)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9f231a49-dfde-4887-8b07-54a30459f56a)
