### ISSUE TITLE
[Query] - Edit, delete department KPI in DB

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#75]
- Update department KPI after click save button
- Delete department KPI after click save button

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d91b4567-4e41-4293-8b34-274b65e23de6)

**Comment by nawapornmanyanon** [comment]
Phase 1 ตัด Edit ออกก่อน
