### ISSUE TITLE
[API][IndividualKPI] - evaluates/report/individual_kpi , Data order by Individual KPI name

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#751]
เรียง DATA ตามชื่อ Individual name ให้หน่อย
https://s4-test-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_report_individual_kpi

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/117eafad-1cb3-4b4f-b665-55d100dae8a2)

**Comment by sainamphung** [comment]
ตรงนี้มีผลทำให้ https://s4-test-api.mfec.dev/apidocs/#/evaluate/get_api_v1_evaluates_report_department_kpi
เรียงตามชื่อ department KPI name ด้วย
