### ISSUE TITLE
[Evaluation][Supervisor][Department Table] - เปลี่ยนเส้น API โดยใช้ performance API

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#755]
https://github.com/S4-Internal-app/Evaluated/issues/733

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4bbe2846-ef17-4b2e-9bc5-56067203428f)
