### ISSUE TITLE
[Evaluation][Corevalue][Redirect] - หลังกดปุ่ม submit ต้องไปหน้า ....

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#756]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/89fe1c21-78ac-45ee-bb45-fea7addb0a09)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/c64b6c97-5aa1-42cc-89f9-7ce0eb04742e)

**Comment by TanawatMfec** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/56796dae-8770-45ef-88ce-7c9be7981f44)

**Comment by TanawatMfec** [comment]
ข้อความสีแดง check ทุกจุด ทั้ง flow evaluation

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/202cdc82-c283-4db9-90c0-70571414cddb)
