### ISSUE TITLE
[Evaluation][Self-eva][Department] - ใช้ performance แทน

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#757]

**Comment by TanawatMfec** [comment]
test ทั้งหน้า table กับ หน้า ข้างใน ตอนทำ evaluate (Modal summary)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec  @nawapornmanyanon   ยังไม่ได้ทำ  แต่กดเข้าไปมาขึ้นว่าทำแล้ว



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/665ea517-c4fc-4c97-8f35-3023c82619da)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/48f6d335-0299-4747-8a96-268b7f4dfbfa)

**Comment by nawapornmanyanon** [comment]
ใช้เป็น API Score report แทน @TanawatMfec   ที่คุยเมื่อเช้า

**Comment by TanawatMfec** [comment]
พี่แตง อัพ API น่าจะใช้ได้เลย

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/226da4ec-7ebb-4879-99ca-6b7db54b6855)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0868a848-8cc8-4967-a27d-205e2c857386)
