### ISSUE TITLE
[Evaluation][TeamMember] - กรณี Supervisor ประเมินcore value ให้น้องๆตัวเองต้องได้รายละเอียดตามรูป

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#760]
Step
1. Login > Supervisor: Chonpicha 
2. Click team member : Chatsama
3. Click Core value จากปุ่มด้านบน
4. ระบบเปิดให้ประเมิน core value ของ Chatsama > กด Save > กด Submit
5. ระบบเปิดมาหน้า Summary เดิม

คะแนนสรุปของ core value แสดงถูกต้อง 50%
Your rating แสดงถูก 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9cde989e-639f-4034-b7d2-2f1611bd7afe)

FIX
----

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c42d3fdc-3717-4c66-92e9-5daec1b7dc2a)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b4248568-35d9-4371-87ef-129fb9f827a4)

**Comment by wichita-ser** [comment]
@TanawatMfec  
![Screenshot 2023-11-25 211524](https://github.com/S4-Internal-app/Evaluated/assets/126653943/bda8abbc-08bd-4a9e-acaa-024c266ccbda)

**Comment by wichita-ser** [comment]
Note: ส่ง weight ใน reponse body  เพิ่ม

**Comment by wichita-ser** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/04e7eecc-5de1-4b65-bda0-4a1b2b50408d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/75af4bfd-0607-45f6-bd0a-0813beb779c5)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6873d8fa-9eaf-4e90-944f-25cd3a32e42d)
