### ISSUE TITLE
[Evaluation][Core_Value] - ปรับ status กระทบการแสดงผล ว่าทำแล้ว หรือยังไม่ได้ทำ - ปุ่ม, สีปุ้ม , icon , etc..

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#762]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/af426052-50c9-45ed-86b2-0e5396ad83a7)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2683d151-d820-4136-9a74-b8e04d39afb7)
