### ISSUE TITLE
[Evaluation][CoreValue] - disable ปุ่ม บัคข้อ 7 ยังไม่ได้ทำ แต่ปุ่ม มันโชว

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#768]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5b461454-f8f9-4beb-a397-fe3ae634fbd0)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cf4bca61-975a-4d6d-a926-d911d8228bbe)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/509ad675-2d49-4018-9de1-48a9174cb2dd)
