### ISSUE TITLE
[Script] - create script Add data GRADE , SCORE , QUOTA ลง DB

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#794]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fa48e027-1a9c-4419-9a5d-1a61b886941b)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0208d4f0-d947-474f-acee-a94f894dc364)

**Comment by sainamphung** [comment]
เหลือลองเทส run บน db ที่จำลองมาจาก prod

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/acde9b11-507f-4591-8632-1e73c28d2854)
