### ISSUE TITLE
[Evaluation][KPIEvaluate] - KPI evalution ทำครบแล้ว  แต่ status เป็น Pending อยู่

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#795]
### Department  KPI = Submitted

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e507da4c-a9ac-4996-9373-ecb492778aad)

#### Individual KPI = Submitted

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ba3e61e6-7c1e-4c86-b8cf-738500db6e07)

---------------------
แต่ Staus รวมเป็น Pending

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/75c2a352-7017-4f87-ab18-e3c9fd66fc2a)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5b955654-0b5a-47e6-b453-bdc6422333bf)

##Expect to
----
Status >>> Submitted เป็นปุ่มสีขาว

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/06fa6306-cc9d-4c70-a424-52984c70f065)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/77ae9b90-16f3-48df-bf43-5dceb6fee622)

**Comment by nawapornmanyanon** [comment]
### P'NAT  level E  มีแค่ Department KPI



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/98162bac-a83d-4b90-a0cc-7b7b3cd0ef53)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a7545c84-73be-4602-beee-41abd7dde9cd)

### P'Ying Level E  มีแค่ Department KPI

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a6d1f6cd-a412-4aac-9296-ce872c3add3f)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/40fa027b-0a64-4e6f-9b76-07280126515e)

**Comment by nawapornmanyanon** [comment]
Self - Evalution
- ได้รับ Department KPI อย่างเดียว
- ได้รับ Department KPI และ Individual KPI

🐛 คนที่ได้รับ 2 type  ถ้าทำ 1 Type จะถือว่า Submited 
( ข้อมูลเพิ่มเติม เหมือนหลังบ้านจะมองว่าถ้าคะแนนมากกว่า 0 จะถือว่า Submitted  )  @nawapornmanyanon

**Comment by wichita-ser** [comment]
## Dev Test:

### P'Ying
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9666b73f-9797-44aa-8839-d7bea3a970ff)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/92e21146-92d8-4717-a81e-b4b9c02e2000)


### P'Nat
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/04209102-7c61-47cc-9ba2-5b7d26f6231d)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/a2796067-768b-4e3d-8b97-93495ea24732)


### P'Kittikun
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/a16ffc88-d7d4-485a-a0ce-dc128cf9e7a3)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/e0a5f92a-089e-4d45-ba9d-9bbec041e234)


### P'Uraporn
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/06b599a5-4ccf-41be-8bca-93299d815326)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/fff0ed90-68aa-46fe-b512-828438223221)
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/32709c4d-ccf0-46cd-b026-9840660a2929)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7abb6c28-7b22-4766-b38f-6e1a9961d977)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8eace56c-4fe1-4a1a-ab4f-f676b3790a0b)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/aa375a8f-6bca-4b42-96af-8656b8723db0)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ed36886a-6c50-4b98-bc14-235189aeda07)
