### ISSUE TITLE
[Evaluation][KPIEvluate] - คำนวณ Score ให้หน่อย

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#797]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/85f48001-35d0-4606-84b0-2af6503d858f)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1ac62f4c-191e-455e-b2a6-5a249e13cdf9)

**Comment by wichita-ser** [comment]
Dev Test:

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/5c92a201-523d-4946-8639-061cd560d4c1)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/7a3d2b77-628f-4ad7-8fcd-6ef791c56394)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bbad47e2-95c5-47f5-a165-37f96a698464)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2efb05a6-8038-419b-be8a-92f865010500)
