### ISSUE TITLE
[API][Evaluation][Summary] - ปัดทศนิยมให้เป็น 2 ตน.

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#799]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/680ccd45-dd66-4243-891f-b74abdf70eea)

**Comment by wichita-ser** [comment]
Dev Test:

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/264e51bf-c391-4c03-8726-612946a9b164)
