### ISSUE TITLE
[UI] - Add engagement survey question

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#80]
### **เพิ่มคำถาม Engagement อีก 6 ข้อ ข้อสุดท้ายเป็นข้อเขียน ไม่บังคับตอบ**

1.ปัจจุบันคุณคิดว่าการประชุมในองค์กรไม่มีประสิทธิภาพ เป็นเรื่องที่ทำให้เสียเวลา และทรัพยากรที่มีค่า เป็นปัญหาที่ต้องได้รับการเปลี่ยนแปลง

2.องค์กรสร้างช่องทางการสื่อสารที่มีคุณภาพให้กับคุณ ทำให้คุณไม่พลาดทุกข่าวสาร และข้อมูลที่เป็นประโยชน์ต่อการใช้ชีวิตใน MFEC 

3.คุณมีโอกาสที่จะทำงานที่หลากหลาย กับเพื่อนร่วมงานในแผนกอื่น ๆ มากขึ้น 

4.คุณพอใจกับการสื่อสารภายในองค์กรที่ทุกคนสามารถติดต่อสื่อสารกันได้ง่ายไม่มีลำดับขั้นซับซ้อน (Communication flow) และแบ่งปันทรัพยากรภายในองค์กรกันได้อย่างง่ายดาย (Resource sharing)

5.คุณได้รับข้อมูลเกี่ยวกับวิสัยทัศน์ (Vision ),พันธกิจ (Mission )และเป้าหมายขององค์กรได้ไม่ยาก 

6.ข้อเสนอแนะเพิ่มเติมว่าองค์กรควรปรับปรุงการสื่อสารภายในให้ทุกคนเข้าถึงการสื่อสารอย่างมีคุณภาพได้อย่างไร (ข้อเขียน)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ab958b8f-da94-4bdf-b3f7-cf877c8b44ee)
