### ISSUE TITLE
[Evaluation][Engagement] - กรณีปิดหน้า Engagement  ค้างไว้เกิน 1 ชม. แล้ว USER มาทำ สามารถทำได้แต่ระบบไม่ save ลง DB

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#803]
Step
1. กดเข้ามาทำ Engagement 
2. เปิดหน้านี้ทิ้งไว้เกิน 1 ชม. แล้วกดทำ Engagement
3. ระบบกด Sutmit ได้ status เปลี่ยน 
4. กดเข้ามาดูที่ทำไว้อีกที  ข้อมูลที่เคยประเมินไว้ไม่เสร็จ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cdf51688-c674-4961-bd1d-b54822a057cc)

**Comment by TanawatMfec** [comment]
เกิดจาก error exception คนละตัวกับ API

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/503aaf71-6d3c-4433-9235-79e30cc664e7)
