### ISSUE TITLE
[API][Evaluation] แสดง summary score ผิด

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#808]
จาก API เส้นนี้ https://github.com/S4-Internal-app/Evaluated/issues/504
ตอนนี้แสดง score ไม่ถูกต้อง

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/1be59854-60b1-4ce5-b322-b2379e363568)

**Comment by wichita-ser** [comment]
## Dev Test
### Case 1:
สมมติว่าแตงคือคนเก่ง ได้คะแนนเต็มหมดเลย ยกเว้น department kpi 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/baa50158-2bdd-471f-9e09-5bdba2ca389d)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/56de93af-3672-43b9-a429-ed89eafdeb3b)


### Case 2:
น้องพลอยยังไม่ได้ทำ department kpi, individual kpi ของตัวเอง
แต่ว่า sup ทำแล้ว



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9744dd7c-b81d-4903-b6d8-e5b939035f77)
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/b5e6d5dd-f99e-4f59-b83c-792ee41c8a00)
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/1e8d4263-97c0-44d4-96be-a0f20d7f918e)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d76a4fd4-72bb-4815-9438-ca78731d97bc)
