### ISSUE TITLE
[PMSetting] - กรณี Delete departments KPI และ Individual KPI ที่ Assign ไว้ status หน้า PM setting ไม่ถูก refresh กลับมาเป็น Pending

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#813]
Step
1. PM setting >> Goal setting > > Overall >> Select Employee  >> Click Detail
2. Click Update department KPI >> Delete All >> save
3. Click Update individual  KPI >> Delete All >> save

ฺBack to PM setting  >> Recheck Status  

Status ยังเป็น Submitted
### Expect to result : Status เปลี่ยนกลับมาเป็น  Pending

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/eecab5f7-9886-4695-a842-8baf5866b131)

**Comment by warakornlj** [comment]
@sainamphung  ผึ้งอันนี้ค่าที่ Return API หลังจากลบไปแล้วมันยัง Return  เป็น Submitted อยุ่ครับ



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/851b3c82-1149-4795-afdb-f08ef068e22f)

**Comment by sainamphung** [comment]
เกิดจาก code ไม่ได้ดัก duration ที่ active ไว้
