### ISSUE TITLE
[Home][Previous][Teammember] - Summary report กรณีไม่มี Individual  ต้องไม่แสดง ตาราง Individual , Ordre ตาราง core value

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#816]
Summary ของตัวเอง และ Teammember ถ้าไม่มี Individual ให้ปิด ตาราง Individual ด้วย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4f45fdc6-b250-4644-abb5-1d973b005ee8)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8fef3c95-b92c-4a89-86f0-2fc9b1156794)

**Comment by warakornlj** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/4ffa5ea4-ef01-4b10-b6a6-21c94fb9955f)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/467a2b6e-161b-43d0-8ee6-959a4bf9f9b5)

**Comment by nawapornmanyanon** [comment]
BUG อีกตัวไป TEST ต่อ https://github.com/S4-Internal-app/Evaluated/issues/877
