### ISSUE TITLE
Total score ไม่อยู่ใน range ที่จะถูกตัดเกรด ทำให้ไม่สามารถดึง grade id มาได้

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#817]
grade range ของเรามันเป็นงี้ 
- C 79.9 - 75.0
- D 74.9 - 0.0
แล้วทีนี้คะแนนรวมของ emp มันเป็น 74.91 อ่ะค่ะ มันไม่อยู่ใน range ไหนเลย ทำให้ grade มาเป็น null เราจะแก้ไขเรื่องนี้ยังไงดีคะ
ตอนนี้ที่คิดออกคือ
1. ตัดคะแนนรวมของ emp ให้เป็น 1 ตำแหน่ง(จะปัดทิ้งหมด หรือปัดตามหลักคณิตศาสตร์เดี๋ยวว่ากันอีกที) แล้วค่อยเอาไปเทียบเกรด
2. เพิ่ม grade range ให้เป็น 2 ตำแหน่ง ก็จะออกมาหน้าตาประมาณนี้ 
- C 79.99 - 75.00
- D 74.99 - 0.00

**Comment by nawapornmanyanon** [comment]
ตอนนี้ ให้หน้าบ้านทำเป็น 2 ตำแหน่ง หลังบ้านจะได้เอาไปตัดเกรดได้

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5561545b-63f9-4b4f-9478-9484441c55b5)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a0e45a1a-9326-43a3-af76-01970b072640)
