### ISSUE TITLE
[API][Summary] - แก้การแสดง department kpi score ถ้าไม่มี kpi detail score ก็ไม่ต้องส่งไป

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#818]
ตอนนี้ department kpi score ใน tab ซึ่งอยู่ในหน้า summary
- score report 
- grade report
- 9 boxes grid
- score compare report

ถ้ายังไม่มี department kpi ใน kpi_evaluate_detail ก็จะส่ง auto score มาแสดงแทน (คะแนน default)

**Expected**
department kpi score เป็น 0

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/4c9febc4-176e-4188-aed3-6964d7fc4c53)

Note:
ดูตัวอย่างโค้ดได้จากโค้ดพี่ผึ้งใน summary tab Summary

**Comment by wichita-ser** [comment]
**API**
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_report_scores_durations
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_report_grade
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_report_nine_boxes_grid
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_report_scores_department_kpi
https://s4-test-api.mfec.dev/apidocs/#/summary/get_api_v1_summaries_report_scores_percentage

**Comment by wichita-ser** [comment]
wating for https://github.com/S4-Internal-app/Evaluated/issues/821 done

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/56fc0fb9-e62f-474f-b118-463cf1620e2a)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/af95b4d0-80cc-48ea-8181-b107443c9fde)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f596a699-719e-4d71-971c-10ad27a314a7)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/93ae195d-757a-4283-86d0-b0ae2322af0d)
