### ISSUE TITLE
[API][Summary] - Summary grade report duplicate data

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#819]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/57817f58-9066-4712-af1e-77f72c4560b1)

**Comment by wichita-ser** [comment]
SQL check data

```
SELECT
	COUNT(employee_id) AS count_emp,
	employee_id,
	kpi_evaluate_id
FROM public.employee_grade
WHERE duration_id = 4 
GROUP BY employee_id, kpi_evaluate_id
ORDER BY count_emp desc, employee_id asc
```

**Comment by wichita-ser** [comment]
**Dev Test:**

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9b4d2d05-21be-49b7-bf02-26c9204783a1)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/01cfa820-0b84-4134-9916-bbf79f443499)
