### ISSUE TITLE
[UI] กรณี edit แล้วไปกดเมนูข้างๆ เราควรดักไว้มั้ย ว่าจะออกจากหน้านี้ แน่ใจนะ

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#82]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e24c5fdc-e5d6-4e71-aa22-1dfccf01406e)

**Comment by sainamphung** [comment]
ทำด้วยค่ะ
