### ISSUE TITLE
[Admin][Create-duration] - ส่ง duration id หลัง create ไปที่ API dup

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#824]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c9b7ecb7-242e-43a8-ba78-7e9a7d052675)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0a504491-f80b-4453-8e27-945e5baaaee1)
