### ISSUE TITLE
[API] Fix bug ดักแก้ calculate เส้น performance score error

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#826]
ต้อง handle None ด้วย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/0ad71542-c35c-4e21-96ea-da90c3efd49c)

DoD:
- จะต้องเข้าหน้า department kpi evaluate ของพี่เพียวได้ ทั้ง Flow self และ sup @UAT

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f5f5a6f1-e5d8-4b34-8039-72a7cb902a61)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d4d4bdba-eb0c-46ed-bfc3-f5edcd1f06be)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d4967aa6-2c42-40cc-9137-81ea4e6d52ef)
