### ISSUE TITLE
[DB] แก้ไขให้ score มี default เท่ากับ 0

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#827]

**Comment by wichita-ser** [comment]
**Dev Test:**

หลังจากที่สร้าง duration ใหม่
ใน employee_grade และ table อื่นๆ ที่มี column `score` มีค่า default เท่ากับ 0 แล้ว

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/af3b09fb-220c-470c-95a5-1e5fc593dd24)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b0a52b82-23c2-4601-afd2-6299e5d457ab)
