### ISSUE TITLE
[API][Duration] Fix bug create duration employee_grade has NULL kpi_evaluate_id and core_value_id

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#828]
Example on @UAT 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/cad0dfd4-1b92-4373-bf51-3c5dfd01b3af)

**Comment by wichita-ser** [comment]
ทดสอบด้วยการ Create new duration@DEV



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/44f70d43-4754-4c19-911e-5cf3e69d6fc1)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b1708cff-9aca-40c2-858c-e91ed2a1c970)
