### ISSUE TITLE
[Function] Handle function upload on add department (admin) and validate based on the division that they select

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#83]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6a7f925e-9b83-48d9-8156-64591d6c82ad)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/019236dc-8c22-4cd9-b5b8-40676958c2f7)
