### ISSUE TITLE
[Duration] - เปลี่ยนชื่อรอบปลายปีเป็น 'Annual Performance Evaluation'

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#833]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/1a0943c9-bf19-471e-9d56-86e9ea74afbb)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6866e365-245a-49aa-9f6a-18ef97cdafb5)
