### ISSUE TITLE
[API][Summary] Grade report ดึงคะแนน admin มาทำให้มีคะแนนไปตัดเกรด

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#841]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/50f6f451-881a-4acb-8d7f-003b9b4f768c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d9ff4737-6e23-4eef-9c7b-df6aae4a7eab)
