### ISSUE TITLE
[API][Summary] จำนวนทีม member ของพี่อาร์มไม่ครบ

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#842]
Recheck team member ของ sup ที่มี team member ลึกลงไป ไม่ครบ

**Comment by wichita-ser** [comment]
Note: 
รอหน้าบ้าน ให้ไม่ต้องส่ง value ใน filter มา ถ้าไม่ได้กด search

**Comment by nawapornmanyanon** [comment]
https://github.com/S4-Internal-app/Evaluated/issues/846
