### ISSUE TITLE
[Summary][Gradereport] - กรณี Adjust grade แล้ว กราฟ Grade report ไม่เปลี่ยนตาม

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#843]
กรณี Adjust grade แล้ว กราฟ Grade report ไม่เปลี่ยนตาม  refresh ก็ไม่มา

Expected to result
### M-lab มี A+  1 คน  , B 3 คน

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/366e21fc-43cb-4e6f-af36-09be39146355)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4bf71638-defa-4f18-861f-d2b860d44889)

**Comment by nawapornmanyanon** [comment]
- https://github.com/S4-Internal-app/Evaluated/issues/829   @wichita-ser ไม่แน่ใจว่าเส้นนี้มั้ย

**Comment by wichita-ser** [comment]
เจอว่า พี่โจ้มีเกรด แต่ว่าไม่ได้แสดง -> total score เป็น 0
อาจจะต้องเช็คตั้งแต่จังหวะ assign grade ค่ะ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9858ae3b-0a29-4b02-9a97-e4d631ea6d30)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/763fd264-eafd-4c9d-852b-901e10f8cc3d)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/632a0ef5-62e6-4655-a5f9-e07e805d60ff)
