### ISSUE TITLE
[KPISetting][ScoreByAdmin] - ใน Score by admin list มีแสดง IA  แต่พอกด update score ไม่ข้อมูลให้กรอกคะแนน

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#844]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2283e1f1-fd97-4bec-9ee7-2b595d1522c0)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/251e055e-d7a5-4512-a00e-5d93a8464fab)

**Comment by sainamphung** [comment]
division_id ใน table year_to_department_kpi ผิด ต้องแก้ manual ที่ DB เลย
(บัคจากเฟส 1 ชื่อ department กับ division เหมือนกัน แล้วไม่ได้ filter จาก type)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/17357ac2-1935-49d7-ad21-63eb274ca783)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/00de09fd-7c79-4419-a87f-92502d364c56)
