### ISSUE TITLE
[Summary] - กรณีพี่อาร์ม Login หน้า Smmary ทุก tab พี่อาร์มต้องเห็นน้องพี่นาถ

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#846]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2b116c81-4e96-4616-9e4c-32d421045da8)

## Expected to

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/202383e0-ef45-43eb-af1b-2320018febf5)

**Comment by warakornlj** [comment]
เหลือ Tab Department Score กรณีไม่ใส่ ยังเป็นรวมอยู่ ฝากหลังบ้านดูทีครับ @sainamphung @wichita-ser 




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/8524b2a1-8a95-465d-8220-dad6e3d4c440)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/31d604ea-3faa-4953-8e6f-b4058c144206)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/eb08f619-a83a-4204-9486-4fd48820d88d)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8efd5934-bef9-433c-a8a8-9ce7c14125bb)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/87347e33-5d95-43bb-b221-54edce3e1486)




![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a5fc908b-ebfe-4837-9f41-2a2495aef2c1)
