### ISSUE TITLE
[API][Evaluate] - แก้ HI07000 เป็น CS11000 ที่จะรับภาพรวม

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#855]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/131150937/9bc55a4f-8af2-417c-92ef-bce4815e4363)

**Comment by nawapornmanyanon** [comment]
รอหน้าบ้านมี CS11000 แสดงที่ Auto Score เด๋ว Check เขารับอะไกันแน่
@nawapornmanyanon

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/87c92867-117d-4a89-94a8-cef448643016)
