### ISSUE TITLE
[Data][AutoScore] - Auto score ไม่ขึ้น

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#858]
Auto score ไม่ขึ้นเพราะ division_name เป็น null ทำให้ sorted ไม่ได้
รอพี่หญิง confirm ก่อนว่า GB01000 เปลี่ยนเป็นอะไร เพื่vจะได้ clean data ใน DB

**Comment by sainamphung** [comment]
ตอนนี้แก้เป็น filter out KPI ที่ไม่มี divison_name ไปก่อน

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/92877807-a40d-42bb-b3df-b0f6e64e4c3f)
