### ISSUE TITLE
[Data][DepartmentKPI] - เชคเรื่อง KPI ของ division GB01000

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#863]
Division GB01000 โดยเอาออกไปแล้ว แต่รอบที่แล้วมี KPI อยู่ ต้องตรวจสอบตามนี้

1. KPI ของ GB01000 มีกี่อัน id อะไรบ้าง
2.  มี employee ที่รับ KPI ของ GB01000 หรือไม่

**Comment by sainamphung** [comment]
1. มี department KPI ของ GB01000 อยู่ 3 อันเป็น auto score ทั้งหมด id = 119, 120, 121
2. kpi_evaluate_id = 664, 1699 มีคนที่รับ KPI จากจ้อ 1 แค่คนเดียว weight เค้ารับเป็น 70 30 แต่เหมือนว่าเค้าไม่ได้ประเมิน individual เพราะคะแนนยังเป็น 0 อยู่เลย
3.  employee_id = 04037 ตอนนี้ย้ายไปอยู่ GB03000 แล้ว

**Comment by nawapornmanyanon** [comment]
employee_id = 04037

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0ce6fc61-6b55-49b9-afda-e4cbf671c119)
