### ISSUE TITLE
[API][Summary] 9 boxes grid เอา auto score มาคิด

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#864]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/a1d95fc0-c544-4b82-b9c3-84611d94e360)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/46d40abc-1326-4e98-9855-8dcc4e595e49)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9a3fd707-3020-4d21-a8c6-e4ef1f7c2960)

**Comment by nawapornmanyanon** [comment]
@nawapornmanyanon  Check กับน้องอีกที @wichita-ser

**Comment by wichita-ser** [comment]
Fixed ka

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/430f8b63-08f3-49bd-a37e-14601b29e469)

**Comment by nawapornmanyanon** [comment]
@wichita-ser ต้อง filter คนที่ยังไม่มี คะแนน ออกจากกล่องด้วย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4ffa6d5c-bd25-4987-aa67-dd609b81aafe)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/43dbde7f-c84b-4d77-b361-8413d2e0ade5)
