### ISSUE TITLE
[API][Summary] department kpi ให้เรียงมาด้วย

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#865]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9126ef3c-4197-4827-a6fb-bfbf56f7c1cd)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1809ef49-179e-401a-a98c-e1f3db513678)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/56ea5287-b637-4d3a-b442-bb547a299734)
