### ISSUE TITLE
[DB] Clean data duration รอบที่แล้ว เรื่อง employee มี supervisor evaluate 2 รอบ

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#869]
@TEST duration_id = 1
คิดว่าเป็นตั้งแต่ phase แรก

core value detail มีการซ้ำกัน 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/af991219-3520-432f-bfcc-fe3c40cb4fa9)

**Comment by wichita-ser** [comment]
@TEST UAT PROD
employee id ที่ clean core value ไป:  02185, 02852, 03044, 03494, 03560, 03808, 04037, 04257

**query check:**
```
select
	cv.core_value_id,
	cv.employee_id,
	cvd.choice,
	cv.duration_id,
	count(cvd.evalutor_id) as count_cv
from public.core_value_detail as cvd
join public.core_value as cv
	on cv.core_value_id = cvd.core_value_id
	and cvd.evalutor_id != cv.employee_id
group by cv.core_value_id, cvd.choice, cv.employee_id, cv.duration_id
order by count_cv desc,  choice, core_value_id

```

**Comment by nawapornmanyanon** [comment]
เชคผ่าน   UI 
employee id ที่ clean core value ไป: 02185, 02852, 03044, 03494, 03560, 03808, 04037, 04257

ติดแค่ 2 คน คือ 03414 , 04037  เป็นคนที่ออกไปแล้ว จะมีข้อมูลที่ หลังบ้าน


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/97d6ab63-f7ce-4c58-b940-f3b58085c0e2)
