### ISSUE TITLE
[Query] - Login and get employee data from DB

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#87]
1. login โดยใช้แต่ username อย่างเดียวไม่ต้องใส่ password แล้วไปดึง email มาจาก mockup data
2. เอา email ที่ได้จากข้อ 1 มา query data จาก DB อีกที (ตรงนี้ต้อง check ด้วยว่าเป็น admin ด้วยหรือเปล่า และดูแลส่วนไหน)
3. เอาจากข้อ 3 มาใส่ไว้ใน store

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f8dc544d-3fb4-4781-b3d4-058a4f420c61)
