### ISSUE TITLE
[Login][Landing get token] - Round ยังไม่เปิด หรือหมดไปแล้ว employee ต้องเข้าไม่ได้ แล้ว แสดง modal ให้เด้งไปหน้า log in

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#871]
ส่วนของ Employee 
Start Date   >>> ใช้วันที่จาก Process Employee evaluation: Start Date   
End Date   >>> ใช้วันที่จะ Duration : End date ( รอบใหญ่ )

ส่วนของ Teammember 
Start Date   >>> ใช้วันที่จาก Process Supervisor evaluation: Start Date   
End Date   >>> ใช้วันที่จะ Duration : End date ( รอบใหญ่ )

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9cd382c7-7bb1-4f3a-a008-e20fe2e157ca)

**Comment by nawapornmanyanon** [comment]
กรณียังไม่ถึงรอบการประเมิน ใช้ Start Date - End  Date จาก Duration ( รอบใหญ่ )

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b4ed95e3-9eec-41f6-89b2-c6fcddc12ee2)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec   ถ้ายังไม่ถึงวัน Start Date Disable ปุ่ม Evaluation ทั้ง 3 ส่วนไว้ก่อน


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d8f80c10-bdfe-4223-a19e-ff3fae79abf5)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec 
### Step 1


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a4d3f6ee-66f9-4189-b6b4-fe6e3f98f47f)

### Step 2


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/b8fe44f7-3ce3-4947-8564-5e62582deb13)

### Step 3

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bc1e4b2e-1642-42ac-956f-9bd8784decc9)

**Comment by nawapornmanyanon** [comment]
@TanawatMfec  
จาก Comment ตาม Step ข้างบน ถ้า Admin แก้ Startdate  แล้ว เปิดไปหน้า Evaluation ข้อมูลของวันที่ จะยังไม่เปลี่ยนตามที่อก้ให้  แต่ถ้ากด Refresh ข้อมูลก็จะเปลี่ยนตามที่ admin แก้ไข 



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8f63af97-d732-4990-9b5a-0e8dc1f5164c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a64050ff-1a48-46d3-a7f2-b4b338e83c00)
