### ISSUE TITLE
[Home][Previous] - Self report ดึง Total score มาแสดงผิดค่า

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#874]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7608abbd-5e8b-42aa-b8ee-a30c79b1b826)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/319e939e-ac9f-4012-bb44-fd76059acc74)
