### ISSUE TITLE
[Home][Previous][TeamMember][SummaryReport] - เรียง Column ใหม่

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#877]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/229ef72f-3d23-4f6d-b2c8-2d3359281ff9)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/91c43d73-0185-4925-aff0-a784ad6d3a88)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8963b18c-ac18-43ca-8c95-e69047ca6eb1)
