### ISSUE TITLE
[Function] - Logout

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#88]
Clear all store value

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e129171b-4cd3-4c9e-910c-e978868b8e4e)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7f9b4f89-a2bc-4336-8d96-2b5db3657452)
