### ISSUE TITLE
[Summary][9Box] - กรณี คะแนน %  KPI total กับ %Core value เป็น 0  จะต้องไม่แสดงเกรด  และเขาจะต้องยังไม่ถูกตัดลง BOX เพราะคะแนนยังเป็น 0  อยู่

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#880]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3379fa24-baef-4aa7-b1a2-62a756fc25e2)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/723fad4d-8cbe-4479-b28a-80bf6d4272bf)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8dbf7cfc-239a-49e5-8a93-7ea0f6364b14)

ไม่เห็นมี อ่า  condition อย่างงัยนะ @warakornlj

**Comment by warakornlj** [comment]
โจ้ดัก Condition ต้อง KPI Total score(%) กับ Core Value score (%) มากกว่า 0 เกรดถึงแสดงครับ กรณีที่พี่วง Core Value score (%) มันยัง 0 อยู่ เกรดเลยไม่แสดงครับ 

หรือโจ้เข้าใจโจทย์ผิด

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/b47f8391-eef1-494a-a54d-11aacff42354)





![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/d0ffe3ed-695b-4851-9bff-9287308bbf3e)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4071c25f-a259-44d3-9022-28043d515adb)
