### ISSUE TITLE
[Summary][DepartmentScore] - ของ Msyne ไม่มี DATA เลย  แต่ถ้าดูใน Department KPI admin  upload เข้าไปนะ

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#882]
Consultant Solution Services

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ddbdad01-db07-4e19-a60a-41355a42a414)

**Comment by wichita-ser** [comment]
**Investigate result:**
1.ไม่มี employee คนไหนใช้ department kpi ของเเดิมที่ MS0000 ถูก assign ผิด
(คนใน department นี้ (MS00000) ใช้ department_kpi_id 31, 42, 20, 8 ซึ่งเป็นของ PE)

2.ข้อมูลใน year_to_department kpi ของ MS00000 ตอนนี้เหมือนกับ TS00000 (จึงคาดว่า upload file department kpi ของ TS0000 เข้ามาที่ MS00000 ทำให้เขาผิด)

 
**Solution:**
แก้ division_id ที่มีตอนนี้ให้ถูกต้องเลย คือ 
TE01000 เป็น MS01000
TE02000 เป็น MS02000
TE04000 เป็น MS03000
TE05000 เป็น MS04000
TE06000 เป็น MS05000
TE0700 เป็น MS06000
TE08000 เป็น MS07000

ซึ่ง solution นี้จะไม่กระทบ employee  คนไหน เพราะไม่มีใครใช้อยู่แล้ว

**Comment by wichita-ser** [comment]
Auto score ใน table `bu_performance_result` มีแต่ type STG
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/32b1ba8e-cd46-447f-b2f4-895b79805ecb)

**Comment by sainamphung** [comment]
แก้เรื่อง costcenter ใน API auto score list ด้วย

**Comment by nawapornmanyanon** [comment]
@TEST
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9a906a2f-9539-4e02-ae25-1dee1e16c9cc)
