### ISSUE TITLE
[Handle Refresh Page] - อัพเดท ข้อมูล Round ใหม่ ให้ user ทุกครั้ง ที่เค้ากด refresh page

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#884]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/132323829/096867ce-929a-415c-b612-d751f07ba68c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/61646a74-3096-4269-8ab3-2da846e54cbc)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7dbbb93c-c61d-44fa-b7ff-4d12fd3e3e3a)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ee4130aa-81f4-4daf-9b6c-23e88462b0bc)
