### ISSUE TITLE
[Data] Clean data เรื่อง employee department kpi

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#888]
Duration id = 2 
ENV = PROD

**Clean step:**
1. Query ดูใน `year_to_department_kpi` ว่า division_id, department_id นี้ใช้ department_kpi_id อะไรบ้าง -> ทด department_kpi_id ไว้
2. Query ดูใน `kpi_evaluate`  ว่าใครอยู่ใน division, department นี้บ้าง และมี kpi_evaluate_detail อะไรบ้าง
3. เอา kpi_evaluate_detail มาดูว่ามี deparment_kpi_id อะไรบ้าง -> ทด department_kpi_id ไว้
4. เอา department_kpi_id ทั้งสองที่ทดไว้ มาเทียบกันว่าแทนกันได้มั้ย
5. ถ้าแทนได้ ก็ update set ใน table ได้เลย

**Checklist**
| office_code"| parent_code | office_name                                    | @TEST | In progress by | @PROD |
|---------------|---------------|---------------------------------------------------|--------|-----|-----|
| "AF01000"     | "AF00000"     | "Accounting"                                      | ✅ | |✅|
| "AF03000"     | "AF00000"     | "Financial and Budget"                            |  | |✅|
| "AF04000"     | "AF00000"     | "Purchase"                                        |  | |✅|
| "AF05000"     | "AF00000"     | "Warehouse"                                       |  | |✅|
| "AF06000"     | "AF00000"     | "Office of Corporate Finance Operation"           |  | |✅|
| "CS06000"     | "CS00000"     | "Office of Corporate Operation"                   |  | |✅|
| "CS09000"     | "CS00000"     | "Project Management"                              |  | |✅|
| "CS10000"     | "CS00000"     | "Corporate Lawyer"                                |  | |✅|
| "CS11000"     | "CS00000"     | "Helpdesk"                                        |  | |✅|
| "CS12000"     | "CS00000"     | "Customer Success"                                |  | |ไม่มีใน year to|
| "ES01000"     | "ES00000"     | "Business Solution"                               |  | |✅|
| "ES02000"     | "ES00000"     | "Business Service Management (BSM)"               |  | |✅|
| "ES03000"     | "ES00000"     | "Digital Information Services (DIS)"              |  | |✅|
| "ES04000"     | "ES00000"     | "Digital Platform and Management (DPM)"           |  | |✅|
| "ES05000"     | "ES00000"     | "Application Solution"                            |  | |✅|
| "ES06000"     | "ES00000"     | "MarTech Innovation"                              |  | |✅|
| "ES07000"     | "ES00000"     | "Integration Solution"                            |  | |ไม่มีใน year to|
| "ES08000"     | "ES00000"     | "Data Intelligence"                               |  | |ไม่มี Employee|
| "EX01000"     | "EX00000"     | "Office of Executive"                             |  | |✅|
| "GB02000"     | "GB00000"     | "Sales Government"                                |  | |✅|
| "GB03000"     | "GB00000"     | "Sales Innovation"                                |  | |✅|
| "HI01000"     | "HI00000"     | "Information Security"                            |  | |✅|
| "HI02000"     | "HI00000"     | "Networking and Cisco Customer Experience"        |  | |✅|
| "HI03000"     | "HI00000"     | "Cloud Solution Services"                         |  | |✅|
| "HI04000"     | "HI00000"     | "IT Operation Managed Services"                   |  | |✅|
| "HI05000"     | "HI00000"     | "System Infrastructure"                           |  | |✅|
| "HI06000"     | "HI00000"     | "IOT and Smart Solution"                          |  | |✅|
| "IA01000"     | "IA00000"     | "Internal Audit"                                  |  | |ถูกอยู่แล้ว|
| "IN01000"     | "IN00000"     | "Innovation Lab"                                  |  | |ไม่มี kpi_evaluate_detail|
| "IN02000"     | "IN00000"     | "Venture Lab"                                     |  | |✅|
| "IN03000"     | "IN00000"     | "M-Lab"                                           |  | |✅|
| "IN04000"     | "IN00000"     | "Digital Sustainability"                          |  | |✅|
| "MS01000"     | "MS00000"     | "Sales"                                           | ✅ | |✅|
| "MS02000"     | "MS00000"     | "Program Management Office (PMO)"                 | ✅ | |✅|
| "MS03000"     | "MS00000"     | "Service Delivery"                                | ✅ | |✅|
| "MS04000"     | "MS00000"     | "Data Intelligence"                               | ✅ | |✅|
| "MS05000"     | "MS00000"     | "Customer Services and Support"                   | ✅ | |✅|
| "MS06000"     | "MS00000"     | "Strategic Planning"                              | no employee |-| -|
| "MS07000"     | "MS00000"     | "Solution Consultant"                             | no employee  |-|-|
| "MT01000"     | "MT00000"     | "Office of MTIS BU"                               |  | |✅|
| "MT02000"     | "MT00000"     | "Sales and Marketing"                             |  | |✅|
| "MT03000"     | "MT00000"     | "MTIS Services Delivery"                          |  | |✅|
| "PE01000"     | "PE00000"     | "People Business Partner (PBP)"                   |  | |✅|
| "PE02000"     | "PE00000"     | "Talent Acquisition (TA)"                         |  | |✅|
| "PE03000"     | "PE00000"     | "People Development and Growth (PDG)"             |  | |✅|
| "PE04000"     | "PE00000"     | "People Benefits and Well-being (PBW)"            |  | |✅|
| "PE05000"     | "PE00000"     | "HR Solution Services"                            |  | |✅|
| "SL02000"     | "SL00000"     | "Enterprise Business"                             |  | |✅|
| "SL03000"     | "SL00000"     | "Office of Commercial Business Sales"             |  | |ไม่มีใน year to|
| "SL09000"     | "SL00000"     | "Sales Banking Financial Service Industry (BFSI)" |  | |มีใช้ของคนอื่น|
| "SL17000"     | "SL00000"     | "Innovation Solution"                             |  | |ไม่มีใน year to|
| "SL18000"     | "SL00000"     | "Industry Presales"                               |  | |✅|
| "SL99000"     | "SL00000"     | "Sales Coordinate"                                |  | |✅|
| "ST01000"     | "ST00000"     | "Strategy Office and Business Development"        | ✅ | Phung |✅|
| "ST02000"     | "ST00000"     | "Center of Excellence"                            | ✅ | Phung |✅|
| "ST03000"     | "ST00000"     | "Partner Relation"                                | ✅ | Phung  |✅|
| "ST04000"     | "ST00000"     | "Risk and Compliance"                             | ✅ | Phung   |✅|
| "ST05000"     | "ST00000"     | "Office of Corporate Secretary"                   | ✅ ถูกอยู่แล้ว | Phung  |ถูกอยู่แล้ว|
| "ST06000",    | "ST00000",    | "Corporate Communication and Branding"            | ✅ ถูกอยู่แล้ว | Phung |ถูกอยู่แล้ว|
| "TE01000",    | "TE00000",    | "Sales"                                           | ✅ | Phung |✅|
| "TE02000",    | "TE00000",    | "Data Intelligence"                               | ✅ | Phung |✅|
| "TE04000",    | "TE00000",    | "Program Management Office (PMO)"                 | ✅ | Phung |✅|
| "TE05000",    | "TE00000",    | "Service Delivery"                                | ✅ | Phung |✅|
| "TE06000",    | "TE00000",    | "Customer Services and Support"                   | ✅ | Phung |✅|
| "TE07000",    | "TE00000",    | "Strategic Planning"                              | ✅ | Phung |✅|
| "TE08000",    | "TE00000",    | "Solution Consultant"                             | ✅  | Phung |✅|

**Comment by sainamphung** [comment]
*Note*
| office_code"| parent_code | office_name                                    | Remark |
|---------------|---------------|---------------------------------------------------|--------|
| "IN01000" | "IN00000" | "Innovation Lab" | พี่เท้อยู่ division นี้คนเดียว ไม่ต้องประเมิน |

**Comment by wichita-ser** [comment]
Note:
![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/cfa759b8-3efd-482d-b462-27a7f7c2f535)

**Comment by wichita-ser** [comment]
ไปแก้เรื่อง SL09000 รับ division ของคนอื่นที่การ์ด https://github.com/S4-Internal-app/Evaluated/issues/902

**Comment by nawapornmanyanon** [comment]
### Corporate Finance Operation, Purchase

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/99b7b583-9545-45ee-b9fc-30d7c61b626d)

**Comment by nawapornmanyanon** [comment]
### Corporate Finance Operation, Purchase

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/efd5df07-3137-44f2-852c-c824eee5a00b)

**Comment by nawapornmanyanon** [comment]
### Corporate Lawyer

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/36fed1ee-ef18-4bd0-8dd5-831e6f51b9e5)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4ffaf8d8-3866-47dd-9620-816e13c7841c)

**Comment by nawapornmanyanon** [comment]
### Corporate Operation Management, Helpdesk


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f9efcff2-d144-43e5-b26a-3bd886e90104)

**Comment by nawapornmanyanon** [comment]
### Corporate Operation Management, Office of Corporate Operation


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e6f9acb0-d39d-407f-b6d2-cf383a64c009)

**Comment by nawapornmanyanon** [comment]
### Corporate Operation Management, Project Management
00554  Waralee Onpol  - Senior Project Administrator-  Resource Performance  >> คนนี้ถูก
ดูไว เหมือนคนที่เหลือจะผิด

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/96a40272-c9d6-454d-9c51-16ba13eb0782)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1f917d8-1683-419c-9d6a-3b8207e2694e)

**Comment by nawapornmanyanon** [comment]
### Corporate Strategy Planning and Management, Partner Relation
Measurements  ผิด >> อาจจะผิดจาก File ที่ upload
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/beb3c6b4-18f7-4abd-b6ac-8fd69e933c24)

**Comment by nawapornmanyanon** [comment]
### Corporate Strategy Planning and Management, Risk and Compliance


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ebd72ef1-82b1-43c1-9138-34bfe4806f59)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d92afba4-4c48-4534-9ee0-2cace1e1bdbf)

**Comment by nawapornmanyanon** [comment]
### Commercial Business Sales, Sales Coordinate


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/49afe2b2-aad8-4185-ac67-525a0afced98)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/08fbe5b9-abd0-4e47-a871-9e34a58e144d)

**Comment by nawapornmanyanon** [comment]
### Government Business Sales, Sales Innovation
04037  Phawasud Kaeobunma  >> Recheck ทำมั้ยรับ 3 ไม่เหมือนเพื่อน


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/53fab0f8-9fda-4aab-a7b0-0309c2d35c5b)

**Comment by nawapornmanyanon** [comment]
### Hybrid Infrastructure Services, Cloud Solution Services


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1583a1a0-21e8-48a9-b358-182496918c28)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a2f4198c-3347-447e-b638-7e0902afccea)

**Comment by nawapornmanyanon** [comment]
### Hybrid Infrastructure Services, Information Security


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1397a861-d1d1-4182-a2f5-e69ecac6d5da)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/642b8cc5-05ca-4db6-bd6b-d3f0544bd069)

**Comment by nawapornmanyanon** [comment]
### Department  highlight สีเหลือง ต้อง Recheck ใหม่

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/268fe56e-3892-40b8-b5b1-72491f160eef)


[BUG-888-Data_DepartmentKPI_Table.xlsx](https://github.com/S4-Internal-app/Evaluated/files/13663739/BUG-888-Data_DepartmentKPI_Table.xlsx)

**Comment by sainamphung** [comment]
**Sales Coordinate** -> Assign ซ้ำ , meaturement ผิด
**Purchase** -> department_kpi_id ผิด
**Corporate Lawyer** -> Assign ซ้ำ , meaturement ผิด
**Helpdesk** -> Assign ซ้ำ , meaturement ผิด
**Office of Corporate Operation** -> data ผิดเยอะ ข้ามไปก่อน *************************
**Project Management** -> Assign ซ้ำ , meaturement ผิด
**Partner Relation** ->

**Comment by nawapornmanyanon** [comment]
- [ ] Sales Coordinate -> Assign ซ้ำ , measurement ผิด
- [ ] Purchase -> department_kpi_id ผิด
- [ ] Corporate Lawyer -> Assign ซ้ำ , measurement ผิด
- [ ] Helpdesk -> Assign ซ้ำ , measurement ผิด
- [ ] Office of Corporate Operation -> data ผิดเยอะ ข้ามไปก่อน *************************
- [ ] Project Management -> Assign ซ้ำ , measurement ผิด
- [ ] Partner Relation -> measurement ผิด
- [ ] Risk and Compliance -> Assign ซ้ำ , measurement ผิด
- [ ] Cloud Solution Services -> Assign ซ้ำ , measurement ผิด, department_kpi_id ผิด
- [ ] Information Security -> Assign ซ้ำ , measurement ผิด
