### ISSUE TITLE
[Save data] [Core Value] - ระบบต้องเซฟ data ถ้าเกิด vpn หลุด หรือ APi แตก ตอนกด submit - Handle ทั้ง Employee กับ supervisor ประเมิณ - Supervisor ประเมิณพี่โจ้ แล้ว VPN แตก => หลังจากนั้นไปกดประเมิณคนอื่น => กลับมาหาพี่โจ้อีกที ระบบก็จะแสดง data ที่เคยกรอกไว้ด้วย

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#889]
กระทบ ทั้ง Flow ของการทำ Core Value ทั้งฝั่ง Employee, Sup 

กระทบ การแสดงผล ก่อน ทำ และ หลังทำ ทั่้งหมด

**Comment by nawapornmanyanon** [comment]
### Self - Core value


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/6385f85b-371c-4129-85cb-389ee470fcd3)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/cd5a8170-eaaf-47cb-9f84-7bac3e56141f)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d7504d79-b003-4907-b0c2-cf0f1de4e502)

**Comment by nawapornmanyanon** [comment]
### Evaluate team member by Supervisor 


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e824e834-04fa-41cc-aa5e-c8cd5e30933d)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f7ba2b27-f4bb-4d7e-bdd0-6910578666db)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c3dc49d4-d50c-4ff7-b642-b788cf816fea)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9a4e958e-cdbb-4e1f-9ead-ac3dc954d641)

**Comment by nawapornmanyanon** [comment]
### Re Evaluate core value By Sup


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/663dfffe-6db1-45eb-93d8-db7e994d36eb)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/938a12fd-afc3-4aa0-a784-f61a564ee0e5)
