### ISSUE TITLE
[Save data] [Engagement] - [Save data] [Core Value] - ระบบต้องเซฟ data ถ้าเกิด vpn หลุด หรือ APi แตก ตอนกด submit

### ISSUE THREAD

**Issue by TanawatMfec** [S4-Internal-app/Evaluated#890]

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ccdc8b1d-1538-4e5d-95de-1f31ec493155)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f9a338fd-330a-473a-9f26-0aa128735a85)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bb5c48b7-ffd4-43c4-98af-507d89f750d6)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/65ae6cf2-57de-4be4-bda9-2236fed8c10e)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7513c36c-800f-4ef0-bc75-b7ab9fe38cff)

**Comment by nawapornmanyanon** [comment]
กรณี VPN หลุด แล้วไม่กด Submit  >> ต่อใหม่แล้ว >> หน้า Engagement ระบบจะยังจำข้อมูลที่เคยกรอกไว้ 

ระบบจะ clear store ตอนกด Submit สำเร็จ

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/30493039-719b-4bc6-b1da-047f666da0e0)
