### ISSUE TITLE
[Summary][Grade Report][UI] - เพิ่ม tooltip

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#892]
**Performance Grading ℹ️**

A+ | Outstanding   - สูงกว่ามาตรฐานมาก
A | Exceed   - สูงกว่ามาตรฐาน
B | Achieve   - มาตรฐาน
C | Need   Improvement – ควรปรับปรุง
D | Unacceptable   - ควรปรับปรุงอย่างมาก

เหมือน Corevalue 

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/7b93cc86-5192-4796-bff1-126a27946282)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/71511334-ec6b-4c2e-b3dd-b53668cea807)

**Comment by warakornlj** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/ab08b878-5af4-4608-9488-964d6271d13c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4214564f-2835-416c-ba04-781b7b8212c8)
