### ISSUE TITLE
[Home]{Previous][SummaryReport] - 1.  ใส่เลขข้อให้หน่อย , 2.  แก้คำจาก KPI   เป็น KBI

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#893]
1.  ใส่เลขข้อให้หน่อย 
2.  แก้คำจาก KPI   เป็น KBI

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c224aa80-32e3-46c7-9ab0-58264af64fe3)

**Comment by warakornlj** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/48aaa861-d060-4839-9d92-e425fe4966a2)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/19c7a677-2aa8-4043-a708-b4c8fadf031d)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/4ee8ec4e-8b44-4513-8d91-cb1358640ffe)
