### ISSUE TITLE
[DB] - ต้องเพิ่มข้อมูล Core valuew ของพี่เตย  อีก 2 row เพิ่อให่้มีข้อมูลแสดง

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#895]
เพิ่มข้อ 6 กับ 7 เป็น Score 4 ( เดาจากคะแนนที่มีอยู่ เป็น 4 ทั้หมด น่าจะ BUG เฟส 1 ที่จังหวะ save แล้วไม่ลง )

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/f2a3e6f9-b713-4493-a3e2-5b849f3c6d2f)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9ad54082-f2d7-4a5d-8477-f5dac5f4b98d)

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/03b7e00f-7924-47d1-a1b4-0846c8e59986)

**Comment by wichita-ser** [comment]
@TEST UAT PROD
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/1c5c7008-86ae-48af-a0d6-b451d49c1b31)

Related SQL Query
```
select * from public.core_value where employee_id = '04353' and duration_id = 1
-- core_value_id = 788

// List core value detail
select * from public.core_value_detail where core_value_id = 788 order by choice

// Insert choice 6
insert into public.core_value_detail
(core_value_id, choice, score, evalutor_id, created_date, created_by, updated_date, updated_by)
values (788, 6, 80, '04353', NOW()::timestamp, 'Wichita', NOW()::timestamp, 'Wichita')

// Insert choice 7
insert into public.core_value_detail
(core_value_id, choice, score, evalutor_id, created_date, created_by, updated_date, updated_by)
values (788, 7, 80, '04353', NOW()::timestamp, 'Wichita', NOW()::timestamp, 'Wichita')
```

**Comment by wichita-ser** [comment]
ตรวจสอบแล้ว employee ที่เหลือ ไม่มีคนที่ข้อหาย
มีแต่คนที่ supervisor ไม่ได้ประเมิณ

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/43415130-2ddb-4d20-b0d1-09bac96bc370)
@PROD


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/aad107ac-d8a1-4883-9ced-735757de2154)
