### ISSUE TITLE
[Data] - Check division ของ employee ที่ย้ายทีม

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#899]
employee ที่มีเปลี่ยนแปลง cost center ตั้งแต่เดือน 6 
date | emp_id | name | old | new | old division | new division | Change division | ลาออก |
-- | -- | -- | -- | -- | -- | -- | -- | -- |
9/28/2023 | 04865 | Thanradee Thawiyok | HI04020 | HI04030 | HI04000 | HI04000 | |✅|
9/13/2023 | 02781 | Yuttana Noiphlai | HI04020 | HI04030 | HI04000 | HI04000 | |✅|
9/11/2023 | 04843 | Phollakit Thongchaui | HI04030 | HI04020 | HI04000 | HI04000 | |✅|
8/11/2023 | 01122 | Aim-on Kanjanasanit | TE04040 | TE04020 | TE04000 | TE04000 | | |
8/1/2023 | 03560 | Mechai Prawsri | HI04030 | HI04020 | HI04000 | HI04000 | | |
7/25/2023 | 04834 | Monai Sirisethakarn | HI04020 | HI04030 | HI04000 |HI04000 | | |
7/24/2023 | 02837 | Tinbodee Hassakatt | CS06010 | CS06020 | CS06000 | CS06000| | |
7/21/2023 | 03469 | Pakawoot Chutchotik | HI01040 | HI01010 | HI01000 | HI01000| | |
7/17/2023 | 04804 | Prapusak Thaensuwan | HI07010 | HI01070 | HI07010  | HI01000 |✅|✅|
7/10/2023 | 01958 | Tuchchai Apinuntakulchai | ES03010 | ES03020 |ES03000|ES03000| | |
7/6/2023 | 04580 | Kawipat Nguyen | HI05020 | HI04020 |HI05000|HI04000|✅|✅|
7/2/2023 | 04804 | Prapusak Thaensuwan | HI01070 | HI07010 |HI01000|HI07000|✅|✅|
7/2/2023 | 01958 | Tuchchai Apinuntakulchai | ES03020 | ES03010 |ES03000|ES03000| | |
6/30/2023 | 00552 | Phatthinan Samanyaporn | TE05020 | TE06012 |TE05000|TE06000|✅| |
6/26/2023 | 02185 | Chatchaya Luckthum | TE03050 | TE05020 |TE03000|TE05000|✅| |
6/15/2023 | 04196 | Tharasu Koonharn | TE05020 | HI01030 |TE05000|HI01000|✅| |
6/15/2023 | 03407 | Pongsatorn Rungrueang | TE05020 | HI01040|TE05000|HI01000|✅| |
6/15/2023 | 03446 | Ekkarat Huakhao | TE05020 | HI01030 |TE05000|HI01000|✅| |
6/15/2023 | 00552 | Phatthinan Samanyaporn | TE06012 | TE05020 |TE06000|TE05000|✅| |
6/15/2023 | 00552 | Phatthinan Samanyaporn | TE05020 | TE06012 |TE05000|TE06000|✅| |
6/6/2023 | 03851 | Nontawat Kardyid | HI04010 | HI04020 |HI04000|HI04000| | |
6/2/2023 | 02185 | Chatchaya Luckthum | TE05020 | TE03050 |TE05000|TE03000|✅| |
6/2/2023 | 01449 | Pruchya Pattanakulanun | TE05020 | TE05010 |TE05000|TE05000| | |

**Comment by sainamphung** [comment]
บางคนมีเปลี่ยน division ด้วย อาจจะต้องไปถามพี่หญิงอีกทีว่าคนที่ย้าย division จะต้องรับ KPI แบบไหน

**Comment by wichita-ser** [comment]
**Answer:** ของคนที่ย้าย division ใหม่
- ถ้า duration ปัจจุบันให้รับ department kpi ของ division ใหม่
- ถ้า duration เก่า ให้รับ department kpi ของ division ตามเดิมไม่ต้องแก้

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/c25f0afb-4255-480b-8c9c-6f14d0880a8a)

**Comment by wichita-ser** [comment]
**Note:**
การเปลี่ยน department kpi ใน kpi_evaluate_detail
- เปลี่ยน 02185 ให่ใช้ TE05000 แทน TE03000 -> เพราะ TE03000 ไม่มี division นี้อยู่แล้ว
- 04196, 03407, 03446 ย้ายมาจาก TE05000 แต่ตอนนี้ใน DB เขารับจำนวนข้อตาม HI01000 ไม่แน่ใจว่าต้องจัดการอย่างไร

พรุ่งนี้ขอปรึกษาค่า @sainamphung

**Comment by sainamphung** [comment]
คนที่ย้าย เดือน 11
date | emp_id | name | old | new | old division | new division | Change division | ลาออก
-- | -- | -- | -- | -- | -- | -- | -- | --
11/30/2023 | 04613| Ploynapat Pitipornchotrawee| HI01000| GB03000| HI01000| GB03000 | ✅  | 
11/15/2023 | 04871| Porramet Yotha | PE04000| PE03000| PE04000| PE03000|  ✅ | 
11/01/2023 | 04871| Porramet Yotha | PE03000| PE04000| PE03000| PE04000| ✅  | 
10/31/2023 | 04230| Sirima Kitruenpiromsuk | PE04000| SL09000| PE04000| SL09000|  ✅|

**Comment by wichita-ser** [comment]
04230 รับของ PE04000 เหมือนเดิม ตามเคสในการ์ดนี้ https://github.com/S4-Internal-app/Evaluated/issues/902

**Comment by nawapornmanyanon** [comment]
สุ่ม Check : 01122 , 04834 , 02837 , 00552
