### ISSUE TITLE
[Data] SL09000 มี department kpi ของที่ไม่มีใน year to department และไม่ใช่ auto score type

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#902]
เช่น คุณ Sirima 04230 ตอนนี้รับทั้งหมด 6 ข้อ
คือ 
| department kpi id | name | measurement | target | auto |
| -- | -- | -- | -- | -- |
| 27	 | 15% turnover rate  | Employee demographic  report 2023 | 15% | |
| 28   | Quality of hire - Number of employee pass probation | Employee demographic  report 2023 | 90% | |
| 8 | KPI 7 - Resource Booking (RBI) | RBI  from Pivot report | 75% | |
| 19   | KPI 6 - Resource Utilization (RUI) | RUI  from Pivot report |  75% | |
| 6     | OLA recruitment of Manager Level  | TA Report | 75-90 Days | RUI |
| 11   |  OLA recruitment of officer Level | TA Report | 45-60 Days | |

แต่ว่า SL09000 ตอนนี้รับ แค่ 3 ข้อ
| department kpi id | name | measurement | target | auto |
| -- | -- | -- | -- | -- |
| 109 | KPI 8 - Strategic Conformance Ratio (STG) | Feedback from Green team report ... | meet target of Strategic conformance ratio | STG |
| 107 | KPI 2 - BU net profit | "NP from Pivot reports | 255 MB | NP |
| 108 | KPI 7 - Resource Booking (RBI) | "RBI  from Pivot reports | 75% | RBI |

ต้องเอาที่ไม่ใช่ของ division ของเขาเหล่านี้ออก
- 15% turnover rate
- Quality of hire - Number of employee pass probation
- OLA recruitment of Manager Level 
- OLA recruitment of officer Level

**Comment by nawapornmanyanon** [comment]
Sales_BFSI

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5417e1c3-55bc-4f78-874b-a3e3b20a0db2)

**Comment by wichita-ser** [comment]
จากที่คุยกับพี่อุ
K'Sirima (04230) จะต้องรับเหมือน P'Bon (01589) เนื่องจากว่าเพิ่งย้ายมาที่ division ใหม่เมื่อ Nov ทำให้ K'Sirima ยังรับ department kpi ตาม supervisor (P'Bon) อยู่ ทั้ง 2 รอบ durations

**แก้ไขเป็นดังนี้**
P'Bon
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/85c42eb3-5d2e-4bc4-b301-8571cd4d37b3)

K'Sirima
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/213bfff0-507c-4594-9a0d-12e49811d6bc)

และหลังจากนี้ ถ้ามีใครที่ย้าย division อีก Admin จะต้องเป็นผู้ทำการ assign ใหม่

**Comment by nawapornmanyanon** [comment]
![image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/0d1e6593-e9a5-4b3a-96e1-c17ff9c769fc)
