### ISSUE TITLE
[PMsetting][Overall] - แก้ชื่อ Column

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#903]
แก้ชื่อ Coulmn จาก Department_kpi  เป็น Department KPI

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ecb38a9a-4be6-4327-b83f-45e8dbc1ea64)

**Comment by warakornlj** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126637804/d8944d23-b4c6-4d9f-9905-2ff35d3a4d77)

**Comment by nawapornmanyanon** [comment]
Done
