### ISSUE TITLE
[Summary][SummaryTab] - กรณีที่มีคะแนนของ KPI score หรือ Core value core อย่างใดอย่างหนึ่ง ให้โชว์ total score

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#904]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/1a3359f6-4a32-463e-900f-d0db04367742)

**Comment by wichita-ser** [comment]
โค้ดส่วนที่คิดว่าต้องแก้ ตรงนี้
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/400efc02-34b9-4401-baef-737402e1a41d)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1469b51-c4f0-471d-9673-354aa3583ab0)
