### ISSUE TITLE
[PMSetting] - Order data Department KPI and  Individual KPI ?

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#907]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c98c4dc9-291c-4ec8-a08e-28777cb02c6e)

**Comment by nawapornmanyanon** [comment]
### Individual KPI

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/11fe32e8-b16b-419c-9dbf-32cb0529f28d)

**Comment by wichita-ser** [comment]
Dev Test:

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/9f5f0837-1653-4c85-a3a6-3e3ea4686271)
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/8b3e05f1-8649-4dae-8713-984820c11c67)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8ebe7e2c-9d92-4bb3-9d50-b4b7833fa786)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8067d67a-093e-4495-8490-f9b39dc066b7)
