### ISSUE TITLE
Order by

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#911]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/c786305e-e99e-446c-aa1d-490415993b30)

**Comment by wichita-ser** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/7cce63c3-57a7-40dd-a3be-c244a8471e2c)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/d76c196c-34c8-49cd-a627-c7b4c84c3625)

**Comment by wichita-ser** [comment]
แก้ไขใหม่ 
- เรียง perspective P R S
- เรียง department kpi name (KPI 8 อยู่ล่างสุด)

![image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/750ce75a-562f-4efe-af40-4ad5ece92e3b)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d2da9498-8564-47ff-99c0-33f3f6da0212)
