### ISSUE TITLE
[DATA] - Delete individual employee  ของ HI04030 ทั้งหมด 50 คน

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#912]
ลบ Individual KPI ทั้งหมด >> Round : Annual year

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ccae352e-c2f5-46c0-bfb3-ac25b5483f10)

EMP ID
--
01501
01575
01699
01771
01971
01973
01978
02206
02213
02279
02391
02576
02578
02632
02637
02646
02847
02863
02865
02930
03036
03074
03075
03089
03122
03140
03158
03166
03188
03191
03214
03236
03400
03560
03573
03606
03618
03764
03835
03878
04103
04326
04559
04566
04633
04641
04671
04712
04750
04834

**Comment by sainamphung** [comment]
- [ ] On production
- [ ] On test

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/2e987e5d-f0dc-4770-a9a5-2a361d81e80e)
