### ISSUE TITLE
[DATA] - Delete Department KPI ทั้งหมด >>  เนื่องจากเปลี่ยนชื่อ จาก Master Solution เป็น Application Solution

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#913]
Department KPI ทั้งหมด >>  เนื่องจากเปลี่ยนชื่อ จาก Master Solution เป็น Application Solution

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/82e8e03c-2417-4ef6-9a26-e417f8a4c05b)

EMP ID
--
01456
02120
02316
02469
02484
02509
02657
02734
02983
02996
03019
03043
03044
03114
03126
03161
03195
03250
03254
03292
03571
03572
03584
03595
03650
03870
03914
03948
03971
03987
03997
04001
04076
04077
04092
04131
04146
04205
04345
04469
04519
04569
04679
04685
04759

**Comment by sainamphung** [comment]
- [ ] Test
- [ ] Prod

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/32eb5e14-2f1e-471f-b587-f3fa19e5643f)

ลบเพิ่มจากหน้าบ้าน


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/d1233556-e531-471f-8d2f-627078afebd1)
