### ISSUE TITLE
[Summary] Cannot export summary

### ISSUE THREAD

**Issue by wichita-ser** [S4-Internal-app/Evaluated#914]
Login ด้วย P'Arm, P'Nat กด Export ไม่ได้ มีขึ้น error "ToastSagas.ts:30 Cannot read properties of undefined (reading 'data')"

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/b4ee785b-6931-4f39-83e7-23f87129d2c5)

**Comment by wichita-ser** [comment]
API มี response มา

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/4348240b-2c24-4417-89b7-d13ea3de1e3c)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/fcfd55ba-24c3-47f2-a7ec-4f43843e9412)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/410f66ef-db63-45ed-867b-faa81c8268ca)
