### ISSUE TITLE
[API][Auto Score][GET] - Get history log

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#916]
**Description**: Get recalculate history log list sort by created_date from latest
**Role**:
- Admin

**Table**:
- recalculate_history_log

**Params**:
- duration_id

**Response**:
```
{
 "logs": [
  {
   "auto_score_type": "NP",
   "month": 12,
   "recal_date": "",
   "recal_by": "email@email.com"
  }
 ]
}
```

**Comment by nawapornmanyanon** [comment]
@wichita-ser   แก้ให้ *required หน่อย

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e1bf230f-d194-4763-bd1b-724f1f67ee57)

**Comment by wichita-ser** [comment]
@nawapornmanyanon  ตอบค่า เออเร่อเพราะโค้ดค่ะ แก้ไขเรียบร้อยค่า

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/c9732bad-26ba-4f0d-abd6-3fe016e25c81)
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126653943/0fbd69f3-bed8-49a1-9a8f-89518cad4778)

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/9cb16a55-877a-46c2-b774-5c0c0f581d74)
