### ISSUE TITLE
[API][Auto Score][GET] - Edit API get auto score list

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#919]
เพิ่ม filter month กับ type ใน query string

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/99e4fd00-b9be-4bb1-ac61-114f4665dc52)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a14f599d-c38b-445e-a9cd-5285ed3096b3)
