### ISSUE TITLE
[API][Auto Score][GET] - Get auto score type list for dropdown

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#922]
**Description**: Get auto score type list for dropdown in recalculation page

**Role**:
- admin

**Response**:
```
{
 "type_list": [
    "NP", 
    "SPI", 
    "CPI", 
    "RUI", 
    "RBI", 
    "STG"
]
}
```

**Comment by wichita-ser** [comment]
[GET] /api/v1/admins/auto_score/types

**Comment by wichita-ser** [comment]
Deploy @DEV, TEST

**Comment by nawapornmanyanon** [comment]
### Done

![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/bc5447f3-e327-4ea7-acc5-c05810c998f5)
