### ISSUE TITLE
[Edit_Admin_List] - เป็น Department  หรือ Division ?

### ISSUE THREAD

**Issue by nawapornmanyanon** [S4-Internal-app/Evaluated#94]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/a5edc716-507e-41f2-a996-48c4e4a4a942)

MFEC มี 13 department , 56 Division

**Comment by sainamphung** [comment]
ให้เลือกแค่ระดับ division ค่ะ

**Comment by nawapornmanyanon** [comment]
@sainamphung  แสดงว่า ต้องเปลียนหัวข้อเป็น Division และ Placeholder เป็น Select division

**Comment by nawapornmanyanon** [comment]
สรุป เป็น Department  MFEC มีทั้งหมด 13 department
