### ISSUE TITLE
[Design] - Redesign individual KPI to be assign by supervisor

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#96]
include Assign department KPI

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/783cfe91-3a15-40ab-b838-2d6206f6bedd)


![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/e02b5931-0c27-4fcb-8bbd-b465e827c0f2)
