### ISSUE TITLE
[Function] - Only supervisor can set individual KPI to employee

### ISSUE THREAD

**Issue by sainamphung** [S4-Internal-app/Evaluated#99]
employee cannot see PM Setting in main menu

**Comment by nawapornmanyanon** [comment]
![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/ab228cda-5f35-481a-adf1-cf93a4176bc2)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/5ea57848-c0fb-409b-9c38-9a520f293898)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/8f3b3abe-c236-4646-816e-a393056ddb13)



![Image](https://github.com/S4-Internal-app/Evaluated/assets/126447414/3d9420ad-c3c3-47b4-8635-cfd98156c37b)
